pom.xml
src/main/java/uk/gov/pay/api/model/Link.java
src/main/java/uk/gov/pay/api/model/Links.java
src/main/java/uk/gov/pay/api/model/Payment.java
src/main/java/uk/gov/pay/api/model/PaymentConnectorResponse.java
src/main/java/uk/gov/pay/api/model/PaymentConnectorResponseLink.java
src/main/java/uk/gov/pay/api/model/PaymentEvents.java
src/main/java/uk/gov/pay/api/model/PaymentWithLinks.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceITest.java
src/test/java/uk/gov/pay/api/utils/ConnectorMockClient.java
swagger/swagger.json

- Created new extra link _next_post_url_ coming from Connector.
- Charges from connector are now deserialised using  Charge class rather than reading Json fields.

PP-486 Deserialisation next_url_post from Connector - Merge after pay-connector PP-486

---

src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
swagger/swagger.json

- Reflect the fact that searching charges, from_date is
inclusive and to_date is exclusive.

PP-631 Search charges API documentation changes

---

src/test/java/uk/gov/pay/api/it/PaymentsResourceITest.java

- Added a test that exercise the boundaries for for all the fields when create a payment.

PP-628 Added test with max-length boundaries fields to create payment

---

src/main/java/uk/gov/pay/api/model/PaymentError.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/test/java/uk/gov/pay/api/it/PaymentsCancelResourceITest.java
swagger/swagger.json

- Update to indicate new error body and error http status codes.
- Update existing resources (out of date).

PP-611 Update API documentation

---

src/main/java/uk/gov/pay/api/model/Payment.java
src/main/java/uk/gov/pay/api/model/PaymentConnectorResponse.java
src/main/java/uk/gov/pay/api/model/PaymentEvent.java
src/main/java/uk/gov/pay/api/model/PaymentForSearchResult.java
src/main/java/uk/gov/pay/api/model/PaymentState.java
src/main/java/uk/gov/pay/api/model/PaymentWithAllLinks.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/validation/PaymentSearchValidator.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceITest.java
src/test/java/uk/gov/pay/api/it/ResourcesFiltersITest.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentSearchResultBuilder.java
src/test/java/uk/gov/pay/api/utils/ChargeEventBuilder.java
src/test/java/uk/gov/pay/api/utils/ConnectorMockClient.java
src/test/java/uk/gov/pay/api/validation/PaymentSearchValidatorTest.java
swagger/swagger.json

Now we have the 'state' field everywhere, we can remove
the old legacy status from the publicapi.
Improve swagger here and there.

PP-541 Remove old status field.

---

.github/PULL_REQUEST_TEMPLATE.md

* Adding `How`, `What`, `Who` and `Related PRs`

Adding GitHub Pull request template

---

src/main/java/uk/gov/pay/api/model/CreatePaymentRequest.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java

* Formatting log messages to be more consistent.
* Making sure we don't log object references by including toString()
where they are needed.
Run the application and access the publicapi endpoints to observe the logs.

PP-582 Logging refactoring

---

src/main/java/uk/gov/pay/api/validation/PaymentSearchValidator.java
src/test/java/uk/gov/pay/api/validation/PaymentSearchValidatorTest.java

- When non numeric value for page and display_size was passed it was
handling the error however validation was not populating the proper
error message, this fixes it, with a test

PP-335 Added a check for non numeric page, display_size passed

---

src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/model/PaymentError.java
src/main/java/uk/gov/pay/api/resources/RequestDeniedResource.java
src/test/java/uk/gov/pay/api/it/RequestDeniedResourceITest.java

- When _Naxsi_ intercepts a request and any non whitelisted rule is being violated, then it makes a POST to the configured **DeniedUrl** parameter (path set in _Naxsi_ see _Related PRs_) to the application receiving the original request (_POST_ with the details of the original request).
- Created the specified resource and logging the _Naxsi_ header containing the causes of the violation.
- [] WebOps
https://github.com/alphagov/pay-infra/pull/350

PP-800 Request denied resource (Naxsi deniedUrl)

---

README.md

- Get Payment by ID
- Search All Payments
- Create a Payment
- Create a new Refund
- Get a Refund by ID
- Get all Refunds

PP-942 Update README.md for Public API for refunds section on

---

swagger/swagger.json

Updating the swagger.json file

PP-864 Include the email field on the response

---

README.md

- Public api now returns email in the response for search payments, get
payment by ID
- Payments search can be filtered on email address.
with @PauloPortugal

PP-864 search payments by email

---

README.md
src/main/java/uk/gov/pay/api/model/ChargeFromResponse.java
src/main/java/uk/gov/pay/api/model/Payment.java
src/main/java/uk/gov/pay/api/model/PaymentForSearchResult.java
src/main/java/uk/gov/pay/api/model/PaymentWithAllLinks.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/validation/PaymentRequestValidator.java
src/main/java/uk/gov/pay/api/validation/PaymentSearchValidator.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchITest.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceITest.java
src/test/java/uk/gov/pay/api/it/ResourcesFiltersITest.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentSearchResultBuilder.java
src/test/java/uk/gov/pay/api/utils/ConnectorMockClient.java
src/test/java/uk/gov/pay/api/validation/PaymentRequestValidatorTest.java
src/test/java/uk/gov/pay/api/validation/PaymentSearchValidatorTest.java
swagger/swagger.json

The used card brand, eg visa, master-card, etc is available for search as card_brand. The API returns the Label of the card brand, eg Visa, Mastercard, etc with charges status greater than 'CAPTURE SUBMITTED'

Pp 863 card types used available to partners

---

src/main/java/uk/gov/pay/api/app/RestClientFactory.java
src/main/java/uk/gov/pay/api/filter/LoggingFilter.java
src/main/java/uk/gov/pay/api/filter/RestClientLoggingFilter.java
src/test/java/uk/gov/pay/api/filter/LoggingFilterTest.java
src/test/java/uk/gov/pay/api/filter/RestClientLoggingFilterTest.java

This PR contains the scope of #PP-946 and some part of #PP-627. (from PP-627 Logging Request-ID in inbound/outbound requests are done, but still not available in all logs)
Timing inbound requests is done in LoggingFilter.java
Timing outbound requests is done in RestClientLoggingFilter.java
With @simad

PP-946 log elapsed time inboud/outbound requests 

---

pom.xml
swagger/swagger.json

Update the swagger config and generated JSON file to point to the production environment.

Swagger hostname update

---

src/main/java/uk/gov/pay/api/app/RestClientFactory.java
src/main/java/uk/gov/pay/api/filter/LoggingFilter.java
src/main/java/uk/gov/pay/api/filter/RestClientLoggingFilter.java

Quick fix for address review comments from previous PR.

PP-946 Address review comments

---

src/main/java/uk/gov/pay/api/model/PaymentError.java
src/test/java/uk/gov/pay/api/model/PaymentErrorTest.java

- Added name and code value to toString() method so we can get same the information our integrators receive (code value)

PP-1219 Fix logging of payment errors

---

README.md
src/main/java/uk/gov/pay/api/model/Address.java
src/main/java/uk/gov/pay/api/model/CardDetails.java
src/test/java/uk/gov/pay/api/it/PaymentRefundsResourceITest.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchITest.java
src/test/java/uk/gov/pay/api/it/PaymentsRefundsResourceAmountValidationITest.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceITest.java
src/test/java/uk/gov/pay/api/it/ResourcesFiltersITest.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentSearchResultBuilder.java
swagger/swagger.json

- County is not a field that we capture/persist. so removing it.
- Updating gelato documentation.

PP-1282 removing county field and updating api documentation

---

pom.xml
src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/app/config/PublicApiConfig.java
src/main/resources/config/config.yaml
src/test/resources/config/test-config.yaml

- We added two environment variables for host and port for
metrics.
- If the variables are not passed, default values are going to
get picked up
with @imranbohoran

PP-1386 Add dropwizard metrics

---

pom.xml
src/main/java/uk/gov/pay/api/resources/PaymentRefundsResource.java
swagger/swagger.json

- Fix documentation, where message is "Accepted" when creating refunds the correct response code is 202 (not 201).

PP-1452 Update documentation

---

pom.xml

Upgrade more dependencies on the basis of mvn versions:display-dependency-updates

Upgrade more dependencies

---

LICENSE

The statement for copyright was incorrect
This has been corrected

Correcting copyright statement

---

docker-startup.sh

This will allow java heap size to be controlled

PP-2019 allow JAVA_OPTS to be specified

---

pom.xml

PP-3178 PP-3179

---

src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/auth/AccountAuthenticator.java

Due to a bug in jersey client using a custom SSL context, the client cannot be called by many threads the first time it is called. In order to fix this problem we're are temporarily adding a dummy request on service startup to load the SSL context in the jersey client.

PP-3129 Add hack to solve issue when running end to end tests in parallel

---

pom.xml
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/test/java/uk/gov/pay/api/it/DirectDebitPaymentTest.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceITest.java
src/test/java/uk/gov/pay/api/pact/PactProviderRule.java
src/test/java/uk/gov/pay/api/pact/Pacts.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorDDMockClient.java
src/test/resources/pacts/publicapi-direct-debit-connector.json
src/test/resources/pacts/publicapi-publicauth.json

A working pact consumer java integration test. It was agreed with @alexbishop1 and @mrlumbu we should make the direct debit payment test use pact. See commit messages for more detail.

Pp 3733 pact consumer test

---

src/main/java/uk/gov/pay/api/model/Address.java
src/main/java/uk/gov/pay/api/model/CardDetails.java
src/main/java/uk/gov/pay/api/model/CardPayment.java
src/main/java/uk/gov/pay/api/model/DirectDebitPayment.java
src/main/java/uk/gov/pay/api/model/PaymentError.java
src/main/java/uk/gov/pay/api/model/PaymentEvent.java
src/main/java/uk/gov/pay/api/model/PaymentEvents.java
src/main/java/uk/gov/pay/api/model/PaymentState.java
src/main/java/uk/gov/pay/api/model/RefundSummary.java
src/main/java/uk/gov/pay/api/model/SettlementSummary.java
src/main/java/uk/gov/pay/api/model/links/Link.java
src/main/java/uk/gov/pay/api/model/links/PaymentEventLink.java
src/main/java/uk/gov/pay/api/model/links/PaymentLinks.java
src/main/java/uk/gov/pay/api/model/links/PaymentLinksForEvents.java
src/main/java/uk/gov/pay/api/model/links/PaymentLinksForSearch.java
src/main/java/uk/gov/pay/api/model/links/PaymentSearchNavigationLinks.java
src/main/java/uk/gov/pay/api/model/links/PostLink.java
swagger/swagger.json

- When we have space in the name we receive `$ref values must be RFC3986-compliant percent-encoded URIs` error
with @georgeracu

PP-3676 Fixed attribute `value` Swagger error

---

Jenkinsfile
pom.xml

bau: Tag with branch name on publishing of pact to the pact broker

---

Jenkinsfile

PP-3842: Tag consumer pact on deploy to master

---

src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/service/ConnectorUriGenerator.java
src/main/java/uk/gov/pay/api/service/PaymentSearchService.java
src/main/java/uk/gov/pay/api/service/PaymentUriGenerator.java
src/test/java/uk/gov/pay/api/service/PaymentSearchServiceTest.java

- move search logic from resource to service

PP-3679 Refactor to use PaymentSearchService in PaymentsResource

---

pom.xml

latest dropwizard 1.2.x series

Upgrade to dropwizard 1.2.5

---

Jenkinsfile

gitBranchName is currently not returning 'master' on master branch builds. This
is currently blocking progress so doing this quick fix now.
@oswaldquek

bau: Quick fix for failing gitBranchName method

---

README.md
docs/api_specification.md
src/main/java/uk/gov/pay/api/exception/mapper/CreateAgreementExceptionMapper.java
src/main/java/uk/gov/pay/api/model/PaymentConnectorResponseLink.java
src/main/java/uk/gov/pay/api/model/directdebit/agreement/CreateAgreementRequest.java
src/main/java/uk/gov/pay/api/model/directdebit/agreement/CreateAgreementResponse.java
src/main/java/uk/gov/pay/api/model/directdebit/agreement/GetAgreementResponse.java
src/main/java/uk/gov/pay/api/model/directdebit/agreement/MandateConnectorRequest.java
src/main/java/uk/gov/pay/api/model/directdebit/agreement/MandateConnectorResponse.java
src/main/java/uk/gov/pay/api/service/AgreementService.java
src/test/java/uk/gov/pay/api/service/AgreementServiceTest.java
src/test/resources/pacts/publicapi-direct-debit-connector-create-agreement-with-reference.json
src/test/resources/pacts/publicapi-direct-debit-connector-create-agreement-without-reference.json
swagger/swagger.json

This PR adds optional agreement `reference` property for the `/v1/agreements` endpoint request.
with @georgeracu

PP-3676 Add agreement reference

---

src/main/java/uk/gov/pay/api/model/directdebit/agreement/CreateAgreementRequest.java
src/main/java/uk/gov/pay/api/model/directdebit/agreement/CreateAgreementResponse.java
src/main/java/uk/gov/pay/api/model/directdebit/agreement/GetAgreementResponse.java
src/main/java/uk/gov/pay/api/model/directdebit/agreement/MandateConnectorResponse.java
src/test/java/uk/gov/pay/api/it/directdebit/AgreementsResourceITest.java
src/test/java/uk/gov/pay/api/service/AgreementServiceTest.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorDDMockClient.java
src/test/resources/pacts/publicapi-direct-debit-connector-create-agreement-with-reference.json
src/test/resources/pacts/publicapi-direct-debit-connector-create-agreement-without-reference.json
src/test/resources/pacts/publicapi-direct-debit-connector-get-agreement.json
swagger/swagger.json

- Added `mandate_reference` from connector as `provider_id` to the services
that call Public API
- Added `service_reference` from connector as `reference` to the services
that call Public API
- Updated Swagger file
with @danailminchev

PP-3922 Added provider id and reference

---

src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/service/PaymentSearchService.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchITest.java
src/test/java/uk/gov/pay/api/service/PaymentSearchServiceTest.java
src/test/resources/pacts/publicapi-direct-debit-connector-search-by-mandate-three-results.json
swagger/swagger.json

- replace search parameter `agreement` with `agreement_id`
- update tests

PP-3679 Refactor to use agreement_id

---

src/main/java/uk/gov/pay/api/model/search/IPaymentSearchPagination.java
src/main/java/uk/gov/pay/api/model/search/PaymentSearchFactory.java
src/main/java/uk/gov/pay/api/model/search/SearchPaymentsBase.java
src/main/java/uk/gov/pay/api/model/search/card/PaymentForSearchResult.java
src/main/java/uk/gov/pay/api/model/search/card/PaymentSearchResponse.java
src/main/java/uk/gov/pay/api/model/search/card/PaymentSearchResults.java
src/main/java/uk/gov/pay/api/model/search/card/SearchCardPayments.java
src/main/java/uk/gov/pay/api/model/search/directdebit/DDPaymentState.java
src/main/java/uk/gov/pay/api/model/search/directdebit/DDSearchResponse.java
src/main/java/uk/gov/pay/api/model/search/directdebit/DDTransactionForSearch.java
src/main/java/uk/gov/pay/api/model/search/directdebit/DDTransactionFromResponse.java
src/main/java/uk/gov/pay/api/model/search/directdebit/SearchDirectDebitPayments.java
src/main/java/uk/gov/pay/api/model/search/links/DDTransactionLinksForSearch.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/service/PaymentSearchService.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchITest.java

- refactor PaymentSearchService to use a factory pattern

PP-3679 Refactor PaymentSearchService

---

src/main/java/uk/gov/pay/api/model/search/SearchPaymentsBase.java
src/main/java/uk/gov/pay/api/model/search/directdebit/DDTransactionForSearch.java
src/main/java/uk/gov/pay/api/model/search/directdebit/DDTransactionFromResponse.java
src/test/java/uk/gov/pay/api/service/PaymentSearchServiceTest.java
src/test/resources/pacts/publicapi-direct-debit-connector-search-by-mandate-three-results.json

- add agreement id to DD search results
- add agreement id to pact test
- update relevant test

PP-3929 add agreement id to dd search results

---

src/test/java/uk/gov/pay/api/service/CreatePaymentServiceTest.java

It is wrong, and causing problems elsewhere. I will fix it and put it back, promise.

BAU mandate collect pact specified connector as provider

---

Jenkinsfile

BAU Run connector provider tests as part of build

---

docs/api_specification.md

- add agreement_id to search results

PP-3929 Update api docs

---

src/main/java/uk/gov/pay/api/exception/mapper/CreateAgreementExceptionMapper.java
src/main/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapper.java
src/main/java/uk/gov/pay/api/exception/mapper/CreateRefundExceptionMapper.java
src/main/java/uk/gov/pay/api/model/PaymentError.java
src/main/java/uk/gov/pay/api/model/directdebit/agreement/AgreementError.java

- These errors will be displayed when either trying to collect from a one off
mandate, or trying to create a one off mandate in the create agreeemnt endpoint

PP-3835 Show meaningful errors for create and collect agreements

---

docs/api_specification.md

Fix documentation
- Updated `state` search parameter

BAU - Update documentation for `state` search param

---

docs/api_specification.md
src/main/java/uk/gov/pay/api/service/PaymentSearchService.java
src/main/java/uk/gov/pay/api/validation/PaymentSearchValidator.java
src/test/java/uk/gov/pay/api/validation/PaymentSearchValidatorTest.java

- refactor PaymentSearchValidator to check separately for CardPayment and DirectDebit states
- update/add relevant tests
- update documentation

PP-3646 Address review comment (states)

---

src/main/java/uk/gov/pay/api/resources/DirectDebitEventsResource.java
src/main/java/uk/gov/pay/api/service/ConnectorUriGenerator.java
src/test/java/uk/gov/pay/api/resources/DirectDebitEventsResourceTest.java
src/test/java/uk/gov/pay/api/service/ConnectorUriGeneratorTest.java

- After refactoring not passing in search dates would cause a null pointer exception.
- This has been fixed and tests added to prevent future occurrence.

PP-3680 Fixed event search dates to permit null values.

---

src/main/java/uk/gov/pay/api/model/links/directdebit/DirectDebitEventsResponse.java
src/test/java/uk/gov/pay/api/it/GetDirectDebitEventsTest.java

- Fixed error when converting links provided by DDConnector to use
'agreement' and 'payment' as per publicapi convention.
- Corrected associated tests.

PP-3680 Fix bug in pagination links.

---

src/main/java/uk/gov/pay/api/json/RequestJsonParser.java
src/main/java/uk/gov/pay/api/model/CreatePaymentRequest.java
src/test/java/uk/gov/pay/api/resources/PaymentsResourceCreatePaymentTest.java
src/test/java/uk/gov/pay/api/service/CreatePaymentServiceTest.java
src/test/java/uk/gov/pay/api/validation/PaymentRequestValidatorTest.java

PP-4095 Introduce builder pattern for CreatePaymentRequest

---

src/main/java/uk/gov/pay/api/json/RequestJsonParser.java
src/main/java/uk/gov/pay/api/model/CreatePaymentRequest.java
src/main/java/uk/gov/pay/api/model/ValidCreatePaymentRequest.java
src/test/java/uk/gov/pay/api/json/CreatePaymentRequestDeserializerTest.java
src/test/java/uk/gov/pay/api/json/RequestJsonParserTest.java

- Added `delayedCapture` property to create payment request classes
- Modified `RequestJsonParser` and related tests
- Added missing `@Test` annotations and fixed the related tests
with @SandorArpa

PP-4106 Add delayedCapture field to create payment request

---

src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/service/GetPaymentService.java
src/test/java/uk/gov/pay/api/resources/PaymentsResourceCreatePaymentTest.java
src/test/java/uk/gov/pay/api/service/GetPaymentServiceTest.java
src/test/resources/pacts/publicapi-connector-get-payment-with-delayed-capture-true.json

Add `get payment with delayed capture true` pact test.
- Refactor PaymentsResource and add GetPaymentService
- Add Pact tests
- Create a json file for 'get a payment with delayed capture true'
with @DanailMinchev

PP-4106 add get payment with delayed capture pact integration

---

src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/exception/CaptureChargeException.java
src/main/java/uk/gov/pay/api/exception/mapper/CaptureChargeExceptionMapper.java
src/main/java/uk/gov/pay/api/model/PaymentError.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/service/CapturePaymentService.java
src/main/java/uk/gov/pay/api/service/ConnectorUriGenerator.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceCaptureITest.java
src/test/java/uk/gov/pay/api/resources/PaymentsResourceCreatePaymentTest.java
src/test/java/uk/gov/pay/api/service/CapturePaymentServiceTest.java
src/test/java/uk/gov/pay/api/service/ConnectorUriGeneratorTest.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java
src/test/resources/pacts/publicapi-connector-capture-payment-with-delayed-capture-true-and-awaiting-capture-request-status.json
swagger/swagger.json

This PR adds a new `POST /v1/payments/{paymentId}/capture` endpoint.
See commits for more information.
with @SandorArpa

PP-4110 Add a new capture endpoint

---

docs/api_specification.md
src/main/java/uk/gov/pay/api/model/CardDetails.java
src/test/java/uk/gov/pay/api/it/CreatePaymentITest.java
src/test/java/uk/gov/pay/api/it/GetPaymentITest.java
src/test/java/uk/gov/pay/api/it/PaymentRefundsResourceITest.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchITest.java
src/test/java/uk/gov/pay/api/it/ResourcesFilterITestBase.java
src/test/java/uk/gov/pay/api/it/ResourcesFilterLocalRateLimiterITest.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentSearchResultBuilder.java
src/test/java/uk/gov/pay/api/it/validation/PaymentsRefundsResourceAmountValidationITest.java
src/test/java/uk/gov/pay/api/model/PaymentTest.java
src/test/java/uk/gov/pay/api/resources/PaymentsResourceCreatePaymentTest.java
swagger/swagger.json

We are about to add support for storing the first 6 digits of a card number in connector. This PR makes PublicApi return its value if present, or `null` if not.

PP-4144 Return last 4 digits and first 6 digits of card number in get payment

---

docs/api_specification.md

PP-4141 Update README to include first, last digits and cardholder name filters

---

src/main/java/uk/gov/pay/api/model/CardPayment.java
src/main/java/uk/gov/pay/api/model/Payment.java
src/test/java/uk/gov/pay/api/service/CreatePaymentServiceTest.java
src/test/java/uk/gov/pay/api/service/GetPaymentServiceTest.java
swagger/swagger.json

- refactor CardPayment's and Payment's getters to return Optional where appropriate. This is to avoid using null.

PP-4128 Make CardPayment use Optional

---

README.md
docs/api_specification.md
src/main/java/uk/gov/pay/api/model/search/card/RefundForSearchRefundsResult.java
swagger/swagger.json

Adding information about the new refunds endpoint to the api specification and readme.

PP-4113 Update api specification and readme to add refunds endpoint docs

---

docs/api_specification.md

Correct url links for refunds in api specification

PP-4113 Correct refunds links in docs

---

src/main/java/uk/gov/pay/api/model/search/card/RefundForSearchRefundsResult.java
src/main/java/uk/gov/pay/api/model/search/card/RefundForSearchResult.java
src/main/java/uk/gov/pay/api/model/search/card/RefundResult.java
src/main/java/uk/gov/pay/api/model/search/card/SearchRefundsResults.java
src/main/java/uk/gov/pay/api/resources/PaymentRefundsResource.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
swagger/swagger.json

Part 2 of fixing swagger file..
Corrected swagger for following refund API calls
- GET /v1/refunds
- GET /v1/payments/{paymentId}/refunds
- POST /v1/payments/{paymentId}/refunds
- GET /v1/payments/{paymentId}/refunds/{refundId}

PP-4610 Fix swagger - Refunds API docs

---

pom.xml
src/main/java/uk/gov/pay/api/model/CreatePaymentRefundRequest.java
src/main/java/uk/gov/pay/api/model/ValidCreatePaymentRequest.java
src/main/java/uk/gov/pay/api/model/search/card/PaymentForSearchResult.java
src/main/java/uk/gov/pay/api/model/search/card/RefundForSearchRefundsResult.java
src/main/java/uk/gov/pay/api/model/search/card/RefundForSearchResult.java
src/main/java/uk/gov/pay/api/model/search/card/SearchRefundsResults.java
src/main/java/uk/gov/pay/api/resources/PaymentRefundsResource.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/resources/SearchRefundsResource.java
swagger/swagger.json

- Fixes Authorization in code samples
curl  `-H 'Authorization: API_KEY'` instead of `curl -H 'Authorisation: API_KEY'`
- Renamed few model names

PP-4610 Swagger - fix authorization

---

src/main/java/uk/gov/pay/api/exception/mapper/CreateAgreementExceptionMapper.java
src/main/java/uk/gov/pay/api/exception/mapper/RefundsValidationExceptionMapper.java
src/main/java/uk/gov/pay/api/filter/RateLimiterFilter.java
src/main/java/uk/gov/pay/api/filter/RestClientLoggingFilter.java
src/main/java/uk/gov/pay/api/healthcheck/Ping.java
src/main/java/uk/gov/pay/api/model/PaymentConnectorResponseLink.java
src/main/java/uk/gov/pay/api/model/SettlementSummary.java
src/main/java/uk/gov/pay/api/resources/HealthCheckResource.java
src/main/java/uk/gov/pay/api/service/CancelPaymentService.java
src/main/java/uk/gov/pay/api/service/GetPaymentService.java
src/test/java/uk/gov/pay/api/app/RestClientFactoryTest.java
src/test/java/uk/gov/pay/api/filter/RestClientLoggingFilterTest.java
src/test/java/uk/gov/pay/api/filter/ratelimit/LocalRateLimiterTest.java
src/test/java/uk/gov/pay/api/it/HealthCheckResourceITest.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchITest.java
src/test/java/uk/gov/pay/api/it/fixtures/PaginatedPaymentSearchResultFixture.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentSearchResultBuilder.java
src/test/java/uk/gov/pay/api/it/rule/RedisContainer.java
src/test/java/uk/gov/pay/api/it/rule/RedisDockerRule.java
src/test/java/uk/gov/pay/api/resources/PaymentsResourceCreatePaymentTest.java
src/test/java/uk/gov/pay/api/service/CardPaymentSearchServiceTest.java
src/test/java/uk/gov/pay/api/service/DirectDebitPaymentSearchServiceTest.java
src/test/java/uk/gov/pay/api/utils/JsonStringBuilderTest.java

Address some of IntelliJ's linter's concerns

Intellij fixups

---

src/test/java/uk/gov/pay/api/filter/RestClientLoggingFilterTest.java
src/test/java/uk/gov/pay/api/json/CreatePaymentRefundRequestDeserializerTest.java
src/test/java/uk/gov/pay/api/resources/HealthCheckResourceTest.java

MockitoJUnitRunner has moved from org.mockito.runners to org.mockito.junit

Use non-deprecated MockitoJUnitRunner

---

Dockerfile
Jenkinsfile
docker-startup.sh
pom.xml

This upgrades PublicApi to Java 11. Note that `JAVA_HOME` was previously set to JDK11 in the `Jenkins` file so no need to do it here.

PP-5053 Upgrade to Java 11

---

pom.xml
src/main/java/uk/gov/pay/api/json/RequestJsonParser.java
src/main/java/uk/gov/pay/api/model/CreatePaymentRequest.java
src/main/java/uk/gov/pay/api/model/PaymentError.java
src/main/java/uk/gov/pay/api/model/ValidCreatePaymentRequest.java
src/test/java/uk/gov/pay/api/it/CreatePaymentITest.java
src/test/java/uk/gov/pay/api/it/validation/PaymentResourceMetadataITest.java
src/test/java/uk/gov/pay/api/it/validation/PaymentResourceMetadataValidationFailuresITest.java

Validations happen in RequestJsonParser, which has become rather messy; but
this will be refactored in a separate PR.

PP-4886: Tests for invalid metadata

---

src/main/java/uk/gov/pay/api/json/RequestJsonParser.java
src/main/java/uk/gov/pay/api/model/CreatePaymentRequest.java
src/main/java/uk/gov/pay/api/model/ValidCreatePaymentRequest.java
swagger/swagger.json

Extract validations into its own method. This makes things clearer.

PP-4886: Refactor RequestJsonParser

---

src/test/java/uk/gov/pay/api/service/GetPaymentServiceTest.java
src/test/resources/pacts/publicapi-connector-get-payment-with-fee-and-net-amount.json

- Pact consumer test for new fields `fee` and `net_amount` available from connector

PP-5080 Pact test for `fee` and `net_amount`

---

src/test/java/uk/gov/pay/api/service/CreatePaymentServiceTest.java
src/test/resources/pacts/publicapi-connector-create-payment-with-prefilled-cardholder-details.json

- add pact test
- add CreatePaymentServiceTest test using the pact json file
API documentation in next PR

PP-5091 Add pact test for create payment with prefilled cardholder details

---

docs/api_specification.md

Add api documentation for create payment request with prefilled cardholder details
No test required
This is the documentation

PP-5091 Add api documentation for prefilled cardholder details

---

Jenkinsfile

As agreed with team, will make builds faster and reduce strain on CI

PP-5191 Don't run e2e on PRs by default

---

src/test/java/uk/gov/pay/api/it/CreatePaymentITest.java

Test for where metadata supplied when creating a payment is
```
"metadata":{}
```

PP-4886: Test for empty metadata

---

src/main/java/uk/gov/pay/api/app/config/PublicApiModule.java
src/main/java/uk/gov/pay/api/exception/mapper/ViolationExceptionMapper.java
src/main/java/uk/gov/pay/api/model/CreatePaymentRequest.java
src/main/java/uk/gov/pay/api/validation/PaymentRefundRequestValidator.java
src/main/java/uk/gov/pay/api/validation/PaymentRequestValidator.java
src/main/java/uk/gov/pay/api/validation/PaymentSearchValidator.java
src/test/java/uk/gov/pay/api/it/CreatePaymentITest.java
src/test/java/uk/gov/pay/api/it/PaymentResourceITestBase.java
src/test/java/uk/gov/pay/api/it/validation/PaymentResourceMetadataValidationFailuresITest.java
src/test/java/uk/gov/pay/api/it/validation/PaymentsResourceEmailValidationITest.java
src/test/java/uk/gov/pay/api/validation/PaymentRequestValidatorTest.java

Use `@Valid` for email validation.

Pp 5100 validations

---

src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/json/RequestJsonParser.java
src/main/java/uk/gov/pay/api/model/CreatePaymentRequest.java
src/main/java/uk/gov/pay/api/validation/InjectingConfiguredValidator.java
src/main/java/uk/gov/pay/api/validation/InjectingConstraintValidatorFactory.java
src/main/java/uk/gov/pay/api/validation/InjectingValidationFeature.java
src/main/java/uk/gov/pay/api/validation/PaymentRequestValidator.java
src/main/java/uk/gov/pay/api/validation/ReturnUrlValidator.java
src/main/java/uk/gov/pay/api/validation/URLValidator.java
src/main/java/uk/gov/pay/api/validation/ValidReturnUrl.java
src/main/java/uk/gov/pay/api/validation/ValidatorFactory.java
src/test/java/uk/gov/pay/api/it/validation/CreatePaymentReturnUrlValidationITest.java
src/test/java/uk/gov/pay/api/it/validation/CreatePaymentWithHttpReturnUrlTest.java
src/test/java/uk/gov/pay/api/it/validation/PaymentsResourceAgreementIdValidationITest.java
src/test/java/uk/gov/pay/api/it/validation/PaymentsResourceLanguageValidationITest.java
src/test/java/uk/gov/pay/api/it/validation/PaymentsResourceReturnUrlValidationITest.java
src/test/java/uk/gov/pay/api/validation/PaymentRequestValidatorTest.java
src/test/resources/config/test-config.yaml
swagger/swagger.json

Change validation of the returnUrl when creating a payment to use `@Valid`.

Pp 5100 return url

---

src/test/java/uk/gov/pay/api/validation/PaymentRequestValidatorTest.java

These are now validated using the javax validation framework and have now moved
to integration tests.

PP-5100: Delete deprecated tests

---

src/test/java/uk/gov/pay/api/it/GetDirectDebitEventsIT.java
src/test/java/uk/gov/pay/api/it/directdebit/pact/DirectDebitPaymentIT.java

Re-enable Direct Debit Pact tests that were disabled in commit 1de88e42bf5a76086a58e224cc2b6332e5daeac5

PP-5248 Re-enable Direct Debit Pact tests

---

src/main/java/uk/gov/pay/api/model/directdebit/agreement/CreateMandateResponse.java
src/main/java/uk/gov/pay/api/model/directdebit/agreement/GetAgreementResponse.java
src/main/java/uk/gov/pay/api/model/links/directdebit/MandateLinks.java
src/main/java/uk/gov/pay/api/service/AgreementService.java
src/main/java/uk/gov/pay/api/service/DirectDebitEventService.java
src/main/java/uk/gov/pay/api/service/PublicApiUriGenerator.java
src/test/java/uk/gov/pay/api/it/directdebit/MandatesResourceIT.java

Add mandate payment link in the create mandate response.

PP-5297: Return mandate payments link

---

src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/app/config/PublicApiConfig.java
src/main/java/uk/gov/pay/api/common/SearchConstants.java
src/main/java/uk/gov/pay/api/exception/SearchTransactionsException.java
src/main/java/uk/gov/pay/api/ledger/model/TransactionSearchParams.java
src/main/java/uk/gov/pay/api/ledger/model/TransactionSearchResults.java
src/main/java/uk/gov/pay/api/ledger/resource/TransactionsResource.java
src/main/java/uk/gov/pay/api/ledger/service/LedgerUriGenerator.java
src/main/java/uk/gov/pay/api/ledger/service/TransactionSearchService.java
src/main/resources/config/config.yaml
src/test/java/uk/gov/pay/api/it/fixtures/PaginatedTransactionSearchResultFixture.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentResultBuilder.java
src/test/java/uk/gov/pay/api/it/ledger/TransactionsResourceIT.java
src/test/java/uk/gov/pay/api/ledger/service/TransactionSearchServiceTest.java
src/test/java/uk/gov/pay/api/utils/mocks/LedgerMockClient.java
src/test/resources/config/test-config.yaml

- add endpoint to search transactions in Ledger
- add TransactionSearchService to handle endpoint's query
- add integration test
This is a quick job for a temporary endpoint. We tried to re-use as much of Search Payments components as physically possible.
with @kbottla

PP-5257 add TransactionsResource.searchTransactions endpoint

---

src/main/java/uk/gov/pay/api/model/links/directdebit/MandateLinks.java
src/main/java/uk/gov/pay/api/service/AgreementService.java
src/main/java/uk/gov/pay/api/service/PublicApiUriGenerator.java
src/test/java/uk/gov/pay/api/it/directdebit/MandatesResourceIT.java

Also did some refactoring on the MandateLinks class to use the builder pattern.

Pp 5297 event links on mandate creation

---

Jenkinsfile
src/test/java/uk/gov/pay/api/ledger/service/TransactionSearchServiceTest.java
src/test/resources/pacts/publicapi-ledger-search-transaction.json

- Adds consumer tests for searching transactions in ledger
- Enables checking pacts (runPactProviderTests) with ledger
- CI should pass

PP-5252 Pact consumer test - for ledger transaction search

---

src/main/java/uk/gov/pay/api/model/directdebit/agreement/MandateStatus.java

These shouldn't have been deleted as they are returned from dd-connector.

PP-5297: Reinstate statuses

---

src/main/java/uk/gov/pay/api/model/directdebit/agreement/DirectDebitPayment.java
src/main/java/uk/gov/pay/api/service/directdebit/CreateDirectDebitPaymentsService.java
src/test/java/uk/gov/pay/api/resources/directdebit/DirectDebitPaymentsResourceIT.java

Return mandate_id and provider_id in response.

PP-5298 Return all fields in create dd payment response

---

src/main/java/uk/gov/pay/api/resources/MandatesResource.java
src/main/java/uk/gov/pay/api/service/PublicApiUriGenerator.java
src/test/java/uk/gov/pay/api/it/GetDirectDebitEventsIT.java
src/test/java/uk/gov/pay/api/it/directdebit/CreateMandateIT.java
src/test/java/uk/gov/pay/api/utils/Urls.java

PP-5299: Update self link when creating mandate

---

src/main/java/uk/gov/pay/api/model/directdebit/mandates/GetMandateResponse.java
src/test/java/uk/gov/pay/api/it/directdebit/GetMandateIT.java
src/test/java/uk/gov/pay/api/service/MandatesServiceTest.java
src/test/resources/pacts/publicapi-direct-debit-connector-get-mandate.json

There are some TODOs in this PR which I intend to address in the next PR.

PP-5299: Return bank statement reference when getting a mandate

---

src/test/java/uk/gov/pay/api/it/directdebit/GetMandateIT.java
src/test/java/uk/gov/pay/api/service/MandatesServiceTest.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorDDMockClient.java
src/test/java/uk/gov/pay/api/utils/mocks/DDConnectorResponseToGetMandateParams.java
src/test/resources/pacts/publicapi-direct-debit-connector-create-mandate.json

Also added a builder for ConnectorDDMockClient.respondOk_whenGetAgreementRequest.

PP-5299: Assert mandate ref is null on mandate creation

---

src/main/java/uk/gov/pay/api/model/directdebit/DirectDebitConnectorPaymentResponse.java
src/main/java/uk/gov/pay/api/model/directdebit/mandates/DirectDebitPayment.java
src/main/java/uk/gov/pay/api/resources/directdebit/DirectDebitPaymentsResource.java
src/main/java/uk/gov/pay/api/service/GetDirectDebitPaymentService.java
src/main/java/uk/gov/pay/api/service/PublicApiUriGenerator.java
src/main/java/uk/gov/pay/api/service/directdebit/CreateDirectDebitPaymentsService.java
src/test/java/uk/gov/pay/api/resources/PaymentsResourceCreatePaymentTest.java
src/test/java/uk/gov/pay/api/resources/directdebit/DirectDebitPaymentsResourceIT.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorDDMockClient.java
src/test/resources/pacts/publicapi-direct-debit-connector-collect-payment.json

- Migrates logic for Get Payments endpoint for Direct Debit payments
- Changes return type to match DD Payments information

PP-5300 Introduce Direct Debit Specific GET Payments Endpoint

---

src/main/java/uk/gov/pay/api/model/directdebit/mandates/GetMandateResponse.java
src/main/java/uk/gov/pay/api/model/directdebit/mandates/MandateConnectorResponse.java
src/test/java/uk/gov/pay/api/it/directdebit/CreateMandateIT.java
src/test/java/uk/gov/pay/api/it/directdebit/GetMandateIT.java
src/test/java/uk/gov/pay/api/service/MandatesServiceTest.java
src/test/java/uk/gov/pay/api/utils/mocks/BaseConnectorMockClient.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorDDMockClient.java
src/test/java/uk/gov/pay/api/utils/mocks/CreateMandateRequestParams.java
src/test/java/uk/gov/pay/api/utils/mocks/DDConnectorResponseToGetMandateParams.java
src/test/resources/pacts/publicapi-direct-debit-connector-get-mandate.json

Return provider id when getting a confirmed mandate from dd-connector.

PP-5299: Return provider id

---

src/main/java/uk/gov/pay/api/model/directdebit/mandates/MandateResponse.java
src/main/java/uk/gov/pay/api/model/directdebit/mandates/MandateState.java
src/main/java/uk/gov/pay/api/model/directdebit/mandates/MandateStatus.java
src/test/java/uk/gov/pay/api/it/directdebit/CreateMandateIT.java
src/test/java/uk/gov/pay/api/it/directdebit/GetMandateIT.java
src/test/java/uk/gov/pay/api/service/MandatesServiceTest.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorDDMockClient.java
src/test/java/uk/gov/pay/api/utils/mocks/DDConnectorResponseToGetMandateParams.java
src/test/resources/pacts/publicapi-direct-debit-connector-get-mandate.json

PP-5299: Add status details and created date in pact

---

src/main/java/uk/gov/pay/api/service/GetDirectDebitPaymentService.java
src/test/java/uk/gov/pay/api/service/GetDirectDebitPaymentServiceContractTest.java
src/test/resources/pacts/publicapi-direct-debit-connector-get-directdebit-payment.json

- Adds a pact test for the GET DirectDebit Payment endpoint

PP-5300 Get DirectDebit Payment Pact Test

---

src/main/java/uk/gov/pay/api/model/CardPayment.java
src/main/java/uk/gov/pay/api/model/DirectDebitPaymentState.java
src/main/java/uk/gov/pay/api/model/Payment.java
src/main/java/uk/gov/pay/api/model/directdebit/DirectDebitConnectorPaymentResponse.java
src/main/java/uk/gov/pay/api/model/directdebit/mandates/DirectDebitPayment.java
src/main/java/uk/gov/pay/api/resources/directdebit/DirectDebitPaymentsResource.java
src/main/java/uk/gov/pay/api/service/ConnectorUriGenerator.java
src/main/java/uk/gov/pay/api/service/directdebit/DirectDebitConnectorUriGenerator.java
src/test/java/uk/gov/pay/api/it/GetPaymentIT.java
src/test/java/uk/gov/pay/api/resources/directdebit/DirectDebitPaymentsResourceGetIT.java
src/test/java/uk/gov/pay/api/service/DirectDebitPaymentSearchServiceTest.java
src/test/java/uk/gov/pay/api/service/GetDirectDebitPaymentServiceContractTest.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorDDMockClient.java
src/test/resources/pacts/publicapi-direct-debit-connector-get-directdebit-payment.json
src/test/resources/pacts/publicapi-direct-debit-connector-search-by-mandate-three-results.json

Make DirectDebitPaymentState not extend PaymentState as it is its own thing.

PP-5301: Search payments pact test

---

src/main/java/uk/gov/pay/api/model/search/directdebit/DirectDebitSearchMandatesParams.java
src/main/java/uk/gov/pay/api/model/search/directdebit/MandateSearchConnectorResponse.java
src/main/java/uk/gov/pay/api/service/directdebit/DirectDebitMandateSearchService.java
src/test/java/uk/gov/pay/api/it/directdebit/MandateResourceSearchMandateIT.java
src/test/java/uk/gov/pay/api/model/search/directdebit/DirectDebitSearchMandatesParamsTest.java
src/test/java/uk/gov/pay/api/service/directdebit/DirectDebitMandateSearchServiceTest.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorDDMockClient.java

Add validation to mandate search mirroring validation applied in DDConnector.

Pp 5429 add validation to mandate search

---

src/main/java/uk/gov/pay/api/resources/MandatesResource.java
swagger/swagger.json

PP-5346: Correct response for mandate search

---

pom.xml
src/main/java/uk/gov/pay/api/model/search/directdebit/DirectDebitSearchPaymentsParams.java
src/main/java/uk/gov/pay/api/resources/directdebit/DirectDebitPaymentsResource.java
swagger/swagger.json

PP-5346: Swagger docs for mandate payments

---

src/main/java/uk/gov/pay/api/model/search/directdebit/DirectDebitSearchMandatesParams.java
src/main/java/uk/gov/pay/api/resources/MandatesResource.java
swagger/swagger.json

PP-5346: Add authorization and more descriptions

---

src/test/resources/pacts/publicapi-connector-create-payment-with-language-welsh.json
src/test/resources/pacts/publicapi-connector-create-payment-with-metadata.json

I discovered some pacts were being overriden due to non-unique descriptions.

bau: Make pact descriptions unique

---

src/main/java/uk/gov/pay/api/ledger/service/LedgerUriGenerator.java
src/main/java/uk/gov/pay/api/service/GetPaymentService.java
src/test/resources/pacts/publicapi-ledger-get-payment-with-corporate-surcharge.json
src/test/resources/pacts/publicapi-ledger-get-payment-with-delayed-capture-true.json
src/test/resources/pacts/publicapi-ledger-get-payment-with-fee-and-net-amount.json
src/test/resources/pacts/publicapi-ledger-get-payment-with-gateway-transaction-id.json
src/test/resources/pacts/publicapi-ledger-get-payment-with-metadata.json

* added account_id query parameter to ledger transaction endpoint
* updated pacts to reflect the change

PP-5419: add account_id to get transaction ledger endpoint

---

src/main/java/uk/gov/pay/api/model/Charge.java
src/main/java/uk/gov/pay/api/model/TransactionResponse.java
src/test/resources/pacts/publicapi-ledger-get-payment-with-corporate-surcharge.json
src/test/resources/pacts/publicapi-ledger-get-payment-with-delayed-capture-true.json
src/test/resources/pacts/publicapi-ledger-get-payment-with-fee-and-net-amount.json
src/test/resources/pacts/publicapi-ledger-get-payment-with-gateway-transaction-id.json
src/test/resources/pacts/publicapi-ledger-get-payment-with-metadata.json

* for ledger get one transaction endpoint
* in order to deprecate charge_id

BAU: replace charge_id with transaction_id 

---

src/main/java/uk/gov/pay/api/ledger/service/TransactionSearchService.java
src/main/java/uk/gov/pay/api/model/search/card/PaymentForSearchResult.java
src/main/java/uk/gov/pay/api/model/search/card/PaymentSearchResponse.java
src/main/java/uk/gov/pay/api/service/PaymentSearchService.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentResultBuilder.java
src/test/resources/pacts/publicapi-ledger-search-transaction.json

* for transaction search endpoint
* in order to deprecate charge_id in ledger

BAU: replace charge_id with transaction_id

---

src/main/java/uk/gov/pay/api/model/search/directdebit/DirectDebitSearchPaymentsParams.java
src/test/java/uk/gov/pay/api/resources/directdebit/DirectDebitPaymentsResourceGetIT.java
swagger/swagger.json

Update the allowed states to include the new external states for direct debit payments.

PP-5516 Fix state validation for search direct debit payments

---

src/main/java/uk/gov/pay/api/app/config/PublicApiConfig.java
src/main/resources/config/config.yaml
src/test/resources/config/test-config.yaml

It will be handled with header: https://github.com/alphagov/pay-publicapi/pull/625

PP-5418: remove the old ledger flag

---

src/main/java/uk/gov/pay/api/resources/PaymentRefundsResource.java
src/main/java/uk/gov/pay/api/service/ConnectorService.java
src/main/java/uk/gov/pay/api/service/ConnectorUriGenerator.java
src/main/java/uk/gov/pay/api/service/GetPaymentRefundsService.java
src/test/java/uk/gov/pay/api/service/GetPaymentServiceLedgerTest.java
src/test/java/uk/gov/pay/api/service/GetPaymentServiceTest.java

_Prep to use Ledger for PaymentRefunds_
- Refactored PaymentRefunds resource method to use `GetPaymentRefundsService` to get refunds from connector

PP-5421 Refactor PaymentRefunds resource method

---

src/main/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapper.java
src/main/java/uk/gov/pay/api/model/PaymentError.java
src/test/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapperTest.java

- Returns a helpful error when the MandateID is invalid

PP-5519 Helpful Error When MandateID Invalid

---

src/test/java/uk/gov/pay/api/service/GetPaymentRefundsServiceTest.java
src/test/resources/pacts/publicapi-connector-get-payment-refunds.json

- Adds pact tests for payment refunds from connector

PP-5421 Pact test for connector payment refunds

---

src/main/java/uk/gov/pay/api/model/search/PaginationDecorator.java
src/main/java/uk/gov/pay/api/model/search/card/SearchRefundsResponseFromConnector.java
src/main/java/uk/gov/pay/api/model/search/card/SearchRefundsResults.java
src/main/java/uk/gov/pay/api/resources/SearchRefundsResource.java
src/main/java/uk/gov/pay/api/service/ConnectorService.java
src/main/java/uk/gov/pay/api/service/SearchRefundsService.java
src/test/java/uk/gov/pay/api/service/SearchRefundsServiceTest.java

Prep to introduce ledger for refunds search
- Refactors SearchRefundsService to use ConnectorService to search for refunds
- Returns an object instead of generic `Response` fron SearchRefundsResource

PP-5499 Refactor SearchRefundsService

---

src/main/java/uk/gov/pay/api/model/search/card/SearchRefundsResults.java

- Adds missing @JsonProperty annotation for search refunds response '_links'

PP-5499 Fix search refunds endpoint

---

src/test/java/uk/gov/pay/api/service/GetPaymentRefundServiceTest.java
src/test/resources/pacts/publicapi-ledger-get-payment-refund.json

depends on https://github.com/alphagov/pay-ledger/pull/233

PP-5498: pact test for ledger get refund transaction

---

src/test/java/uk/gov/pay/api/it/SearchRefundsResourceIT.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentRefundSearchJsonFixture.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java

- Test for fix https://github.com/alphagov/pay-publicapi/pull/656

PP-5499 ITest for search refunds endpoint

---

src/main/java/uk/gov/pay/api/service/SearchRefundsService.java
src/test/java/uk/gov/pay/api/service/SearchRefundsServiceTest.java
src/test/resources/pacts/publicapi-ledger-search-refunds.json

* fix a bug when generating link uncovered by pact test

PP-5499: pact test for refunds search

---

src/main/java/uk/gov/pay/api/model/search/PaginationDecorator.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/resources/SearchPaymentsStrategy.java
src/main/java/uk/gov/pay/api/service/LedgerService.java
src/main/java/uk/gov/pay/api/service/PaymentSearchService.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchIT.java
src/test/java/uk/gov/pay/api/resources/SearchPaymentsStrategyTest.java
src/test/java/uk/gov/pay/api/resources/directdebit/DirectDebitPaymentsResourceGetIT.java
src/test/java/uk/gov/pay/api/service/CardPaymentSearchServiceTest.java
src/test/resources/pacts/publicapi-ledger-search-payments.json

* add strategy for search payments
* add unit test for the new strategy
* update resource to include a new header and use the strategy
* extend ledger service with a method to search for payments transactions
* extend PaymentSearchService to use the ledger search payments method
* pact test for ledger payments search

PP-5497 search payments strategy

---

src/main/java/uk/gov/pay/api/model/CreateCardPaymentRequest.java
src/main/java/uk/gov/pay/api/model/CreatePaymentResult.java
swagger/swagger.json

fix swagger descriptor for language and metadata, See https://govuk.zendesk.com/agent/tickets/3782041

BAU fix metadata and language swagger descriptors

---

src/main/java/uk/gov/pay/api/model/CreateCardPaymentRequest.java
swagger/swagger.json

bau: Make swagger doc on metadata clearer

---

src/main/java/uk/gov/pay/api/model/telephone/CreateTelephonePaymentRequest.java
src/main/java/uk/gov/pay/api/model/telephone/PaymentOutcome.java
src/main/java/uk/gov/pay/api/validation/CardExpiryValidator.java
src/main/java/uk/gov/pay/api/validation/CardFirstSixDigitsValidator.java
src/main/java/uk/gov/pay/api/validation/CardLastFourDigitsValidator.java
src/main/java/uk/gov/pay/api/validation/CardTypeValidator.java
src/main/java/uk/gov/pay/api/validation/PaymentOutcomeValidator.java
src/test/java/uk/gov/pay/api/it/telephone/BuiltInValidationIT.java
src/test/java/uk/gov/pay/api/it/telephone/CardExpiryValidationIT.java
src/test/java/uk/gov/pay/api/it/telephone/FirstSixCardDigitsValidationIT.java
src/test/java/uk/gov/pay/api/it/telephone/GetTelephonePaymentIT.java
src/test/java/uk/gov/pay/api/it/telephone/LastFourCardDigitsValidationIT.java
src/test/java/uk/gov/pay/api/it/telephone/PaymentOutcomeValidationIT.java
src/test/java/uk/gov/pay/api/it/telephone/PredefinedValidationIT.java
src/test/java/uk/gov/pay/api/it/telephone/TelephonePaymentResourceITBase.java
src/test/java/uk/gov/pay/api/validation/CardExpiryValidatorTest.java
src/test/java/uk/gov/pay/api/validation/CardFirstSixDigitsValidatorTest.java
src/test/java/uk/gov/pay/api/validation/CardLastFourDigitsValidatorTest.java
src/test/java/uk/gov/pay/api/validation/CardTypeValidatorTest.java
src/test/java/uk/gov/pay/api/validation/PaymentOutcomeValidatorTest.java

This PR moves the resource validation tests into Integration tests and adds separate unit tests for CardExpiry, CardType, PaymentOutcome and LastCardFourDigits and FirstCardSixDigits custom validators.

PP-5443 Refactors resource tests into integration tests and adds unit test for validators

---

src/main/resources/config/config.yaml

Want to see if requests are hitting the application like they are hitting
nginx. This will help us debug DVLA load testing issues.
Nginx format is
```
"'$host:$server_port $http_x_request_id $http_x_forwarded_for $remote_addr $remote_user [$time_local] \"$_request\" $status $body_bytes_sent $request_time $http_x_forwarded_proto \"$_http_referer\" \"$http_user_agent\"'"
```

bau: Add request logging

---

pom.xml
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
swagger/swagger.json

Update API docs for card payment search to indicate that reference is an exact match (but is case insensitive).

PP-5611 Update Swagger for card payment reference search

---

src/main/java/uk/gov/pay/api/model/telephone/CreateTelephonePaymentRequest.java
src/test/java/uk/gov/pay/api/it/telephone/CreateTelephonePaymentIT.java
src/test/java/uk/gov/pay/api/it/telephone/FirstSixCardDigitsValidationIT.java
src/test/java/uk/gov/pay/api/it/telephone/LastFourCardDigitsValidationIT.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java
src/test/java/uk/gov/pay/api/validation/CardFirstSixDigitsValidatorTest.java
src/test/java/uk/gov/pay/api/validation/CardLastFourDigitsValidatorTest.java
src/test/java/uk/gov/pay/api/validation/CardTypeValidatorTest.java

- make card_type, last_four_digits and first_six_digits optional for telephone payments
- update/remove relevant tests

PP-5654 make card related fields optional

---

src/main/java/uk/gov/pay/api/model/CardDetails.java
src/test/java/uk/gov/pay/api/it/CreatePaymentIT.java
src/test/java/uk/gov/pay/api/it/GetPaymentIT.java
src/test/java/uk/gov/pay/api/it/PaymentRefundsResourceIT.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchIT.java
src/test/java/uk/gov/pay/api/it/ResourcesFilterLocalRateLimiterIT.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentResultBuilder.java
src/test/java/uk/gov/pay/api/it/ledger/TransactionsResourceIT.java
src/test/java/uk/gov/pay/api/it/validation/PaymentsRefundsResourceAmountValidationIT.java
src/test/java/uk/gov/pay/api/resources/PaymentsResourceCreatePaymentTest.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java

- Adds the 'card_type' field to 'card_details' as a response to
publicapi get payment requests

PP-5652 Add Card Type As PublicAPI Response

---

src/test/java/uk/gov/pay/api/it/telephone/pact/CreateTelephonePaymentServiceTest.java
src/test/resources/pacts/publicapi-connector-create-telephone-payment-notification.json

- add a contract test with all fields covered for telephone payment notifications

PP-5446 add telephone payments contract test

---

src/main/java/uk/gov/pay/api/model/CardDetails.java
src/main/java/uk/gov/pay/api/model/CardPayment.java
src/main/java/uk/gov/pay/api/model/CreateCardPaymentRequest.java
src/main/java/uk/gov/pay/api/model/CreatePaymentRefundRequest.java
src/main/java/uk/gov/pay/api/model/RefundSummary.java
src/main/java/uk/gov/pay/api/model/SettlementSummary.java
src/main/java/uk/gov/pay/api/model/links/PaymentLinks.java
src/main/java/uk/gov/pay/api/model/links/PaymentLinksForSearch.java
src/main/java/uk/gov/pay/api/model/links/PostLink.java
src/main/java/uk/gov/pay/api/model/search/card/PaymentForSearchResult.java
src/main/java/uk/gov/pay/api/model/search/directdebit/DirectDebitSearchPaymentsParams.java
src/main/java/uk/gov/pay/api/model/search/directdebit/SearchMandateResponse.java
src/main/java/uk/gov/pay/api/resources/MandatesResource.java
src/main/java/uk/gov/pay/api/resources/PaymentRefundsResource.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/resources/SearchRefundsResource.java
src/main/resources/swagger-config.yaml

- Updated openapi specs to match current version of swagger

PP-5285 Fix specs for OpenAPI

---

src/test/resources/pacts/publicapi-connector-search-payment-by-cardholder-name.json

PP-5652: Add card_type in contract test

---

pom.xml
src/main/resources/swagger-config.yaml
swagger/swagger.json
swagger/swagger_v3_0_0.json

- Restore previous version of swagger, so service(s) can continue to use v2 of swagger. 
- We will be maintaining both versions for some period before completely switching to openapi v3.0. API Docs will continue to be based on v2 of swagger file

PP-5692 Restore swagger v2

---

src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/resources/config/config.yaml
src/test/resources/config/empty-elevated-accounts-test-config.yaml
src/test/resources/config/test-config.yaml

PP-5723: Configure publicapi to use json logging

---

src/main/java/uk/gov/pay/api/model/telephone/CreateTelephonePaymentRequest.java
src/main/java/uk/gov/pay/api/validation/CardTypeValidator.java
src/main/java/uk/gov/pay/api/validation/ValidCardType.java
src/test/java/uk/gov/pay/api/validation/CardTypeValidatorTest.java

- Telephone payments should also support JCB card type

PP-5743 Telephone payments - Additional card type

---

src/main/java/uk/gov/pay/api/validation/CardTypeValidator.java

- `Discover` card type added by mistake

PP-5743 Telephone payments - Remove discover card type

---

pom.xml
src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/resources/config/config.yaml

PP-5776: Configure server request logs to log in json format

---

src/test/java/uk/gov/pay/api/it/PaymentRefundsResourceIT.java
src/test/java/uk/gov/pay/api/utils/mocks/LedgerMockClient.java

Why?
Changes:
* refactor existing test
* add ledger equivalent tests for all the refund retrieval scenarios
In case of comments I prefer to address them in follow up PRs, because I'll be working on multiple branches.

[PP-5869] add refunds resource integration tests for ledger

---

src/test/java/uk/gov/pay/api/it/GetPaymentIT.java

Why?
Remove a lot of duplicate code to make it easier to update with ledger tests
Changes:
* refactor setting up a charge to a method
* replace full set up with new method and add overrides/additional properites to tests

[PP-5869] refactor get payment integration test

---

src/test/java/uk/gov/pay/api/service/CardPaymentSearchServiceTest.java
src/test/java/uk/gov/pay/api/service/SearchRefundsServiceTest.java
src/test/resources/pacts/publicapi-ledger-search-payment-by-cardholder-name.json
src/test/resources/pacts/publicapi-ledger-search-payment-by-first-digits-card-number.json
src/test/resources/pacts/publicapi-ledger-search-payment-by-last-digits-card-number.json
src/test/resources/pacts/publicapi-ledger-search-payment-with-charge-in-success-state.json

- Update the tests we have for ledger to bring them to functionality
parity with those we have for connector.

PP-5868 Update Ledger Pacts For Connector Parity

---

src/test/java/uk/gov/pay/api/utils/mocks/TransactionFromLedgerFixture.java

Why?
For integration tests that will be added in separate PR.
In order to avoid big PRs this is created as separate change.

[PP-5869] add transaction ledger fixture for testing

---

src/test/java/uk/gov/pay/api/it/PaymentResourceSearchIT.java

Why?
Follow up to: https://github.com/alphagov/pay-publicapi/pull/777
Changes:
* add missing ledger integration test

[PP-5869] add missing search test for ledger

---

src/main/java/uk/gov/pay/api/app/PublicApi.java

Description:
- Refactors to uses Google Guice injector

PP-5893-Add-MDC-Logging-Filter

---

src/main/java/uk/gov/pay/api/model/RefundResponse.java
src/main/java/uk/gov/pay/api/resources/PaymentRefundsResource.java

Changes:
* replace the path variable building with hardcoded values - more readable than the previous version
* remove queryParam building - the list is always empty

BAU: clean up PaymentRefundsResource

---

src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/service/PublicApiUriGenerator.java
src/main/java/uk/gov/pay/api/service/SearchRefundsService.java
src/main/java/uk/gov/pay/api/service/directdebit/DirectDebitConnectorUriGenerator.java
src/test/java/uk/gov/pay/api/filter/RestClientLoggingFilterTest.java
src/test/java/uk/gov/pay/api/filter/ratelimit/LocalRateLimiterTest.java
src/test/java/uk/gov/pay/api/filter/ratelimit/RedisRateLimiterTest.java
src/test/java/uk/gov/pay/api/it/directdebit/pact/DirectDebitPaymentIT.java
src/test/java/uk/gov/pay/api/it/telephone/TelephonePaymentResourceITBase.java
src/test/java/uk/gov/pay/api/resources/directdebit/DirectDebitPaymentsResourceCreatePaymentIT.java
src/test/java/uk/gov/pay/api/resources/directdebit/DirectDebitResourceITBase.java
src/test/java/uk/gov/pay/api/service/CardPaymentSearchServiceTest.java
src/test/java/uk/gov/pay/api/service/ConnectorUriGeneratorTest.java
src/test/java/uk/gov/pay/api/service/SearchRefundsServiceTest.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java

Changes:
* prevent unchecked assignment
** add `<>` when instantiating CachingAuthenticator
** update Appender mocking
** replaced `is(collectionWithSize` with `hasSize`
* remove unused imports
* remove unused methods
* remove unused parameters from methods
* remove unused fields and variables

BAU: clean up (last run)

---

.travis.yml
src/test/resources/config/test-config.yaml

Adds a simple .travis.yml build configuration for running CI java build tasks.

Run builds on travis

---

src/test/java/uk/gov/pay/api/service/SearchRefundsServiceTest.java
src/test/resources/pacts/publicapi-ledger-search-refunds-display-size-two.json

Description:
- Moved shouldSearchForAllExistingRefundsWithDisplaySizeTwo from 'publicapi' pay-endtoend into pact test

PP-6010 Pact test shouldSearchForAllExistingRefundsWithDisplaySizeTwo

---

src/main/java/uk/gov/pay/api/model/CreateCardPaymentRequest.java
src/main/java/uk/gov/pay/api/model/CreateCardPaymentRequestBuilder.java
src/test/java/uk/gov/pay/api/service/CreatePaymentServiceTest.java
src/test/resources/pacts/publicapi-connector-create-payment-with-moto-not-allowed.json

Pact test for creating a moto payment when the gateway account is not configured with moto enabled.

Pp 6077 moto disabled

---

src/main/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapper.java

bau: Make exception mapping more readable

---

src/test/java/uk/gov/pay/api/it/CreatePaymentIT.java
src/test/java/uk/gov/pay/api/it/GetPaymentIT.java
src/test/java/uk/gov/pay/api/json/CreateCardPaymentRequestDeserializerTest.java
src/test/java/uk/gov/pay/api/json/RequestJsonParserTest.java

Description:
- Adds test to check for moto payments via Ledger and Connector
- To avoid rewriting most of the test here I set moto to false and only turned it on for true for the new tests
- Added JUnit parameterized test for CreateCardPaymentRequestDeserializerTest

PP-6077 Modify GetPaymentIT

---

src/test/resources/pacts/publicapi-ledger-search-payments.json

PP-6077: Verify moto field is returned from ledger

---

src/test/resources/pacts/publicapi-ledger-search-transaction.json

bau: Consolidate search payment transaction pact

---

manifest.yml
src/main/resources/env-map.yml

Rename mapped publicapi_base environment variable to match env var sourced in dropwizard config.yml

Rename mapped publicapi_base env var

---

src/main/resources/env-map.yml

Adds missing env-map mapping of publicapi_url to PUBLICAPI_BASE env var.

PP-6127: Add missing PUBLICAPI_BASE env mapping

---

src/main/java/uk/gov/pay/api/resources/PaymentRefundsResource.java

Public API checks the refundable value on charges before submitting a
request for a new refund, this should use the future strategy to allow
it to proceed even if the charge has been removed from Connector.
Strategy is well tested and widely used already, if further integration tests are required they will need to rewrite a fair bit of structure in the refund IT tests.

PP-6135 Use get one payment strategy for refunds

---

src/main/java/uk/gov/pay/api/model/CardPayment.java
swagger/swagger.json
swagger/swagger_v3_0_0.json

PP-5955: Add description to moto payments flag

---

src/main/java/uk/gov/pay/api/model/CreatePaymentResult.java
swagger/swagger.json
swagger/swagger_v3_0_0.json

Descriptions lifted and adapted from https://github.com/alphagov/pay-publicapi/pull/730
Description for `moto` field added.
Generates both swagger v2 and v3 files.

PP-5955 Add descriptions to the CreatePaymentResult swagger object

---

src/test/java/uk/gov/pay/api/filter/ratelimit/RateLimitManagerTest.java

- refactor tests to clean up Mockito warnings

PP-6323 clean up Mockito Hints

---

src/main/java/uk/gov/pay/api/model/SettlementSummary.java

- new field settled_date from Ledger breaks strict SettlementSummary.  Mark it @JsonIgnoreProperties(ignoreUnknown = true)

P-6669 mark settlement summery to ignore unknown json properties

---

pom.xml
src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/app/config/PublicApiConfig.java
src/main/java/uk/gov/pay/api/app/config/PublicApiModule.java
src/main/java/uk/gov/pay/api/app/config/RedisConfiguration.java
src/main/java/uk/gov/pay/api/filter/ratelimit/LocalRateLimiter.java
src/main/java/uk/gov/pay/api/filter/ratelimit/RateLimiter.java
src/main/java/uk/gov/pay/api/filter/ratelimit/RedisRateLimiter.java
src/main/java/uk/gov/pay/api/managed/LettuceClientManager.java
src/main/java/uk/gov/pay/api/managed/RedisClientManager.java
src/main/resources/config/config.yaml
src/test/java/uk/gov/pay/api/filter/ratelimit/LocalRateLimiterTest.java
src/test/java/uk/gov/pay/api/filter/ratelimit/RedisRateLimiterTest.java
src/test/java/uk/gov/pay/api/it/ResourcesFilterLocalRateLimiterIT.java
src/test/java/uk/gov/pay/api/it/rule/RedisContainer.java
src/test/resources/config/empty-elevated-accounts-test-config.yaml
src/test/resources/config/test-config.yaml

Follows the basic usage according to https://github.com/lettuce-io/lettuce-core/wiki/Basic-usage

PP-6343: Replace Jedis with lettuce-core library

---

src/main/java/uk/gov/pay/api/model/SettlementSummary.java
src/test/java/uk/gov/pay/api/it/GetPaymentIT.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchIT.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentResultBuilder.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentSearchResultBuilder.java

- add settled_date field to SettlementSummary
- hide new field from Swagger generation (temporary thing)
- add new tests

PP-6670 add settled_date to settlement summary

---

src/test/java/uk/gov/pay/api/service/GetPaymentServiceLedgerTest.java
src/test/resources/pacts/publicapi-ledger-get-payment-with-settled-date.json

- add a pact test that checks for settled date

PP-6670 add a pact test containing settled date

---

src/main/java/uk/gov/pay/api/common/SearchConstants.java
src/main/java/uk/gov/pay/api/ledger/model/TransactionSearchParams.java
src/main/java/uk/gov/pay/api/ledger/service/TransactionSearchService.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/service/PaymentSearchParams.java
src/main/java/uk/gov/pay/api/service/RefundsParams.java
src/main/java/uk/gov/pay/api/validation/PaymentSearchValidator.java
src/main/java/uk/gov/pay/api/validation/SearchValidator.java
src/test/java/uk/gov/pay/api/service/CardPaymentSearchServiceTest.java
src/test/java/uk/gov/pay/api/service/SearchRefundsServiceTest.java
src/test/java/uk/gov/pay/api/validation/PaymentSearchValidatorTest.java
src/test/resources/pacts/publicapi-ledger-search-payments-with-settled_dates.json
src/test/resources/pacts/publicapi-ledger-search-refunds_with_settled_dates.json

- refactor the way the search is conducted by settled dates
- settled dates format is yyyy-MM-dd
- add validation for settled dates
- add/refactor relevant tests
- add pacts test for ledger payment and refund search

PP-7211 refactor search by settled date

---

src/main/java/uk/gov/pay/api/resources/SearchRefundsResource.java
src/main/java/uk/gov/pay/api/service/RefundsParams.java
src/main/java/uk/gov/pay/api/validation/RefundSearchValidator.java
src/test/java/uk/gov/pay/api/it/SearchRefundsResourceIT.java
src/test/java/uk/gov/pay/api/service/SearchRefundsServiceTest.java
src/test/java/uk/gov/pay/api/validation/RefundSearchValidatorTest.java

- add search by settled dates to the search refunds endpoint
- add/update relevant tests

PP-7211 add settled date search to refunds endpoint

---

src/main/java/uk/gov/pay/api/model/RefundResponse.java
src/main/java/uk/gov/pay/api/model/SettlementSummary.java
src/main/java/uk/gov/pay/api/model/search/card/RefundForSearchRefundsResult.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/resources/SearchRefundsResource.java
swagger/swagger.json
swagger/swagger_v3_0_0.json

- expose the new field settled date in settlement summary
- expose the new search fields (from and to settled date)

PP-7256 expose settled date and search by to swagger

---

src/main/java/uk/gov/pay/api/model/PaymentConnectorResponseLink.java
src/main/java/uk/gov/pay/api/model/ledger/TransactionState.java

- add json's ignore unknown properties annotation to the classes that were missed in previous iterations

PP-7208 add ignore unknown annotations

---

src/main/java/uk/gov/pay/api/auth/Account.java
src/main/java/uk/gov/pay/api/auth/AccountAuthenticator.java
src/test/java/uk/gov/pay/api/filter/RateLimiterFilterTest.java
src/test/java/uk/gov/pay/api/it/CachingAuthenticatorIT.java
src/test/java/uk/gov/pay/api/it/directdebit/pact/CancelPaymentIT.java
src/test/java/uk/gov/pay/api/it/telephone/pact/CreateTelephonePaymentServiceTest.java
src/test/java/uk/gov/pay/api/ledger/service/TransactionSearchServiceTest.java
src/test/java/uk/gov/pay/api/resources/GetOnePaymentStrategyTest.java
src/test/java/uk/gov/pay/api/resources/GetPaymentEventsStrategyTest.java
src/test/java/uk/gov/pay/api/resources/GetPaymentRefundStrategyTest.java
src/test/java/uk/gov/pay/api/resources/GetPaymentRefundsStrategyTest.java
src/test/java/uk/gov/pay/api/resources/PaymentsResourceCreatePaymentTest.java
src/test/java/uk/gov/pay/api/resources/directdebit/DirectDebitPaymentsResourceCreatePaymentIT.java
src/test/java/uk/gov/pay/api/service/CancelPaymentServiceTest.java
src/test/java/uk/gov/pay/api/service/CapturePaymentServiceTest.java
src/test/java/uk/gov/pay/api/service/CardPaymentSearchServiceTest.java
src/test/java/uk/gov/pay/api/service/ConnectorUriGeneratorTest.java
src/test/java/uk/gov/pay/api/service/CreatePaymentServiceTest.java
src/test/java/uk/gov/pay/api/service/DirectDebitPaymentSearchServiceTest.java
src/test/java/uk/gov/pay/api/service/GetDirectDebitPaymentServiceContractTest.java
src/test/java/uk/gov/pay/api/service/GetPaymentEventsServiceTest.java
src/test/java/uk/gov/pay/api/service/GetPaymentRefundServiceTest.java
src/test/java/uk/gov/pay/api/service/GetPaymentRefundsServiceTest.java
src/test/java/uk/gov/pay/api/service/GetPaymentServiceLedgerTest.java
src/test/java/uk/gov/pay/api/service/GetPaymentServiceTest.java
src/test/java/uk/gov/pay/api/service/MandatesServiceTest.java
src/test/java/uk/gov/pay/api/service/SearchRefundsServiceTest.java
src/test/java/uk/gov/pay/api/service/directdebit/DirectDebitMandateSearchServiceTest.java
src/test/java/uk/gov/pay/api/validation/PaymentSearchValidatorTest.java

- Added tokenLink field to Account object which is set when an API token is authenticated.
tokenLink to be added to MDC so it is logged for all publicapi log lines

PP-7429 Add token link to Account object

---

Dockerfile

Description:
- This PR updates the Docker image to use 11.0.9

PP-7283 - Upgrade docker image to 11.0.9

---

pom.xml

Reverts alphagov/pay-publicapi#1056

Revert "Bump jackson.version from 2.11.3 to 2.12.0"

---

Jenkinsfile

Don't run publicapi->direct-debit-connector provider contract test.
Fixes https://build.ci.pymnt.uk/job/pay-publicapi/job/master/421 🤞

PP-7834: Fix build

---

pom.xml
src/main/java/uk/gov/pay/api/resources/DirectDebitEventsResource.java
src/main/java/uk/gov/pay/api/resources/MandatesResource.java
src/main/java/uk/gov/pay/api/resources/PaymentRefundsResource.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/resources/SearchRefundsResource.java
src/main/java/uk/gov/pay/api/resources/directdebit/DirectDebitPaymentsResource.java
src/main/java/uk/gov/pay/api/resources/telephone/TelephonePaymentNotificationResource.java

- Removed `swagger-maven-plugin` as we no longer intend to maintain swagger v2
- Removed swagger annotations used to generate `swagger.json` from resources
TODO: To remove annotations on model classes in a separate PR

PP-7896 Remove swagger maven plugin

---

README.md
openapi/publicapi_spec.json
src/main/resources/swagger-config.yaml

- Sort API specs objects and properties. Specs are currently generated without an order and could change with `mvn compile` which makes it hard to distinguish with API changes
updated specs 
------
previously
------

PP-7896 Sort API specification output

---

src/test/java/uk/gov/pay/api/service/CreatePaymentServiceTest.java

Description:
- Previous PR created the JSON file this PR adds the pact test

PP-8210 - Add pact test for create payment with credentials in created

---

README.md
src/main/java/uk/gov/pay/api/app/config/RateLimiterConfig.java
src/main/resources/config/config.yaml
src/test/java/uk/gov/pay/api/it/validation/PublicApiConfigIT/EmptyLowTrafficAccountsPublicApiConfigIT.java
src/test/resources/config/empty-elevated-accounts-test-config.yaml
src/test/resources/config/empty-low-traffic-accounts-test-config.yaml

- Added new config variables to rate limit accounts with low traffic volume.

PP-8550 Add config variables to rate limit low traffic accounts

---

openapi/publicapi_spec.json
src/main/java/uk/gov/pay/api/model/AuthorisationSummary.java
src/main/java/uk/gov/pay/api/model/CardPayment.java
src/main/java/uk/gov/pay/api/model/Charge.java
src/main/java/uk/gov/pay/api/model/ChargeFromResponse.java
src/main/java/uk/gov/pay/api/model/ThreeDSecure.java
src/main/java/uk/gov/pay/api/model/TransactionResponse.java
src/main/java/uk/gov/pay/api/model/links/PaymentWithAllLinks.java
src/main/java/uk/gov/pay/api/model/search/card/GetPaymentResult.java
src/main/java/uk/gov/pay/api/model/search/card/PaymentForSearchResult.java
src/test/java/uk/gov/pay/api/it/GetPaymentIT.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentResultBuilder.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentSearchResultBuilder.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentSingleResultBuilder.java
src/test/java/uk/gov/pay/api/it/ledger/TransactionsResourceIT.java
src/test/java/uk/gov/pay/api/resources/PaymentsResourceCreatePaymentTest.java
src/test/java/uk/gov/pay/api/utils/mocks/ChargeResponseFromConnector.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java
src/test/java/uk/gov/pay/api/utils/mocks/TransactionFromLedgerFixture.java

- adds authorisation_summary to get one / search payments response from connector / ledger.
- update / add tests.

PP-8535 Add 3DS info to get one or search payments

---

src/main/java/uk/gov/pay/api/model/CardPayment.java
src/test/java/uk/gov/pay/api/service/CardPaymentSearchServiceTest.java
src/test/java/uk/gov/pay/api/service/GetPaymentServiceLedgerTest.java
src/test/java/uk/gov/pay/api/service/GetPaymentServiceTest.java
src/test/resources/pacts/publicapi-connector-get-payment.json
src/test/resources/pacts/publicapi-ledger-get-payment-with-authorisation-summary.json
src/test/resources/pacts/publicapi-ledger-search-payments.json

- update connector get one payment with authorisation_summary field
- update ledger search payments with authorisation_summary field
- add ledger get one payment with authorisation_summary field

PP-8535 add new and update pact tests with 3ds information

---

src/main/java/uk/gov/pay/api/filter/ratelimit/RedisRateLimiter.java
src/test/java/uk/gov/pay/api/filter/ratelimit/RedisRateLimiterTest.java

Description:
- This is so we can get some useful metrics for how quickly Redis performs increment and expire values

PP-8844 - Add timer metric for Redis calls

---

pom.xml

This overrides the transitive dependency via Dropwizard-sentry which
would install v2.14.1 which has a known CVE.
Confirm the pinning of log4j
```
gds5062-2:pay-publicapi danworth$ mvn dependency:tree -Dincludes="*log4j:log4j*"
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------------< uk.gov.pay:pay-publicapi >----------------------
[INFO] Building pay-publicapi 0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:3.2.0:tree (default-cli) @ pay-publicapi ---
[INFO] uk.gov.pay:pay-publicapi:jar:0.1-SNAPSHOT
[INFO] +- org.apache.logging.log4j:log4j-core:jar:2.15.0:compile
[INFO] \- org.apache.logging.log4j:log4j-api:jar:2.15.0:compile
[INFO] …
```

PP-9010 Pin log4j-core and api to v2.15.0

---

.github/workflows/post-merge.yml
.github/workflows/run-tests.yml

[Successful publish and tag pact run](https://github.com/alphagov/pay-publicapi/runs/5572605868?check_suite_focus=true). Can also verify from the pact broker that the pact was published [not too long ago](https://pact-broker-test.cloudapps.digital/matrix?q%5B%5Dpacticipant=publicapi&q%5B%5Dversion=e4bec79ace56aa1ce93db7123a38ac29db6e2458&q%5B%5Dpacticipant=connector&latestby=cvpv&limit=100).

PP-9236: Run pact tests and publish result

---

Jenkinsfile

Pacts are published on post-merge now
(https://github.com/alphagov/pay-publicapi/pull/1388) and PR builds are
happening in concourse so these can be deleted.

PP-9236: Clean up jenkinsfile

---

.github/workflows/post-merge.yml
Jenkinsfile

We can see the "Run Ledger as Provider" and "Run Connector as Provider" checks on this PR run successfully.

Pp 9236 run pact provider tests

---

src/main/java/uk/gov/pay/api/agreement/model/Agreement.java
src/main/java/uk/gov/pay/api/agreement/model/AgreementResponse.java
src/main/java/uk/gov/pay/api/agreement/model/CreateAgreementRequest.java
src/main/java/uk/gov/pay/api/agreement/model/builder/AgreementResponseBuilder.java
src/main/java/uk/gov/pay/api/agreement/resource/AgreementsApiResource.java
src/main/java/uk/gov/pay/api/agreement/service/AgreementService.java
src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/exception/CreateAgreementException.java
src/main/java/uk/gov/pay/api/exception/mapper/CreateAgreementExceptionMapper.java
src/main/java/uk/gov/pay/api/model/PaymentError.java
src/main/java/uk/gov/pay/api/service/ConnectorUriGenerator.java
src/test/java/uk/gov/pay/api/exception/mapper/CreateAgreementExceptionMapperTest.java
src/test/java/uk/gov/pay/api/it/CreateAgreementIT.java
src/test/java/uk/gov/pay/api/service/CreateAgreementServiceTest.java
src/test/java/uk/gov/pay/api/utils/mocks/AgreementResponseFromConnector.java
src/test/java/uk/gov/pay/api/utils/mocks/BaseConnectorMockClient.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java
src/test/java/uk/gov/pay/api/utils/mocks/CreateAgreementRequestParams.java

1. Implemented create agreement endpoint
2. Agreement Service layer
3. Test cases
4. Exception handling

PP-9329 public api create agreement endpoint

---

src/main/java/uk/gov/pay/api/agreement/resource/AgreementsApiResource.java
src/test/java/uk/gov/pay/api/it/CreateAgreementIT.java

Changed the create agreement url

PP-9329: changed create agreement url

---

src/main/java/uk/gov/pay/api/agreement/model/CreateAgreementRequest.java
src/main/java/uk/gov/pay/api/app/config/PublicApiModule.java
src/main/java/uk/gov/pay/api/json/CreateAgreementRequestDeserializer.java
src/main/java/uk/gov/pay/api/json/RequestJsonParser.java
src/main/java/uk/gov/pay/api/model/CreateAgreementRequestBuilder.java
src/main/java/uk/gov/pay/api/model/PaymentError.java
src/test/java/uk/gov/pay/api/it/CreateAgreementIT.java
src/test/java/uk/gov/pay/api/json/CreateAgreementRequestDeserializerTest.java
src/test/java/uk/gov/pay/api/service/CreateAgreementServiceTest.java

This is for addressing  the following issues found in end to end testing
1. fixing the create agreement  url
2. validation of create agreement request.

PP-9329: Create Agreement endpoint

---

src/test/resources/pacts/publicapi-connector-create-payment-with-authorisation-mode-moto-api.json

Amend Connector-PublicAPI Pact test to match type over value

PP-9390 pact test match type over value

---

src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/exception/mapper/ViolationExceptionMapper.java
src/main/java/uk/gov/pay/api/model/AuthorisationRequest.java
src/main/java/uk/gov/pay/api/resources/AuthorisationResource.java
src/test/java/uk/gov/pay/api/resources/AuthorisationResourceIT.java

- implement validation of the request payload for AuthorisationRequest
- add relevant tests
with @stephencdaly

PP-9407 implement request validation

---

pom.xml

Reverts alphagov/pay-publicapi#1443

Revert "Bump dropwizard-dependencies from 2.0.29 to 2.1.0"

---

pom.xml

Reverts alphagov/pay-publicapi#1442

Revert "Bump dropwizard.version from 2.0.29 to 2.1.0"

---

openapi/publicapi_spec.json

- Re-generate (`mvn compile`) openAPI specs to reflect the changes in https://github.com/alphagov/pay-publicapi/pull/1435

PP-9592 Update openapi specs

---

openapi/publicapi_spec.json
src/main/java/uk/gov/pay/api/resources/AuthorisationResource.java
src/main/resources/swagger-config.yaml

- Generated OpenAPI specs for auth endpoint

PP-9592 Generate OpenAPI specs for /v1/auth endpoint

---

pom.xml
src/main/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapper.java
src/main/java/uk/gov/pay/api/model/RequestError.java
src/test/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapperTest.java
src/test/java/uk/gov/pay/api/service/CreatePaymentServiceTest.java
src/test/resources/pacts/publicapi-connector-create-payment-for-disabled-account.json

* New RequestError
* New CreateChargeException mapping
* New pact test

PP-9587: Map account disabled error from Connector

---

src/main/java/uk/gov/pay/api/exception/DisputesValidationException.java
src/main/java/uk/gov/pay/api/model/RequestError.java
src/main/java/uk/gov/pay/api/service/DisputesParams.java
src/main/java/uk/gov/pay/api/validation/DisputeSearchValidator.java
src/test/java/uk/gov/pay/api/validation/DisputeSearchValidatorTest.java

- implement validating search params for disputes searches
- add test

PP-9675 implement validation of dispute search params

---

src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/exception/SearchDisputeException.java
src/main/java/uk/gov/pay/api/exception/mapper/DisputeValidationExceptionMapper.java
src/main/java/uk/gov/pay/api/model/ledger/DisputeSettlementSummary.java
src/main/java/uk/gov/pay/api/model/ledger/DisputeTransactionFromLedger.java
src/main/java/uk/gov/pay/api/model/ledger/SearchDisputeResponseFromLedger.java
src/main/java/uk/gov/pay/api/model/links/DisputeLinksForSearch.java
src/main/java/uk/gov/pay/api/model/search/dispute/DisputeForSearchResult.java
src/main/java/uk/gov/pay/api/model/search/dispute/DisputeSearchResults.java
src/main/java/uk/gov/pay/api/service/LedgerService.java
src/main/java/uk/gov/pay/api/service/SearchDisputesService.java
src/test/java/uk/gov/pay/api/service/SearchDisputesServiceTest.java
src/test/resources/pacts/publicapi-ledger-search-disputes_by_settled_dates.json

- implement a new service that searches Ledger for disputes
- add tests

PP-9675 implement search disputes service

---

openapi/publicapi_spec.json
src/main/java/uk/gov/pay/api/model/ledger/DisputeSettlementSummary.java
src/main/java/uk/gov/pay/api/model/links/DisputeLinksForSearch.java
src/main/java/uk/gov/pay/api/model/links/SearchNavigationLinks.java
src/main/java/uk/gov/pay/api/model/search/dispute/DisputeForSearchResult.java
src/main/java/uk/gov/pay/api/model/search/dispute/DisputesSearchResults.java
src/main/java/uk/gov/pay/api/resources/SearchDisputesResource.java
src/main/java/uk/gov/pay/api/validation/DisputeSearchValidator.java
src/main/resources/swagger-config.yaml

- add Swagger annotations to the new resource and classes that it uses.
- re-generate publicapi_spec.json

PP-9675 add Swagger annotations to new resource

---

src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/exception/mapper/AgreementValidationExceptionMapper.java
src/test/java/uk/gov/pay/api/it/AgreementsIT.java

Add `AgreementValidationExceptionMapper` and an integration test to check it’s been used.

PP-9545 Add AgreementValidationExceptionMapper

---

openapi/publicapi_spec.json
src/main/java/uk/gov/pay/api/common/ResponseConstants.java
src/main/java/uk/gov/pay/api/resources/AuthorisationResource.java
src/main/java/uk/gov/pay/api/resources/PaymentRefundsResource.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/resources/SearchDisputesResource.java
src/main/java/uk/gov/pay/api/resources/SearchRefundsResource.java
src/main/resources/swagger-config.yaml

- OpenAPI spec is being updated to be consistent with Pay API docs
- Working to [Nathan's changes](https://github.com/alphagov/pay-publicapi/pull/1617/files)
- Updated parameter descriptions to match the changes above

PP-10265 Update openapi spec parameter descriptions

---

.secrets.baseline
openapi/publicapi_spec.json
src/main/java/uk/gov/pay/api/model/Address.java
src/main/java/uk/gov/pay/api/model/CardDetails.java
src/main/java/uk/gov/pay/api/model/CardPayment.java
src/main/java/uk/gov/pay/api/model/CreateCardPaymentRequest.java
src/main/java/uk/gov/pay/api/model/CreatePaymentRefundRequest.java
src/main/java/uk/gov/pay/api/model/CreatePaymentResult.java
src/main/java/uk/gov/pay/api/model/Payment.java
src/main/java/uk/gov/pay/api/model/PaymentEventResponse.java
src/main/java/uk/gov/pay/api/model/PaymentEventsResponse.java
src/main/java/uk/gov/pay/api/model/PaymentSettlementSummary.java
src/main/java/uk/gov/pay/api/model/PaymentState.java
src/main/java/uk/gov/pay/api/model/PrefilledCardholderDetails.java
src/main/java/uk/gov/pay/api/model/RefundResponse.java
src/main/java/uk/gov/pay/api/model/RefundSettlementSummary.java
src/main/java/uk/gov/pay/api/model/RefundSummary.java
src/main/java/uk/gov/pay/api/model/RefundsResponse.java
src/main/java/uk/gov/pay/api/model/RequestError.java
src/main/java/uk/gov/pay/api/model/ThreeDSecure.java
src/main/java/uk/gov/pay/api/model/ledger/DisputeSettlementSummary.java
src/main/java/uk/gov/pay/api/model/links/Link.java
src/main/java/uk/gov/pay/api/model/links/SearchNavigationLinks.java
src/main/java/uk/gov/pay/api/model/search/card/PaymentSearchResults.java
src/main/java/uk/gov/pay/api/model/search/card/RefundForSearchRefundsResult.java
src/main/java/uk/gov/pay/api/model/search/card/RefundForSearchResult.java
src/main/java/uk/gov/pay/api/model/search/card/SearchRefundsResults.java
src/main/java/uk/gov/pay/api/resources/error/ApiErrorResponse.java
src/main/resources/swagger-config.yaml

- publicapi_spec is being updated to be consistent with Pay API docs
- these changes to schema descriptions implement Nathan's proposed changes
which are [here](https://github.com/alphagov/pay-publicapi/pull/1621)

PP-10265 update openapi schema descriptions

---

m1/arm64.Dockerfile

fixes an issue with the arm64 build process where some RUN commands were causing an error

BAU fix arm64 build failure

---

src/main/java/uk/gov/pay/api/agreement/resource/AgreementsApiResource.java
src/main/java/uk/gov/pay/api/filter/LoggingMDCRequestFilter.java

- Put the agreement_external_id on the MDC for requests having the agreementId as a path parameter
- Log a line when an agreement is created, including the agreement id

PP-10488 Add missing logging for recurring payments

---

.secrets.baseline
openapi/publicapi_spec.json
src/main/java/uk/gov/pay/api/agreement/model/AgreementSearchResults.java
src/main/java/uk/gov/pay/api/model/CreateCardPaymentRequest.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java

- OpenAPI spec is being updated to reflect latest changes to API reference now that some RCP features are being enabled
- Update PaymentsResource endpoints with descriptions for parameters that relate to agreements

PP-10441 Update openapi spec for Payments for RCP

---

src/test/java/uk/gov/pay/api/service/GetPaymentServiceTest.java
src/test/resources/pacts/publicapi-connector-get-rejected-rcp-payment-with-can-retry-true.json

- add a new pact test that verifies a rejected recurring payment with can retry true against connector

PP-10982 add new pact test

---

openapi/publicapi_spec.json
src/main/java/uk/gov/pay/api/agreement/model/Agreement.java
src/main/java/uk/gov/pay/api/agreement/model/AgreementLedgerResponse.java
src/test/java/uk/gov/pay/api/it/AgreementsApiResourceIT.java
src/test/java/uk/gov/pay/api/it/AgreementsApiResourceSearchIT.java
src/test/java/uk/gov/pay/api/utils/mocks/AgreementFromLedgerFixture.java
src/test/java/uk/gov/pay/api/utils/mocks/LedgerMockClient.java

- when getting a single agreement, return cancelled date if applicable
- when searching agreements, return cancelled date if applicable

PP-10520 return cancelled date

---

src/test/resources/pacts/publicapi-connector-create-payment-with-idempotency-key-200-response.json
src/test/resources/pacts/publicapi-connector-create-payment-with-idempotency-key-409-response.json
src/test/resources/pacts/publicapi-connector-get-rejected-rcp-payment-with-can-retry-true.json

- refactor providersates for agreement related pact tests to use the new one-in-all state in connector
with @james-peacock-gds

PP-10598 refactor agreement pact tests

---

pom.xml

- overriding json vulnerability for pact consumer version

BAU vulnerability triage fix

---

.secrets.baseline
src/test/java/uk/gov/pay/api/service/AgreementServiceConnectorTest.java
src/test/java/uk/gov/pay/api/service/AgreementServiceLedgerTest.java
src/test/java/uk/gov/pay/api/service/GetOneAgreementLedgerServicePactTest.java
src/test/resources/pacts/publicapi-ledger-get-one-agreement.json

- get one agreement from ledger pact test

PP-11121 get one agreement pact test

---

src/test/java/uk/gov/pay/api/service/GetOneAgreementLedgerServicePactTest.java
src/test/resources/pacts/publicapi-ledger-get-one-agreement-not-found.json

- add a pact test when the agreement does not exist

PP-11121 add agreement not found pact test

---

src/test/java/uk/gov/pay/api/service/SearchAgreementsLedgerServicePactTest.java
src/test/resources/pacts/publicapi-ledger-search-agreement-not-found.json
src/test/resources/pacts/publicapi-ledger-search-agreements-with-reference.json
src/test/resources/pacts/publicapi-ledger-search-agreements-with-status.json

- Add consumer tests for PACT with ledger for search agreements

PP-9884 Search agreements PACTs

---

src/main/java/uk/gov/pay/api/agreement/model/AgreementCreatedResponse.java
src/test/java/uk/gov/pay/api/service/CreateAgreementLedgerServicePactTest.java
src/test/resources/pacts/publicapi-connector-cancel-agreement-with-active-status.json
src/test/resources/pacts/publicapi-connector-create-agreement-for-non-rcp-account.json
src/test/resources/pacts/publicapi-connector-create-agreement.json
src/test/resources/pacts/publicapi-connector-create-payment-with-idempotency-key-409-response.json

- Added pact tests for the create agreements endpoint
- Fixed a few pact files which are causing issues when pacts are run as a provider locally.

PP-10443 Add pact tests for create agreement endpoint

---

src/test/java/uk/gov/pay/api/service/CreatePaymentServicePactTest.java
src/test/resources/pacts/publicapi-connector-take-a-recurring-payment.json

- add a new pact test for taking a recurring payment
with @james-peacock-gds

PP-10599 add a tekae a recurring payment pact test

---

src/test/java/uk/gov/pay/api/service/SetUpAgreementWithPaymentConnectorServicePactTest.java
src/test/resources/pacts/publicapi-connector-create-payment-to-setup-agreement.json

- Add PACT consumer test for setup agreement

PP-10599-PACT-for-setup-agreement

---

.github/workflows/post-merge.yml

PP-11292 update pact broker host

---

.github/dependabot.yml

Tell Dependabot to ignore dropwizard version 4 because it only works with Jakarta.

PP-12175 add dependabot ignores

---

.github/workflows/codeql.yml

Correct CodeQL config to scan all files in src folder on push to master

PP-12211 Scan all files in src on push to master

---

.github/dependabot.yml
.github/workflows/_run-tests.yml
.github/workflows/codeql.yml
Dockerfile
m1/arm64.Dockerfile
pom.xml

- Upgrades to Java 21
- Also upgrades pact library as pact tests are failing on the current version of the library

PP-12727 Upgrade to Java 21

---

src/main/resources/config/config.yaml

Reverts alphagov/pay-publicapi#2012

Revert "PP-12517: Set DEBUG level for the logger io.lettuce.core.protocol"

---

src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/test/java/uk/gov/pay/api/resources/SearchPaymentsResourceTest.java

- redact cardholder name and email from logs when searching payments
- add unit test to validate logs

PP-12750 redact personal data from logs

---

src/main/resources/config/config.yaml

Reverts alphagov/pay-publicapi#2030

Revert "PP-12517: Set DEBUG level for the logger io.lettuce.core.protocol again"

---

.secrets.baseline
README.md
src/main/resources/config/config.yaml
src/test/resources/config/empty-elevated-accounts-test-config.yaml
src/test/resources/config/empty-low-traffic-accounts-test-config.yaml
src/test/resources/config/test-config.yaml

Bind to 127.0.0.1 by default instead of 0.0.0.0
I followed the exact same testing strategy as https://github.com/alphagov/pay-connector/pull/5539 and achieved the same results

PP-13145: Accept BIND_HOST env var and default to localhost

---

openapi/publicapi_spec.json
src/main/java/uk/gov/pay/api/model/CardPayment.java
src/main/java/uk/gov/pay/api/model/Charge.java
src/main/java/uk/gov/pay/api/model/ChargeFromResponse.java
src/main/java/uk/gov/pay/api/model/Exemption.java
src/main/java/uk/gov/pay/api/model/ExemptionOutcome.java
src/main/java/uk/gov/pay/api/model/TransactionResponse.java
src/main/java/uk/gov/pay/api/model/links/PaymentWithAllLinks.java
src/main/java/uk/gov/pay/api/model/search/card/PaymentForSearchResult.java
src/main/java/uk/gov/pay/api/utils/ExemptionEvaluator.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceGetIT.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceSearchIT.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentResultBuilder.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentSearchResultBuilder.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentSingleResultBuilder.java
src/test/java/uk/gov/pay/api/utils/ExemptionEvaluatorTest.java
src/test/java/uk/gov/pay/api/utils/mocks/ChargeResponseFromConnector.java
src/test/java/uk/gov/pay/api/utils/mocks/MockHelperFunctions.java
src/test/java/uk/gov/pay/api/utils/mocks/TransactionFromLedgerFixture.java

API should return exemption object in payment responses when appropriate.

PP-13334 add exemption model

---

openapi/publicapi_spec.json
src/main/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapper.java
src/test/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapperTest.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceCreateIT.java

Correct link to docs in error message for a payment below the minimum amount.

PP-13359 Correct 422 message for below minimum amount

---

openapi/publicapi_spec.json
src/main/java/uk/gov/pay/api/model/CardPayment.java
src/main/java/uk/gov/pay/api/model/Charge.java
src/main/java/uk/gov/pay/api/model/ChargeFromResponse.java
src/main/java/uk/gov/pay/api/model/Exemption.java
src/main/java/uk/gov/pay/api/model/ExemptionOutcome.java
src/main/java/uk/gov/pay/api/model/TransactionResponse.java
src/main/java/uk/gov/pay/api/model/links/PaymentWithAllLinks.java
src/main/java/uk/gov/pay/api/model/search/card/PaymentForSearchResult.java
src/main/java/uk/gov/pay/api/utils/InternalExemptionToPublicApiExemptionConverter.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceGetIT.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceSearchIT.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentResultBuilder.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentSearchResultBuilder.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentSingleResultBuilder.java
src/test/java/uk/gov/pay/api/service/GetPaymentServiceLedgerPactTest.java
src/test/java/uk/gov/pay/api/service/GetPaymentServicePactTest.java
src/test/java/uk/gov/pay/api/utils/InternalExemptionToPublicApiExemptionConverterTest.java
src/test/java/uk/gov/pay/api/utils/mocks/ChargeResponseFromConnector.java
src/test/java/uk/gov/pay/api/utils/mocks/MockHelperFunctions.java
src/test/java/uk/gov/pay/api/utils/mocks/TransactionFromLedgerFixture.java
src/test/resources/pacts/publicapi-connector-get-payment-with-honoured-corporate-exemption.json
src/test/resources/pacts/publicapi-ledger-get-payment-with-honoured-exemption.json

API should return exemption object in payment responses when appropriate.

PP-13334 API returns exemption object

---

pom.xml
src/main/java/uk/gov/pay/api/app/PublicApi.java

import `SentryAppenderFactory` from dropwizard-sentry.

PP-13991 refactor to use vanilla SentryAppenderFactory
