alphagov/pay-publicapi

src/main/java/uk/gov/pay/api/model/Payment.java
src/main/java/uk/gov/pay/api/model/PaymentJSON.java
src/main/java/uk/gov/pay/api/model/PaymentWithLinks.java
src/main/java/uk/gov/pay/api/model/PaymentWithLinksJSON.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
swagger/swagger.json

This addresses the need to have separate response structures for
'create', 'find by payment id' and 'search payments'. Providing links in
the response for search payments doesn't make sense as it presents a
snapshot of each payment. However 'create' and 'find by payment id'
require links to be present in their responses.
* Introducing a concept of PaymentWithLinks to represent the fact that
its different from a Payment
* All JSON and API documentation annotations are moved to interfaces to
give the value objects json behaviors.
* The objects would just be value objects with the interfaces giving
them JSON and API documentation capabilities.
* Both create payments and find payment now uses the new PaymentWithLink
object as it makes sense to include links in these responses.
* Search …

PP-539 Selectively including links in the payment responses

---

src/main/java/uk/gov/pay/api/model/CreatePaymentRequest.java

* Removing the ignore unknown properties capability when parsing a json
payload to create a payment.
* If the payload has an attribute that we don't know about, the request
will response with a 400.

PP-539 Making the create payment payload restrictive.

---

README.md
src/main/java/uk/gov/pay/api/model/PaymentSearchResults.java
src/main/java/uk/gov/pay/api/model/PaymentWithSelfLinks.java
src/main/java/uk/gov/pay/api/model/PaymentWithSelfLinksJSON.java
src/main/java/uk/gov/pay/api/model/SelfAndNextLinks.java
src/main/java/uk/gov/pay/api/model/SelfLinks.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/test/java/uk/gov/pay/api/it/PaymentSearchITest.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentSearchResultBuilder.java
swagger/swagger.json

PP-539 Allowing self link for payments from search    
* Including self link in payment search response. Only self link is
available in the '_links' object of the payment search response.
* Introducing separate objects to represent search results, links that
only have safe links and links that have both safe links and next_url
links.
* Every response other than payment search and cancel will have the
next_url in the links object
* Adding tests to assert we are returning everything we need to return
* Fixing typo in documentation

PP-539 Allowing self links in payment search

---

.gitignore
docker-startup.sh
src/main/java/uk/gov/pay/api/config/RestClientConfig.java
src/main/java/uk/gov/pay/api/resources/RestClientFactory.java
src/main/java/uk/gov/pay/api/utils/TrustStoreLoader.java
src/main/java/uk/gov/pay/api/validation/URLValidator.java
src/main/resources/config/config.yaml
src/test/java/uk/gov/pay/api/resources/RestClientFactoryTest.java
src/test/resources/config/test-config.yaml

There is no need for the private keys.
cacerts is a truststore, not a keystore.
Move to a programmatic approach for creating a truststore from the pem directory, to avoid the need for bash scripting inside the containers.

PP 618 fix cert loading

---

src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/exception/CreateChargeConnectorErrorResponseException.java
src/main/java/uk/gov/pay/api/exception/CreateChargeConnectorErrorResponseExceptionMapper.java
src/main/java/uk/gov/pay/api/model/CreatePaymentRequest.java
src/main/java/uk/gov/pay/api/model/PaymentErrorResponse.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceITest.java
src/test/java/uk/gov/pay/api/utils/ConnectorMockClient.java
swagger/swagger.json

- When Authorization succeed but Gateway account is Not Found in Connector, PublicAPI returns a 500 rather than a 400 Bad Request. This situation can't theoretically happen and a client can't recover from this without support.

PP-611 500 Error mapping Creating a Charge when Gateway account does not exist

---

README.md
src/main/java/uk/gov/pay/api/model/Link.java
src/main/java/uk/gov/pay/api/model/PaymentEvent.java
src/main/java/uk/gov/pay/api/model/PostLink.java
src/main/java/uk/gov/pay/api/model/SelfAndNextLinks.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/test/java/uk/gov/pay/api/it/PaymentSearchITest.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceITest.java
src/test/java/uk/gov/pay/api/utils/ChargeEventBuilder.java
swagger/swagger.json

- The payment event dates were using LocalDateTime. This has been changed now to use what the connector would return (as we do with dates returned by other end-points). Connector returns ZoneDateTime.
- The next_url_post has type and params as documentation. These don't apply to GET links. Therefore GET links and POST links are separated.
- Making it clear that authroization header requires Bearer <TOKEN> as swagger fails to document this nicely.

PP-539 Fixing payment event dates and Links

---

README.md
src/main/java/uk/gov/pay/api/model/Payment.java
src/main/java/uk/gov/pay/api/model/PaymentForSearchResult.java
src/main/java/uk/gov/pay/api/model/PaymentWithAllLinks.java
src/main/java/uk/gov/pay/api/model/links/PaymentLinks.java
src/main/java/uk/gov/pay/api/model/links/PaymentLinksForSearch.java
src/main/java/uk/gov/pay/api/model/links/PostLink.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/test/java/uk/gov/pay/api/it/PaymentResourceITestBase.java
src/test/java/uk/gov/pay/api/it/PaymentSearchITest.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceITest.java
swagger/swagger.json

**WHAT**
Introduces a cancel link in payment objects returned for creating a payment, issuing a GET on a payment and searching for a payment
Also includes some refactoring.
**HOW TO REVIEW**
Apart from the code changes, review the README as well please.
Also when reviewing this please note that https://payments-platform.atlassian.net/browse/PP-640 is also ready for review
**WHO**
any dev

PP-640 Add cancel link in payment objects

---

src/main/java/uk/gov/pay/api/model/PaymentEvent.java
src/main/java/uk/gov/pay/api/model/PaymentEvents.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceITest.java
src/test/java/uk/gov/pay/api/utils/ChargeEventBuilder.java

Connector doesn’t return chargeID with every event structure anymore as its in the top level of the structure, which was causing null pointer exception as it was being probed from within the events, this fix stops the chargeId from being probed within every event and looks for it at the top level instead

PP-677 stopped publicapi events end point from throwing null pointer for missing chargeID

---

.gitignore
src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/resources/HealthCheckResource.java
src/test/java/uk/gov/pay/api/it/HealthCheckResourceITest.java
src/test/java/uk/gov/pay/api/resources/HealthCheckResourceTest.java

* The DropWizard healthcheck endpoint is on the admin port and this
creates much more complexity when routing ports through nginxes, proxies
and security groups.
* The Healthcheck should be available on the application port, making use
of the existing healthchecks that follow Dropwizard's standards.
* Developers and DevOps

PP-656 Improve healthchecks so they are consistent and more useful

---

src/main/resources/config/config.yaml

- Set default Rate limiter to 25/second for now since the current 3/second is very strict and there is no need.
- Any dev/webops

PP-571 Relax rate limiter default values

---

src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/filter/LoggingFilter.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/resources/config/config.yaml
src/test/java/uk/gov/pay/api/filter/LoggingFilterTest.java

Introducing a Logging filter that would log all incoming requests with a prefix. 
This gives us a nice trace of the request in the form of; start->error(if any)->end
Run through a payment journey and you should be able to see start->end logging for each resource hit on the connector.
Any Dev

PP-582 Add logging filter

---

src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/validation/PaymentSearchValidator.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentSearchResultBuilder.java
src/test/java/uk/gov/pay/api/validation/PaymentSearchValidatorTest.java
swagger/swagger.json

We allow the status 'success' to pass through publicapi without failing
validation. The Confirmed/Capture states will be removed after the changes
are applied to SelfService and Connector.
Add success to the list of allowed statuses. Switch some integration tests to 'success' so they will continue to be good tests after confirmed is removed.
_Who should review this pull request:_

PP-541 Begin swap of Confirmed/Captured to Success

---

src/main/java/uk/gov/pay/api/validation/PaymentSearchValidator.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchITest.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchValidationITest.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceITest.java

Remove backwards compatibility with old 'confirmed' and 'captured' states.
_Steps to test or reproduce:_
Fail validation of 'confirmed' and 'captured' states now we moved to 'success'.
A few tests were still using 'confirmed' but this did not affect their function. Correct these too.
_Who should review this pull request:_

PP-541 Remove confirmed / captured backwards compat

---

src/main/java/uk/gov/pay/api/resources/RequestDeniedResource.java
src/test/java/uk/gov/pay/api/it/RequestDeniedResourceITest.java

- When _Naxsi_ triggers a redirect (rule violated), the request to _/request-denied_ will use the same verb as the origin request so added the other verbs for this resource.

PP-800 Support for all supported HTTP verbs in request-denied resource

---

src/main/java/uk/gov/pay/api/model/ChargeFromResponse.java
src/main/java/uk/gov/pay/api/model/Payment.java
src/main/java/uk/gov/pay/api/model/PaymentForSearchResult.java
src/main/java/uk/gov/pay/api/model/PaymentWithAllLinks.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/validation/PaymentRequestValidator.java
src/main/java/uk/gov/pay/api/validation/PaymentSearchValidator.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchITest.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchValidationITest.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceITest.java
src/test/java/uk/gov/pay/api/it/ResourcesFiltersITest.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentSearchResultBuilder.java
src/test/java/uk/gov/pay/api/utils/ConnectorMockClient.java
src/test/java/uk/gov/pay/api/validation/PaymentSearchValidatorTest.java

* pay-connector is already returning the `email` field, so we just capture that field and pass it accross to the client.    
* The email will do a partial and full match.
* Amending the unit tests for search charges by email
_Steps to test or reproduce:_
```
cd $WORKSPACE
msl reset && msl -a up && ./run-endtoend.sh

PP-864 Allow the ability to search charges by email 

---

src/main/java/uk/gov/pay/api/model/ChargeFromResponse.java
src/main/java/uk/gov/pay/api/model/Payment.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceITest.java

* We should not serialize email field from the payment response if it is null
_Steps to test or reproduce:_
```
cd $WORKSPACE
msl reset && msl -a up && ./run-endtoend.sh
```

PP-864 We should not serialize email field if null

---

src/main/java/uk/gov/pay/api/exception/mapper/CancelChargeExceptionMapper.java
src/main/java/uk/gov/pay/api/model/PaymentError.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/test/java/uk/gov/pay/api/it/PaymentsCancelResourceITest.java

Connector has been updated to return 409 CONFLICT when charge cancellation attempted on charge  in lock state. This commit ensures the correct code is passed on to the world.

PP-720 Pass through conflict state from connector

---

src/main/java/uk/gov/pay/api/model/Payment.java
src/test/java/uk/gov/pay/api/model/PaymentTest.java

- Personal information shouldn't be logged. Removed email from Payment.toString() to avoid logging unwanted data to be displayed.

PP-1155 Removed email when logging payments

---

src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/app/config/PublicApiConfig.java
src/main/java/uk/gov/pay/api/model/RefundResponse.java
src/main/java/uk/gov/pay/api/model/RefundsResponse.java
src/main/java/uk/gov/pay/api/resources/PaymentRefundsResource.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/resources/config/config.yaml
src/test/java/uk/gov/pay/api/it/PaymentResourceITestBase.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchITest.java
src/test/resources/config/test-config.yaml

PP-1172 Make publicapi ignore its Host: header, instead always return canonical URLs with a base read from the environment provided by ansible.
See https://github.com/alphagov/pay-ansible/commit/dc031a1abe96d2f4a14dc0b2180bb962b8bdd79c

PP-1172 Make publicapi ignore its Host: header

---

README.md
pom.xml
src/main/java/uk/gov/pay/api/exception/mapper/CreateRefundExceptionMapper.java
src/main/java/uk/gov/pay/api/json/RequestJsonParser.java
src/main/java/uk/gov/pay/api/model/CreatePaymentRefundRequest.java
src/main/java/uk/gov/pay/api/model/PaymentError.java
src/main/java/uk/gov/pay/api/model/RefundFromConnector.java
src/main/java/uk/gov/pay/api/model/RefundResponse.java
src/main/java/uk/gov/pay/api/model/RefundsFromConnector.java
src/main/java/uk/gov/pay/api/model/RefundsResponse.java
src/main/java/uk/gov/pay/api/resources/PaymentRefundsResource.java
src/test/java/uk/gov/pay/api/it/PaymentRefundsResourceITest.java
src/test/java/uk/gov/pay/api/it/PaymentsRefundsResourceAmountValidationITest.java
src/test/java/uk/gov/pay/api/utils/ConnectorMockClient.java
swagger/swagger.json

_As a client that needs to execute a refund
Then it will always need to pass the "Total Refund Amount Available" with every Refund request.
And the refund should only go ahead if the "Total Refund Amount Available" in the DB matches the "Total Refund Amount Available" in the body request._
The idea is from preventing a user from submitting a refund request by pressing the form submit button twice in quick succession and from two members of staff submitting the same refund amount for the same payment.
This would result in the refund attempted twice. If the request was for a partial refund then it's possible that double the intended amount would be refunded.
Furthermore, it is also possible to request a refund twice in quick succession via the …

PP-1224 Including `refund amount available` parameter for every refund

---

README.md
src/main/java/uk/gov/pay/api/model/Address.java
src/main/java/uk/gov/pay/api/model/CardDetails.java
src/main/java/uk/gov/pay/api/model/ChargeFromResponse.java
src/main/java/uk/gov/pay/api/model/Payment.java
src/main/java/uk/gov/pay/api/model/PaymentForSearchResult.java
src/main/java/uk/gov/pay/api/model/PaymentWithAllLinks.java
src/test/java/uk/gov/pay/api/it/PaymentRefundsResourceITest.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchITest.java
src/test/java/uk/gov/pay/api/it/PaymentsRefundsResourceAmountValidationITest.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceITest.java
src/test/java/uk/gov/pay/api/it/ResourcesFiltersITest.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentSearchResultBuilder.java
src/test/java/uk/gov/pay/api/model/PaymentTest.java
src/test/java/uk/gov/pay/api/utils/ConnectorMockClient.java
swagger/swagger.json

- Enabled card details in get payments and search payments api's
- removed top level `card_brand` attribute as it is now available in `card_details`. However keeping support for the root level `card_brand` attribute for existing clients. Marked it as Deprecated in documentation, to force teams to use the new API.

PP-1282 expose payment card details in payment api's

---

README.md
src/main/java/uk/gov/pay/api/model/ChargeFromResponse.java
src/main/java/uk/gov/pay/api/model/Payment.java
src/main/java/uk/gov/pay/api/model/PaymentForSearchResult.java
src/main/java/uk/gov/pay/api/model/PaymentWithAllLinks.java
src/main/java/uk/gov/pay/api/model/SettlementSummary.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/utils/DateTimeUtils.java
src/test/java/uk/gov/pay/api/it/PaymentRefundsResourceITest.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchITest.java
src/test/java/uk/gov/pay/api/it/PaymentsRefundsResourceAmountValidationITest.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceITest.java
src/test/java/uk/gov/pay/api/it/ResourcesFiltersITest.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentSearchResultBuilder.java
src/test/java/uk/gov/pay/api/utils/ConnectorMockClient.java
src/test/java/uk/gov/pay/api/utils/DateTimeUtilsTest.java
swagger/swagger.json

- `settlement_summary` is a structure coming from connector, containing
two fields: `capture_submit_time`, which is the timestamp of us
receiving the payment gateway's notification of a capture, and
`captured_date`, which is the date contained in the notification
payload.
- if a charge has not been captured, both those dates  could potentially
be empty; connector would be returning null.
In this case, public api would not show at all the keys in the json structure
- `settlement_summary` is serialised in calls to `/payments` and
`/payments/{id}` endpoints
_Steps to test or reproduce:_

PP-1517 Pass settlement_summary through PublicApi

---

pom.xml
src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/auth/Account.java
src/main/java/uk/gov/pay/api/auth/AccountAuthenticator.java
src/main/java/uk/gov/pay/api/resources/PaymentRefundsResource.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/test/java/uk/gov/pay/api/it/PaymentResourceITestBase.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchITest.java

- Upgraded the following libraries:
- `Dropwizard` from version `0.8.1` to `1.0.6`.
- `commons-validator` from version `1.5.1` to `1.6`.
- `io.dropwizard.metrics` from version `3.1.2` to `3.2.0`.
- `com.fasterxml.jackson.datatype` from version `2.8.6` to `2.8.7`.
- `com.fasterxml.jackson.core` from version `2.8.6` to `2.8.7`.
- `black.door` from version `v1r3t1` to `v1r4t0`
- `httpclient` from version `4.5.2` to `4.5.3`
- `jersey-common` from version `2.23.2` to `2.25.1`
- `jersey-media-jaxb` from version `2.23.2` to `2.25.1`
- The implementation of `Dropwizard Authentication` has undergone a major overhaul since version 0.9.x of `Dropwizard` introducing a new interface for `Authenticators` and the use of a `Principal`. The code was refactored to …

[REVIEW ONLY] PP-1753 Upgraded project dependencies

---

src/test/resources/config/test-config.yaml

in order to avoid port clashes if multiple test runs are happening in parallel
a setting of `0` causes a random free port to be allocated

Allocate free port in integration tests

---

src/main/java/uk/gov/pay/api/model/CreatePaymentRequest.java
src/main/java/uk/gov/pay/api/model/Payment.java

Some services put personally-identifiable information into payment descriptions. In order to avoid this ending up in the logs, exclude the description when logging payment details.

PP-1940 Don’t log payment descriptions because they may contain PII

---

src/main/java/uk/gov/pay/api/model/SettlementSummary.java
swagger/swagger.json

If we don't get an acknowledgement from a payment gateway of a capture order,
but that gateway does successfully process the order, then a payment can be
`CAPTURED` but `capture_submit_time` will be null.

PP-2057 document that capture_submit_time can be null

---

docs/api_specification.md
src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/app/config/PublicApiConfig.java
src/main/java/uk/gov/pay/api/validation/PaymentRequestValidator.java
src/main/resources/config/config.yaml
src/test/java/uk/gov/pay/api/it/PaymentsResourceDescriptionValidationITest.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceITest.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceReferenceValidationITest.java
src/test/java/uk/gov/pay/api/it/ResourcesFiltersITest.java
src/test/java/uk/gov/pay/api/validation/PaymentRequestValidatorTest.java
src/test/resources/config/test-config.yaml

We need to return client error HTTP status code in case we submit `return_url` which is non-HTTPS (currently `NAXSI` is returning `404` in case we submit non-HTTPS url).
We use `422 Unprocessable Entity` for client errors.
- Added `allowHttpForReturnUrl` setting (default is `false`) which enables or disables "https only" check for `return_url` request parameter
- Added related tests in `PaymentRequestValidatorTest` and modified existing ones
- Updated documentation

PP-2514 Enable https validation for return url

---

src/main/java/uk/gov/pay/api/resources/PaymentsResource.java

With the upcoming change in Connector transaction reporting to include refunds, there is the need the distinguish between transaction types 'refund' and 'charge'.
Calls from PublicAPI to Connector are now made to default to request only transactions of type 'charge' when searching for transactions
Search for transactions and see the query parameters has 'transactionType ' as part of the request parameters to Connector

PP-2515 default transactionType='charge' to connector calls

---

pom.xml

Bumped up version of `com.fasterxml.jackson.datatype:jackson-datatype-jsr310` from `2.8.7` to `2.8.10` to address the vulnerabilities below:
- Arbitrary Code Execution
Vulnerable module: commons-collections:commons-collections
Introduced through: commons-validator:commons-validator@1.6
- Deserialization of Untrusted Data
Vulnerable module: com.fasterxml.jackson.core:jackson-databind
Introduced through: black.door:hate@v1r4t0 and com.fasterxml.jackson.datatype:jackson-datatype-jsr310@2.8.7
See https://snyk.io/org/govuk-pay/project/b3895a37-37e2-40e5-ac85-5df4fb96cab7

PP-2636 Address Deserialization of Untrusted Data vulnerability (CVE-2017-7525)

---

pom.xml

In addition to pinning `commons-collections` to version _3.2.2_, we also need to explicitly exclude version _3.2.1_ from transient dependency of `commons-validator`.
It is not strictly needed as per se but Snyk is reporting false alarms and we need to suppress those.
pom snippets:
```
<dependency>
<groupId>commons-validator</groupId>
<artifactId>commons-validator</artifactId>
<version>1.6</version>
<exclusions>
<exclusion>
<groupId>commons-collections</groupId>
<artifactId>commons-collections</artifactId>
</exclusion>
</exclusions>
</dependency>
```
....
```
<dependency>
<groupId>commons-collections</groupId>
<artifactId>commons-collections</artifactId>
<version>3.2.2</version>
</dependency>
```

PP-2117 Upgrade commons-collections to 3.2.2

---

pom.xml

In addition to upgrading com.fasterxml.jackson.core:jackson-datatype we also need to exclude version 2.7.5 from a transient dependency (black.door:hate@v1r4t0). It is not strictly needed as per se but Snyk is reporting false alarms and we need to suppress those.
```
<dependency>
<groupId>black.door</groupId>
<artifactId>hate</artifactId>
<version>v1r4t0</version>
<exclusions>
<exclusion>
<groupId>com.fasterxml.jackson.core</groupId>
<artifactId>jackson-databind</artifactId>
</exclusion>
<exclusion>
<groupId>com.fasterxml.jackson.datatype</groupId>
<artifactId>jackson-datatype-jsr310</artifactId>
</exclusion>
<exclusion>
<groupId>com.fasterxml.jackson.datatype</groupId>
<artifactId>jackson-datatype-jdk8</artifactId>
</exclusion>
</exclusions>
</dependency>
```

PP-2636 adding exclusion to pom file for jackson-datatype

---

src/main/java/uk/gov/pay/api/model/links/PaymentWithAllLinks.java

- `PaymentWithAllLinks` has been changed to _have_ payment, instead of _being_ a payment - the `toString()` method has to change accordingly, as we use that to log information about a payment.
- Without the `toString()` method we end up logging things like
```
Payment returned - [ uk.gov.pay.api.model.links.PaymentWithAllLinks@11c97822 ]
```

PP-2888 Override toString() method of PaymentWithAllLinks

---

src/main/resources/config/config.yaml
src/test/resources/config/test-config.yaml

At the moment we're not logging the request id for this component, so we're not able to correlate logs to each request.

PP-3129 Add request id to log format

---

Jenkinsfile

- deploy should deploy to ecs
- regular deploy shouldn't tag or run tests
- ecs deploy should tag and run tests
solo @tlwr

PP-3094: publicapi should deploy to ecs

---

pom.xml

* Upgraded Dropwizard 1.0.6 to version 1.2.2:
* Since version 1.1.0, Dropwizard dropped dependency to `org.mockito`intentional. The Mockito dependency was only accidentally Maven's "compile" scope and has since moved into the correct "test" scope. See https://github.com/dropwizard/dropwizard/pull/1851 for details. Since Dropwizard itself has no dependency on Mockito except for its internal tests, a dependency to the latest stable version 2.15.0 had to be added to the project explicitly.  Same goes for Guava which was explicitly added at version 24.0-jre.
* Removed explicit dependency of jersey version 2.25.1 which is not anymore needed since Dropwizard 1.2.2 already ships with that version. Note: jersey 2.25.1 is reported to have a medium vulnerability “XML Entity Expansion (XEE)” which …

PP-3312/upgrade dropwizard v1.2.x

---

pom.xml

* Upgraded the following dependencies:
* `swagger-jersey2-jaxrs` v1.5.12 -> v1.5.18
* `mockserver-netty` v3.10.4 -> v5.3.0
* `mockserver-client-java` v3.10.4 -> v5.3.0
* `logback-classic` v1.2.2 -> v1.2.3
* `logback-access` v1.2.2 -> v1.2.3
* `commons-codec` v1.10 -> v1.11
* `metrics-graphite` v3.1.2 -> v4.0.2
* `httpclient` v4.5.3 -> v4.5.5
* `json-path-assert` v2.2.0 -> 2.4.0
* `gson` v2.8.0 -> v2.8.2
metrics-graphite 3.1.2 had been pinned down for a while due to an an issue which changed the way metrics paths were sanitised: https://github.com/dropwizard/metrics/pull/1098
Since then the problem has been addressed in more recent versions and it is now safe to rollout version 4.0.2. 
Tested locally using Telegraf, metrics are still been sent.

PP-3312 Upgraded remaining dependencies

---

src/main/java/uk/gov/pay/api/app/PublicApi.java

The root cause of the issue is a bug in jdk as this method is not thread-safe:
http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/javax/net/ssl/HttpsURLConnection.java#HttpsURLConnection.getDefaultSSLSocketFactory%28%29
This method is not thread-safe, as multiple threads can get different instances, a double-checked locking should be added in order to make it thread safe.
```
public static SSLSocketFactory getDefaultSSLSocketFactory() {
if (defaultSSLSocketFactory == null) {
defaultSSLSocketFactory = (SSLSocketFactory)SSLSocketFactory.getDefault();
}
return defaultSSLSocketFactory;
}
```
The code that invokes this method in jersey client is in `HttpUrlConnector`:
```
if (HttpsURLConnection.getDefaultSSLSocketFactory() == suc.getSSLSocketFactory()) {
// …
```

PP-3219 Try a better approach to fix issue with jersey client.

---

src/main/java/uk/gov/pay/api/validation/URLValidator.java
src/test/java/uk/gov/pay/api/validation/URLValidatorTest.java

One of our partners needed to use an ".internal" TLD for the `return_url` during their testing. This PR allows that.
Actually, this changes the `URLValidator` altogether, which may be used potentially for something else than just return_url. However, for now, it seems that is not the case. And, even if that changes in the future, it should not be an issue.
This implementation uses a static initialiser in an enum, which may not be that common. However, we needed that because the `DomainValidator.updateTLDOverride()` method needs to be called before any call to `getInstance()`. Source: https://commons.apache.org/proper/commons-validator/apidocs/org/apache/commons/validator/routines/DomainValidator.html#updateTLDOverride%28org.apache.commons.validator.routines.DomainValidator.ArrayType,%20jav …

PP-3337 Allowing .internal TLD in return_url

---

src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/validation/PaymentSearchValidator.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchValidationITest.java
src/test/java/uk/gov/pay/api/matcher/ValidationExceptionMatcher.java
src/test/java/uk/gov/pay/api/validation/PaymentSearchValidatorTest.java
swagger/swagger.json

When you do a search there is a parameter to specify the number of
results returned called display_size. Currently this defaults to 500
but does not have a max value. As we have seen the speed of searches is
very dependent on the number of results returned we want limit how big
this can be. Have limited display_size to be 500 or less.

Limit search to 500 transactions

---

Jenkinsfile
pom.xml

Add the pact maven plugin to enable publishing of pacts.
Set trimSnapshot to true in the pom.xml as the pact broker has issues parsing
SNAPSHOT versions (even though we aren't using SNAPSHOT versions but rather the
git commit sha, but just in case). See
https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-provider-maven#publishing-pact-files-to-a-pact-broker.
For some reason the pact broker homepage (https://pact-broker-test.cloudapps.digital/) doesn't show the latest publicapi pact that was published. But the latest version that was published from the https://build.ci.pymnt.uk/job/pay-publicapi/job/PR-178/3 is definitely there at https://pact-broker-test.cloudapps.digital/hal-browser/browser.html#/pacts/provider/direct-debit-connector/consumer/publicapi/version/1fb63718d85705ab17d2e032e8 …

PP-3841: Publish pacts

---

src/main/java/uk/gov/pay/api/resources/HealthCheckResource.java
src/main/java/uk/gov/pay/api/resources/PaymentRefundsResource.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/resources/RequestDeniedResource.java

the [`@Timed` annotation](https://www.dropwizard.io/1.3.2/docs/manual/core.html#man-core-resources-metrics)
allows an endpoint to emit timing metrics of its use. Having timings on public api for each endpoint will help
us in diagnosing any performance issues
with @oswaldquek

BAU: Add timing annotation to all endpoints

---

pom.xml
src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/app/config/PublicApiModule.java
src/main/java/uk/gov/pay/api/auth/AccountAuthenticator.java
src/main/java/uk/gov/pay/api/filter/AuthorizationValidationFilter.java
src/main/java/uk/gov/pay/api/filter/RateLimiterFilter.java
src/main/java/uk/gov/pay/api/resources/HealthCheckResource.java
src/main/java/uk/gov/pay/api/resources/PaymentRefundsResource.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/test/java/uk/gov/pay/api/auth/AccountAuthenticatorTest.java
src/test/java/uk/gov/pay/api/filter/AuthorizationValidationFilterTest.java

Start using Guice to instantiate objects added to the environment in the `PublicApi` class.
This will make it easier to extract some of the logic in the `*Resource` classes to separate service classes (because we will be able to use Guice to inject their dependencies).
with @heathd

Guice publicapi

---

src/test/java/uk/gov/pay/api/it/DirectDebitPaymentTest.java
src/test/resources/pacts/publicapi-direct-debit-connector.json
swagger/swagger.json

While running the publicapi-direct-debit-connector pact for real against the
direct-debit-connector service for real, I noticed some of the interactions
defined here are incorrect. For example, in the call to
`/v1/api/accounts/GATEWAY_ACCOUNT_ID/charges` (on the direct debit connector),
the email and payment provider are not returned in the response body.
Also add a provider state and correct [regex] matchers where appropriate as
some of the data is dynamic. For example, the payment requested external id and
charge token id (UUID) are generated.
@oswaldquek

Pp 3842 publicapi dd connector provider test

---

src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/app/config/RestClientConfig.java
src/main/java/uk/gov/pay/api/auth/Account.java
src/main/java/uk/gov/pay/api/model/CardPayment.java
src/main/java/uk/gov/pay/api/model/DirectDebitPayment.java
src/main/java/uk/gov/pay/api/model/PaymentState.java
src/main/java/uk/gov/pay/api/model/links/Link.java
src/main/java/uk/gov/pay/api/model/links/PaymentWithAllLinks.java
src/main/java/uk/gov/pay/api/model/links/PostLink.java
src/main/java/uk/gov/pay/api/resources/PaymentRefundsResource.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/service/ConnectorUriGenerator.java
src/main/java/uk/gov/pay/api/service/CreatePaymentService.java
src/main/java/uk/gov/pay/api/service/PublicApiUriGenerator.java
src/main/java/uk/gov/pay/api/validation/PaymentSearchValidator.java
src/test/java/uk/gov/pay/api/auth/AccountAuthenticatorTest.java
src/test/java/uk/gov/pay/api/service/CreatePaymentServiceTest.java
src/test/resources/pacts/publicapi-connector.json

with @heathd 
Extract the body of the 'create payment' api call into a service object. We
followed these principles:
1. 'presentation' concerns such as serialisation of the response and generation
of headers remain in the Resource
2. issuing the call to connector and parsing the response is done in the service object
We also extracted `PublicApiUriGenerator` and `ConnectorUriGenerator` which are
responsible for generating URIs relating to PublicApi and Connector
respectively. They get the dropwizard app configuration injected to their
constructors.
Finally we created a Pact contract test for the `CreatePaymentService`. Where
possible we've used real objects where they are simple value objects, rather
than using mocks.
The url paths are almost exclusively used only in one place, which is …

Extract create payments service

---

src/main/java/uk/gov/pay/api/model/directdebit/agreement/AgreementError.java
src/test/java/uk/gov/pay/api/model/directdebit/agreement/AgreementErrorTest.java

To be used in Agreement-related api calls. Most of the errors might overlap with card payments, but we still keep the objects separate to allow us to diverge at will.

PP-3677 Add AgreementError domain object

---

pom.xml
src/test/java/uk/gov/pay/api/it/directdebit/pact/DirectDebitPaymentTest.java
src/test/java/uk/gov/pay/api/service/CreatePaymentServiceTest.java

PP-3845 is about checking pact compatibility between publicapi and
direct-debit-connector; however we currently also publish pacts for publicauth
and connector, and these have no provider tests written for them yet, and
therefore no pact verifications. We need to disable publishing them so the
pact-broker has no knowledge of them and can check pact compatibility between
publicapi and direct-debit-connector only.
@oswaldquek

PP-3845: Don't publish pacts for which there are no provider tests

---

src/test/resources/pacts/publicapi-connector-create-payment.json

The pact requires there to be a gateway account under which
charge will be created.

BAU Add state to publicapi connector pact

---

src/test/resources/pacts/publicapi-connector-create-payment.json

Stipulating the form of expected links seems rather pointless, and probably too
restrictive from a contract point of view. PublicApi should not care if we
completely change the front end url, for example.

Make pact with connector less restrictive

---

src/main/java/uk/gov/pay/api/model/IPaymentSearchPagination.java
src/main/java/uk/gov/pay/api/model/directdebit/DDPaymentState.java
src/main/java/uk/gov/pay/api/model/directdebit/search/DDSearchResponse.java
src/main/java/uk/gov/pay/api/model/directdebit/search/DDTransactionForSearch.java
src/main/java/uk/gov/pay/api/model/directdebit/search/DDTransactionFromResponse.java
src/main/java/uk/gov/pay/api/model/directdebit/search/links/DDTransactionLinksForSearch.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/service/ConnectorUriGenerator.java
src/main/java/uk/gov/pay/api/service/PaymentSearchService.java
src/main/java/uk/gov/pay/api/validation/PaymentSearchValidator.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchITest.java
src/test/java/uk/gov/pay/api/it/ResourcesFiltersITest.java
src/test/java/uk/gov/pay/api/service/PaymentSearchServiceTest.java
src/test/java/uk/gov/pay/api/validation/PaymentSearchValidatorTest.java
src/test/resources/pacts/publicapi-direct-debit-connector-search-by-mandate-three-results.json

Refactor `PaymentsResource` to use `PaymentSearchService`. This is needed so we can implement `Pact` test(s).
Implement Direct Debit search. Use pact testing to test the DD search instead of mocks.
Search is based on `Account` type. This is needed as the nature of the backend response is differ for connector and direct-debit-connector. Instead of trying to make existing `PaymentForSearchResult` generic we opted to separate the searches and thus introduced `DDSearchResponse`.
- introduce `IPaymentSearchPagination` for simplified pagination building.
- add dd search to PaymentSearchService
- add relevant PoJos (`DDSearchResponse`, `DDTransactionFromResponse`,  `DDTransactionForSearch`, etc)
- add Response process from back end responses
- add Pact test

PP-3679 Add DD search by agreement to PaymentResource

---

pom.xml

Upgrade Dropwizard from 1.2.5 to 1.2.8
This upgrades Jackson from 2.9.5 to 2.9.6 and Jetty from 9.4.10 to 9.4.11

PP-3933: Upgrade Dropwizard from 1.2.5 to 1.2.8

---

src/main/java/uk/gov/pay/api/model/RefundSummary.java

- We are going to add `user_external_id` to the Refund Summary in connector, but
we don't necessarily want to serialise that (as of now, at least) in publicapi

PP-3493 Ignore unknown properties in RefundSummary

---

src/main/java/uk/gov/pay/api/app/config/PublicApiModule.java
src/main/java/uk/gov/pay/api/app/config/RateLimiterConfig.java
src/main/java/uk/gov/pay/api/filter/RateLimiter.java
src/main/java/uk/gov/pay/api/filter/RateLimiterFilter.java
src/main/resources/config/config.yaml
src/test/java/uk/gov/pay/api/filter/RateLimiterFilterTest.java
src/test/java/uk/gov/pay/api/filter/RateLimiterTest.java
src/test/resources/config/test-config.yaml

Added new method 'auditRateOf' to RateLimiterFilter to log no of transactions/second for service. This will help to find out optimal rate against current rate of `25tx/s` for each node .  
Does not effect current functionality but does additional logging if `tx/s > 4`
We have chosen `4 tx/s` from inspecting logs to see what kind of load a single service generates. MTP can generate up to about `7/8 tx/s`, but since this will be spread over 3 nodes, the 'normal' rate limit per service will be `12 tx/s`, which should be fine. However there may be cases where the effective limit becomes equal to the limit per node (i.e. if all requests for a particular service were directed at one node). Therefore the purpose of auditing the limit in this manner is to establish whether, and how often, a limit …

PP-4005 Rate filter audit

---

src/main/java/uk/gov/pay/api/filter/RateLimiterFilter.java
src/test/java/uk/gov/pay/api/filter/RateLimiterFilterTest.java

In order to more precisely rate limit the different parts of
public api, this commit passes a concatenation of method and
api key as rate limiting key. This will mean GET requests cannot impinge
on POSTs, so if a service does a batch of GETs it won't block the
mor eimportant process of creating new payments. This is a small
change in right direction, rather than a total solution.
We may want to set different rates for POSTs and GETs at some point,
but this is not currently required.

PP-4005 Segment rate limit by method

---

pom.xml
src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/app/config/PublicApiConfig.java
src/main/java/uk/gov/pay/api/app/config/PublicApiModule.java
src/main/resources/config/config.yaml
src/test/java/uk/gov/pay/api/it/CachingAuthenticatorTest.java
src/test/java/uk/gov/pay/api/it/TestPublicApi.java
src/test/java/uk/gov/pay/api/it/TestPublicApiModule.java
src/test/resources/config/test-config.yaml

Enables authenticator caching in public api, so that repeated requests to public-auth can be avoided if bearer token is already authenticated and within cache time limit.

PP-4075 - Cache request for publicauth in publicapi

---

src/main/java/uk/gov/pay/api/model/links/directdebit/DirectDebitEvent.java
src/main/java/uk/gov/pay/api/resources/DirectDebitEventsResource.java
src/main/java/uk/gov/pay/api/validation/DirectDebitEventSearchValidator.java
src/test/java/uk/gov/pay/api/it/GetDirectDebitEventsTest.java
src/test/java/uk/gov/pay/api/validation/DirectDebitEventSearchValidatorTest.java

- Added validation for display_size, future work may want to refactor validation
into a common reusable class. Also may be prudent to refactor ValidationException to be less payment specific in future.
- Separated serialization and deserialization for mandateId and transactionId
on DDEvent to permit correct setting of names in json.
- Created and updated tests to check for correct naming convention on DDEvent and validation.

PP-3680 Adding validation for display_size

---

src/main/java/uk/gov/pay/api/model/links/directdebit/DirectDebitEvent.java
src/test/java/uk/gov/pay/api/it/GetDirectDebitEventsTest.java

- Also return null for empty elements rather than omitting them e.g. links.payment

PP-3680 Changed event_external_id to event_id in DD Event Search result.

---

README.md
src/main/java/uk/gov/pay/api/app/config/PublicApiModule.java
src/main/java/uk/gov/pay/api/app/config/RateLimiterConfig.java
src/main/java/uk/gov/pay/api/filter/RateLimiter.java
src/main/java/uk/gov/pay/api/filter/RateLimiterFilter.java
src/main/resources/config/config.yaml
src/test/java/uk/gov/pay/api/filter/RateLimiterFilterTest.java
src/test/java/uk/gov/pay/api/filter/RateLimiterTest.java
src/test/resources/config/test-config.yaml

Changes to set different rate limits for GET and POST methods. 
GET requests : revert back to 25 requests/second/node
POST requests : keep current limit of 5 request/second/node

PP 4005 - Separate rate limits for GET and POST

---

src/main/java/uk/gov/pay/api/app/PublicApi.java

Removed redis from health checks as it is not a mandatory dependency.

PP-4036 Unregister redis from health check

---

src/main/java/uk/gov/pay/api/filter/ratelimit/RateLimiter.java
src/main/java/uk/gov/pay/api/filter/ratelimit/RedisRateLimiter.java
src/main/resources/config/config.yaml

Jedis doesn't return connection to the connection pool automatically. The connection need to be closed explicitly to return to the pool. Try with resources on Jedis will invoke Jedis.close() that actually returns connection to pool (only when Jedis is obtained from pool which is the case ).

PP-4036 Fix - Return redis connection to pool

---

src/main/java/uk/gov/pay/api/json/RequestJsonParser.java
src/main/java/uk/gov/pay/api/model/CreatePaymentRequest.java
src/test/java/uk/gov/pay/api/json/RequestJsonParserTest.java

- Add optional language to `CreatePaymentRequest`
- Deserialise the `"language"` field from the JSON into the object, checking that it’s a string and returning an P0102 “Invalid attribute value” error if it isn’t
- As language is optional, don’t return a P0101 “Missing mandatory attribute” error if the JSON explicitly contains `"language": null`, instead return a P0102 error
- No validation that the field actually contains a supported language yet
- The language in not yet sent to connector when creating the payment
with @DanailMinchev

PP-4095 Add language to CreatePaymentRequest object

---

pom.xml
src/main/java/uk/gov/pay/api/app/config/PublicApiModule.java
src/main/java/uk/gov/pay/api/json/CreatePaymentRequestDeserializer.java
src/main/java/uk/gov/pay/api/json/RequestJsonParser.java
src/main/java/uk/gov/pay/api/model/CreatePaymentRequest.java
src/main/java/uk/gov/pay/api/model/ValidCreatePaymentRequest.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/service/CreatePaymentService.java
src/main/java/uk/gov/pay/api/validation/LanguageValidator.java
src/main/java/uk/gov/pay/api/validation/PaymentRequestValidator.java
src/test/java/uk/gov/pay/api/it/validation/PaymentsResourceLanguageValidationITest.java
src/test/java/uk/gov/pay/api/json/CreatePaymentRequestDeserializerTest.java
src/test/java/uk/gov/pay/api/resources/PaymentsResourceCreatePaymentTest.java
src/test/java/uk/gov/pay/api/service/CreatePaymentServiceTest.java
src/test/java/uk/gov/pay/api/validation/PaymentRequestValidatorTest.java

- Reject create payment requests with a `"language"` that is not `"en"` or `"cy"`
- After validating a `CreatePaymentRequest` object, convert it to a new `ValidCreatePaymentRequest` object for the rest of its time in the system — because we know its fields are valid, we can use more specific types like the `SupportedLanguage` enum rather than JSON-compatible types like String
- Tests, lots of tests
- Still not actually sending the language to connector when creating a payment
with @DanailMinchev

PP-4095 Validate language in create payment request

---

src/main/java/uk/gov/pay/api/model/CardPayment.java
src/main/java/uk/gov/pay/api/model/ChargeFromResponse.java
src/main/java/uk/gov/pay/api/model/ValidCreatePaymentRequest.java
src/main/java/uk/gov/pay/api/model/links/PaymentWithAllLinks.java
src/main/java/uk/gov/pay/api/model/search/card/PaymentForSearchResult.java
src/main/java/uk/gov/pay/api/service/CreatePaymentService.java
src/main/java/uk/gov/pay/api/utils/CustomSupportedLanguageDeserializer.java
src/test/java/uk/gov/pay/api/it/CreatePaymentITest.java
src/test/java/uk/gov/pay/api/it/GetPaymentITest.java
src/test/java/uk/gov/pay/api/it/PaymentRefundsResourceITest.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchITest.java
src/test/java/uk/gov/pay/api/it/ResourcesFilterLocalRateLimiterITest.java
src/test/java/uk/gov/pay/api/it/ResourcesFilterRateLimiterITest.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentSearchResultBuilder.java
src/test/java/uk/gov/pay/api/it/validation/PaymentsRefundsResourceAmountValidationITest.java
src/test/java/uk/gov/pay/api/json/CreatePaymentRequestDeserializerTest.java
src/test/java/uk/gov/pay/api/model/PaymentTest.java
src/test/java/uk/gov/pay/api/resources/PaymentsResourceCreatePaymentTest.java
src/test/java/uk/gov/pay/api/service/CreatePaymentServiceTest.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java
src/test/resources/pacts/publicapi-connector-create-payment-with-language-welsh.json
src/test/resources/pacts/publicapi-connector-create-payment.json

When processing a create card payment request, send the supplied `"language"` to connector if it passes validation i.e. is `"en"` (English) or `"cy"` (Welsh). If no `"language"` is supplied, do not include a `"language"` field in the request to connector (connector will default to English).
When retrieving a card payment via either the `/v1/payments/{paymentId}` endpoint, the `/v1/payments` search endpoint, or in response to a create payment request, include a `"language" : "en"` or `"language": "cy"` field depending on what connector sends us.
Commits:
1. Make getters in `ValidCreatePaymentRequest` return `Optional`s if appropriate
2. Include `"language"` field when returning a card payment (updates existing create payment Pact test)
3. Send `"language"` field to connector when creating …

PP-4095 Send language to and return language from connector

---

pom.xml
src/main/java/uk/gov/pay/api/filter/RateLimiterFilter.java
src/main/java/uk/gov/pay/api/model/CardPayment.java
src/main/java/uk/gov/pay/api/model/PaymentState.java
src/main/java/uk/gov/pay/api/model/ValidCreatePaymentRequest.java
src/main/java/uk/gov/pay/api/resources/AgreementsResource.java
src/main/java/uk/gov/pay/api/resources/DirectDebitEventsResource.java
src/main/java/uk/gov/pay/api/resources/PaymentRefundsResource.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/resources/error/ApiErrorResponse.java
swagger/swagger.json

PP-4073: limit which classes are exported to swagger docs. 
-  Configured swagger-maven-plugin to exclude direct debit related endpoints and fields (as we don't want to publish these yet) while generating api docs.
**_with @heathd_** 
PP-4073: Add 429 response code to resource endpoints
- Added 429 response code to all applicable endpoints.
swagger.json file generated should now 
- exclude direct debit related api documentation and 
- contain 429 responses for all endpoints published

PP-4073: 429 response code and specify classes to use for swagger.json

---

src/main/java/uk/gov/pay/api/app/config/PublicApiModule.java
src/main/java/uk/gov/pay/api/app/config/RateLimiterConfig.java
src/main/java/uk/gov/pay/api/filter/RateLimiterFilter.java
src/main/java/uk/gov/pay/api/filter/ratelimit/LocalRateLimiter.java
src/main/java/uk/gov/pay/api/filter/ratelimit/RateLimiter.java
src/main/resources/config/config.yaml
src/test/java/uk/gov/pay/api/filter/RateLimiterFilterTest.java
src/test/java/uk/gov/pay/api/filter/ratelimit/LocalRateLimiterTest.java
src/test/resources/config/test-config.yaml

This was a temporary piece of functionality to help us set a sensible rate
limit. We no longer need it. If we do require it in furure it is simple to
re-implement, and it would neeed to be redone to take account of new Redis
backed rate limiting anyway.

Remove rate limit audit

---

src/main/java/uk/gov/pay/api/model/CardPayment.java
src/main/java/uk/gov/pay/api/model/ChargeFromResponse.java
src/main/java/uk/gov/pay/api/model/links/PaymentWithAllLinks.java
src/main/java/uk/gov/pay/api/model/search/card/PaymentForSearchResult.java
src/main/java/uk/gov/pay/api/service/CreatePaymentService.java
src/test/java/uk/gov/pay/api/it/CreatePaymentITest.java
src/test/java/uk/gov/pay/api/it/GetPaymentITest.java
src/test/java/uk/gov/pay/api/it/PaymentRefundsResourceITest.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchITest.java
src/test/java/uk/gov/pay/api/it/ResourcesFilterLocalRateLimiterITest.java
src/test/java/uk/gov/pay/api/it/ResourcesFilterRateLimiterITest.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentSearchResultBuilder.java
src/test/java/uk/gov/pay/api/it/validation/PaymentsRefundsResourceAmountValidationITest.java
src/test/java/uk/gov/pay/api/resources/PaymentsResourceCreatePaymentTest.java
src/test/java/uk/gov/pay/api/service/CreatePaymentServiceTest.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java
src/test/resources/pacts/publicapi-connector-create-payment-with-delayed-capture-true.json
swagger/swagger.json

- Add `delayedCapture` property to the card model
- Make the call to connector include the `delayed_capture` field if appropriate
- Ensure the Public API endpoints for creating payments and retrieving payments return the `delayed_capture` field
The next PR will have Pact tests
with @SandorArpa

PP-4106 Delayed capture connector integration

---

Jenkinsfile

- Pact tests were temporary disabled to fix connector master (see https://github.com/alphagov/pay-publicapi/pull/259), now we can uncomment `runPactProviderTests` lines

PP-4106 Enable Pact tests

---

pom.xml
src/main/java/uk/gov/pay/api/model/ValidCreatePaymentRequest.java
swagger/swagger.json

API docs
- **Fix**: updated field name 'returnUrl' to 'return_url' (create payment API)
- Added description and examples for **ValidateCreatePaymentRequest** fields

BAU : fix create payment api field name

---

src/main/java/uk/gov/pay/api/model/search/SearchPaymentsBase.java
src/main/java/uk/gov/pay/api/model/search/card/SearchCardPayments.java
src/main/java/uk/gov/pay/api/model/search/directdebit/SearchDirectDebitPayments.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/service/PaymentSearchService.java
src/main/java/uk/gov/pay/api/validation/ExactLengthValidator.java
src/main/java/uk/gov/pay/api/validation/NumericValidator.java
src/main/java/uk/gov/pay/api/validation/PaymentSearchValidator.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchITest.java
src/test/java/uk/gov/pay/api/it/ResourcesFilterRateLimiterITest.java
src/test/java/uk/gov/pay/api/it/validation/PaymentResourceSearchValidationITest.java
src/test/java/uk/gov/pay/api/service/CardPaymentSearchServiceTest.java
src/test/java/uk/gov/pay/api/service/DirectDebitPaymentSearchServiceTest.java
src/test/java/uk/gov/pay/api/service/PaymentSearchServiceTest.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java
src/test/java/uk/gov/pay/api/validation/PaymentSearchValidatorTest.java
src/test/resources/pacts/publicapi-connector-search-payment-by-cardholder-name.json
src/test/resources/pacts/publicapi-connector-search-payment-by-first-digits-card-number.json
src/test/resources/pacts/publicapi-connector-search-payment-by-last-digits-card-number.json
swagger/swagger.json

- Added support for searching for first 6 digits and last 4 digits of card number
- Both of those have to be numeric and not empty to be valid. We return a bad request if any of those parameters are invalid. If not specified (ie. `""`) we ignore the query params

PP-4141 Search for first 6 digits and last 4 digits of card number

---

src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/service/CancelPaymentService.java
src/test/java/uk/gov/pay/api/resources/PaymentsResourceCreatePaymentTest.java
src/test/java/uk/gov/pay/api/service/CancelPaymentServiceTest.java
src/test/resources/pacts/publicapi-connector-cancel-payment-with-created-state.json

- add a contract test for cancelling a payment
- refactor code to use a service for cancel payments
- wire in CancelPaymentService
- add pact file
- add pact test
with @cobainc0

PP-4250 FB - add cancel payment contract test

---

src/main/java/uk/gov/pay/api/model/CardPayment.java
src/main/java/uk/gov/pay/api/model/ChargeFromResponse.java
src/main/java/uk/gov/pay/api/model/links/PaymentWithAllLinks.java
src/main/java/uk/gov/pay/api/model/search/card/PaymentForSearchResult.java
src/test/java/uk/gov/pay/api/it/GetPaymentITest.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentSearchResultBuilder.java
src/test/java/uk/gov/pay/api/resources/PaymentsResourceCreatePaymentTest.java
src/test/java/uk/gov/pay/api/service/GetPaymentServiceTest.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java
src/test/resources/pacts/publicapi-connector-get-payment-with-corporate-surcharge.json

- Add pact test for payment with corporate surcharge to confirm
`corporate_card_surchage` and `total_amount` are in the get charge response.
- Add `corporate_card_surcharge` and `total_amount` to the get charge response.
with @danworth

PP-4128 Add corporate surcharge and total amount to payment response

---

src/test/resources/pacts/publicapi-connector-get-payment-with-corporate-surcharge.json

- Changed `refund_summary.amount_available` field in Pact interaction
because we will have corporate card surcharge fee included in the amount.
- Added `refund_summary.amount_available` matcher because we want the value
to be ignored as connector has tests for that and it is out of the scope
of the contract testing.
with @stephencdaly and @oswaldquek

PP-4131 Change refund_summary.amount_available field in Pact interaction

---

docs/api_specification.md

Just updating the docs after fixing a bug in connector.

PP-4113 Refund status should be external in api docs

---

src/main/java/uk/gov/pay/api/model/links/PaymentLinks.java
src/main/java/uk/gov/pay/api/model/links/PaymentWithAllLinks.java
src/main/java/uk/gov/pay/api/service/CreatePaymentService.java
src/main/java/uk/gov/pay/api/service/GetPaymentService.java
src/main/java/uk/gov/pay/api/service/PublicApiUriGenerator.java
src/test/java/uk/gov/pay/api/it/GetPaymentITest.java
src/test/java/uk/gov/pay/api/model/PaymentTest.java
src/test/java/uk/gov/pay/api/resources/PaymentsResourceCreatePaymentTest.java
src/test/java/uk/gov/pay/api/service/GetPaymentServiceTest.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java
src/test/resources/pacts/publicapi-connector-get-payment-with-awaiting-capture-request-state.json
src/test/resources/pacts/publicapi-connector-get-payment-with-awaiting_capture_request_state.json
swagger/swagger.json

Return capture url in the response object when received from connector
Add/refactor process to handle capture uri
When a charge is on AWAITING_CAPTURE_REQUEST state in connector, calling the endpoint `/v1/payments/{payment_external_id}` should include 
```
"_links":
"capture": {
"href": "xxxx/v1/payments/xxxxx/capture",
"method": "POST"
}
```
in the response payload. 
Any other states should include
```
"_links":
"capture": null
```

PP-4297 Add capture url to `/v1/payments/{payment_external_id}` response

---

src/main/java/uk/gov/pay/api/model/links/PaymentLinksForSearch.java
src/main/java/uk/gov/pay/api/model/links/PaymentWithAllLinks.java
src/main/java/uk/gov/pay/api/model/search/card/PaymentForSearchResult.java
src/main/java/uk/gov/pay/api/model/search/card/SearchCardPayments.java
src/main/java/uk/gov/pay/api/service/PaymentUriGenerator.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchITest.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentSearchResultBuilder.java
src/test/java/uk/gov/pay/api/service/CardPaymentSearchServiceTest.java
src/test/resources/pacts/publicapi-connector-search-payment-with-charge-in-awaiting-capture-state.json
swagger/swagger.json

- add capture URI to search results
- add pact test
When a charge is on AWAITING_CAPTURE_REQUEST state in connector, calling the endpoint /v1/payments should include
"results":[
....
"_links":
"capture": {
"href": "xxxx/v1/payments/xxxxx/capture",
"method": "POST"
}
...]
in the response payload.
Any other states should include
"results":
"_links":
"capture": null

PP-4297 Add capture URI to search results

---

src/main/java/uk/gov/pay/api/model/CardDetails.java
src/test/java/uk/gov/pay/api/it/GetPaymentITest.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchITest.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentResultBuilder.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java

- Made billing address optional on domain objects.
- Added tests for both the get payment and search payments endpoints that the billing_address property has a null value when no address is returned from connector.
with @stephencdaly

PP-4162 Make billing address Optional in CardDetails 

---

pom.xml
src/test/java/uk/gov/pay/api/utils/PublicAuthMockClient.java
src/test/java/uk/gov/pay/api/utils/mocks/BaseConnectorMockClient.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorDDMockClient.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java

mock-server version 5.5.0 is slowing down maven builds (4mins to 40mins) which is due to an existing bug in (https://github.com/jamesdbloom/mockserver/issues/565).
Downgrading to working version (5.1.0) improved build times.
`mvn clean test` - should complete under 5mins

BAU - downgrade mock-server version to 5.1.0

---

Jenkinsfile

I have a hunch that running these in parallel is causing flakiness due to
resource contention

BAU: Run e2e tests sequentially

---

docker-startup.sh

Use environment variables to set JVM system properties for proxy configuration.
This makes the application respond to the following 3 environment variables:
http_proxy - passed as http.proxyHost
https_proxy - passed as https.proxyHost
java_http_non_proxy_hosts - passed as http.nonProxyHosts

PP-4584: Manage HTTP proxies via env. vars

---

docker-startup.sh

Reverts alphagov/pay-publicapi#345
We're not going to use these environment variables - instead, we'll pass the proxy settings in via `JAVA_OPTS`

Revert "PP-4584: Manage HTTP proxies via env. vars"

---

src/test/java/uk/gov/pay/api/it/AuthorisationTest.java
src/test/java/uk/gov/pay/api/it/CreatePaymentITest.java
src/test/java/uk/gov/pay/api/it/GetPaymentITest.java
src/test/java/uk/gov/pay/api/it/PaymentRefundsResourceITest.java
src/test/java/uk/gov/pay/api/it/PaymentResourceITestBase.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchITest.java
src/test/java/uk/gov/pay/api/it/directdebit/AgreementsResourceITest.java
src/test/java/uk/gov/pay/api/it/directdebit/pact/DirectDebitPaymentTest.java
src/test/java/uk/gov/pay/api/utils/Payloads.java
src/test/java/uk/gov/pay/api/utils/Urls.java

This replaces this e2e test:
https://github.com/alphagov/pay-endtoend/blob/3b6bab09049c4c712d897d1834060f7d527da125/src/test/java/uk/gov/pay/endtoend/tests/publicapi/AuthorisationIT.java
I've also taken the opportunity to clean up some test code.
Please also approve https://github.com/alphagov/pay-endtoend/pull/701!
@oswaldquek

PP-3437: Add no auth token test

---

src/main/resources/config/config.yaml
src/test/resources/config/test-config.yaml

- Making the log lines look more like connector's by adding additional info as to what is reported.
This helps in two way: searches are going to return more uniform results,  and we will have less noise when looking for errors. For example,`level=error` will help isolating the `logger.error` lines rather than lower level ones which simply have the word error in the message

PP-4602 - change structure of loglines

---

pom.xml
src/main/java/uk/gov/pay/api/model/CardPayment.java
src/main/java/uk/gov/pay/api/model/ValidCreatePaymentRequest.java
src/main/java/uk/gov/pay/api/model/links/PaymentWithAllLinks.java
src/main/java/uk/gov/pay/api/model/search/card/PaymentForSearchResult.java
src/main/java/uk/gov/pay/api/model/search/card/PaymentSearchResults.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
swagger/swagger.json

Part 1 of fixing swagger file
- Added back fields `language` and `delayed_capture`
- Included missing search refunds API ( GET /v1/refunds)
- Fixed field naming (links -> _links) and nested "payments" key shown in `GET /v1/payments/:id` call
- Corrected specs for following API calls
- /v1/payments (both GET & POST)
- /v1/payments/{paymentId}
- /v1/payments/{paymentId}/events
- All above resulting in new swagger file
**Pending**
- All refund related APIs

PP-4610 Fix swagger - Payment & Events API specs

---

pom.xml
src/main/java/uk/gov/pay/api/resources/PaymentRefundsResource.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/resources/SearchRefundsResource.java
swagger/swagger.json

- Adds authentication information to all API calls
- Can't represent the authentication information precisely ( `Authentication : Bearer [API_KEY]` ) as it is not supported in Swagger v2.0.0.
(Migrating to open api v3.0.0 supports header with `Bearer` info, but we are not there)

PP-4610 Swagger - Add authentication information to API docs

---

Jenkinsfile
src/main/java/uk/gov/pay/api/service/CancelPaymentService.java
src/test/java/uk/gov/pay/api/it/CachingAuthenticatorTest.java
src/test/java/uk/gov/pay/api/it/PaymentsCancelResourceITest.java
src/test/java/uk/gov/pay/api/it/directdebit/pact/CancelPaymentTest.java
src/test/java/uk/gov/pay/api/service/CancelPaymentServiceTest.java
src/test/java/uk/gov/pay/api/utils/WiremockStubbing.java
src/test/resources/pacts/publicapi-connector-cancel-already-canceled-payment.json

https://github.com/alphagov/pay-endtoend/blob/3b6bab09049c4c712d897d1834060f7d527da125/src/test/java/uk/gov/pay/endtoend/tests/publicapi/CancelPaymentIT.java#L24
can be deleted. Refactoring the relevant test to a one pact one so we can have
confidence in deleting said e2e test.
Also did some minor refactoring.
@oswaldquek

PP-3437: Replace test with pact test

---

src/main/java/uk/gov/pay/api/model/Address.java
src/main/java/uk/gov/pay/api/model/CreatePaymentResult.java
src/main/java/uk/gov/pay/api/model/Payment.java
src/main/java/uk/gov/pay/api/model/RefundSummary.java
src/main/java/uk/gov/pay/api/model/SettlementSummary.java
src/main/java/uk/gov/pay/api/model/search/card/GetPaymentResult.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
swagger/swagger.json

- Includes fixes for Create payment and Get payment specs
We currently use `PaymentWithAllLinks` & `PaymentDetailForSearch` to represent responses for `CreatePayment` & `GetPayment` API calls respectively. But these object doesn't represent actual responses from publicapi. 
Created new classes `CreatePaymentResult` & `GetPaymentResult` that represent actual responses from both endpoints and also included minor improvements to examples/descriptions

PP-4610 Swagger - Fix API docs for `create & get` payment

---

src/main/java/uk/gov/pay/api/model/CardPayment.java
src/main/java/uk/gov/pay/api/model/ChargeFromResponse.java
src/main/java/uk/gov/pay/api/model/CreatePaymentResult.java
src/main/java/uk/gov/pay/api/model/links/PaymentWithAllLinks.java
src/main/java/uk/gov/pay/api/model/search/card/GetPaymentResult.java
src/main/java/uk/gov/pay/api/model/search/card/PaymentForSearchResult.java
src/test/java/uk/gov/pay/api/it/CreatePaymentITest.java
src/test/java/uk/gov/pay/api/it/GetPaymentITest.java
src/test/java/uk/gov/pay/api/it/PaymentRefundsResourceITest.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchITest.java
src/test/java/uk/gov/pay/api/it/ResourcesFilterLocalRateLimiterITest.java
src/test/java/uk/gov/pay/api/it/ResourcesFilterRateLimiterITest.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentSearchResultBuilder.java
src/test/java/uk/gov/pay/api/it/validation/PaymentsRefundsResourceAmountValidationITest.java
src/test/java/uk/gov/pay/api/resources/PaymentsResourceCreatePaymentTest.java
src/test/java/uk/gov/pay/api/service/GetPaymentServiceTest.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java
src/test/resources/pacts/publicapi-connector-get-payment-with-gateway-transaction-id.json
src/test/resources/pacts/publicapi-connector-search-payment-by-cardholder-name.json
src/test/resources/pacts/publicapi-connector-search-payment-by-first-digits-card-number.json
src/test/resources/pacts/publicapi-connector-search-payment-by-last-digits-card-number.json
swagger/swagger.json

Return the provider id (also known as the gateway transaction id in connector) when getting / searching payment(s).
Depends on https://github.com/alphagov/pay-connector/pull/1107

Pp 4862 Return the provider id

---

src/main/java/uk/gov/pay/api/model/CreatePaymentResult.java
swagger/swagger.json

- paymentId, providerId are currently generated as-is as @JsonPropery/@ApiModelProperty doesn't name the fields explicitly.

PP-4862 Fix API specs for paymentId, providerId

---

src/test/java/uk/gov/pay/api/it/PaymentsCancelResourceITest.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceCaptureITest.java
src/test/java/uk/gov/pay/api/resources/HealthCheckResourceTest.java

HealthCheckResourceTest was taken across to pay-cardid and some improvements
were made there. Bring those improvements home.
Also, statically import hamcrest's `Is.is` in the two other tests which didn't.

Stylistic improvements to tests

---

src/main/java/uk/gov/pay/api/filter/ratelimit/RedisRateLimiter.java
src/main/java/uk/gov/pay/api/model/ValidCreatePaymentRequest.java
src/test/java/uk/gov/pay/api/it/rule/RedisContainer.java
src/test/java/uk/gov/pay/api/it/rule/RedisDockerRule.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java

Address some things IntelliJ didn't like the look of.
Most of the attention was on `RedisContainer` where the `get()` from the `Map` of port mappings could throw a null. Add some guard code around that.
Remove some copypasta in `ConnectorMockClient` when constructing exceptions - we don't need `String.format()` here because we're passing a fixed string.

Intellij fixups

---

Dockerfile
README.md
docker-startup.sh
src/main/resources/config/config.yaml

Improve documentation of the environment variables in use by publicapi
Also, remove logic to avoid adding duplicate certificates to the default Java truststore; this is no longer necessary.

Document environment variables and remove certificate deduplication logic

---

src/main/java/uk/gov/pay/api/json/RequestJsonParser.java
src/main/java/uk/gov/pay/api/model/CardPayment.java
src/main/java/uk/gov/pay/api/model/ChargeFromResponse.java
src/main/java/uk/gov/pay/api/model/CreatePaymentRequest.java
src/main/java/uk/gov/pay/api/model/ValidCreatePaymentRequest.java
src/main/java/uk/gov/pay/api/model/links/PaymentWithAllLinks.java
src/main/java/uk/gov/pay/api/model/search/card/GetPaymentResult.java
src/main/java/uk/gov/pay/api/model/search/card/PaymentForSearchResult.java
src/main/java/uk/gov/pay/api/service/CreatePaymentService.java
src/test/java/uk/gov/pay/api/it/CreatePaymentITest.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentResultBuilder.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentSingleResultBuilder.java
src/test/java/uk/gov/pay/api/it/validation/PaymentResourceMetadataITest.java
src/test/java/uk/gov/pay/api/resources/PaymentsResourceCreatePaymentTest.java
src/test/java/uk/gov/pay/api/utils/mocks/BaseConnectorMockClient.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java
src/test/java/uk/gov/pay/api/utils/mocks/CreateChargeRequestParams.java
src/test/java/uk/gov/pay/api/utils/mocks/CreateChargeResponseFromConnector.java
swagger/swagger.json

The test of significance is CreatePaymentITest.createCardPaymentWithMetadata,
which assumes connector returns the metadata when creating a payment. There
will be a pact test for this in another PR. I've also taken the opportunity to
create builders for some nasty methods which take too many parameters.

PP-4886: Store metadata for charge

---

src/test/resources/pacts/publicapi-connector-cancel-already-canceled-payment.json

The structure of error responses is changing so the message field will be an array. We should remove the field from the pact entirely as we don't consume it, so shouldn't be asserting on it.

PP-5142 Remove message from error response in Pact

---

docs/api_specification.md
src/main/java/uk/gov/pay/api/model/CardPayment.java
src/main/java/uk/gov/pay/api/model/ChargeFromResponse.java
src/main/java/uk/gov/pay/api/model/links/PaymentWithAllLinks.java
src/main/java/uk/gov/pay/api/model/search/card/GetPaymentResult.java
src/main/java/uk/gov/pay/api/model/search/card/PaymentForSearchResult.java
src/test/java/uk/gov/pay/api/it/GetPaymentITest.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchITest.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentResultBuilder.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentSearchResultBuilder.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentSingleResultBuilder.java
src/test/java/uk/gov/pay/api/resources/PaymentsResourceCreatePaymentTest.java
src/test/java/uk/gov/pay/api/utils/mocks/ChargeResponseFromConnector.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java
swagger/swagger.json

- Added new fields `fee` and `net_amount` that are available from connector to get/search payments API
- Also updates swagger file with new fields

PP-5080 New API response fields `fee` and `net_amount`

---

src/main/java/uk/gov/pay/api/json/RequestJsonParser.java
src/main/java/uk/gov/pay/api/model/PaymentError.java
src/test/java/uk/gov/pay/api/it/validation/PaymentResourceMetadataValidationFailuresITest.java

The error description should begin with "Invalid attribute value: metadata.".
Where there are multiple they should be delimited with a period, not semicolon+newline.

PP-4886: Fix error description and multiple errors

---

src/main/java/uk/gov/pay/api/exception/ConnectorResponseErrorException.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java

- The error response body cannot be parsed if the message field is an array of strings, which is what Connector will return in the future. We need to be able to parse the response body to get the "reason" field for refund error responses. This change will make public api compatible with the upcoming connector change.
- Currently we only log the error message so changing the type of the message field to "Object" will mean we will continue to log it.

PP-5142 Make parsing connector error compatible with message array

---

pom.xml
src/main/java/uk/gov/pay/api/exception/ConnectorResponseErrorException.java
src/main/java/uk/gov/pay/api/exception/mapper/CreateAgreementExceptionMapper.java
src/main/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapper.java
src/main/java/uk/gov/pay/api/exception/mapper/CreateRefundExceptionMapper.java
src/test/java/uk/gov/pay/api/it/CreatePaymentITest.java
src/test/java/uk/gov/pay/api/it/directdebit/AgreementsResourceITest.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorDDMockClient.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java

Use error_identifier in error response body from Connector and Direct Debit Connector to decide the error that Public API should return for errors where we cannot infer this from the status code alone.
Currently these are just errors with identifier:
INVALID_MANDATE_TYPE
REFUND_NOT_AVAILABLE
REFUND_AMOUNT_AVAILABLE_MISMATCH

PP-5142 Use error identifiers when handling microservice errors

---

src/main/java/uk/gov/pay/api/app/config/PublicApiModule.java
src/main/java/uk/gov/pay/api/json/CreatePaymentRequestDeserializer.java
src/main/java/uk/gov/pay/api/model/Address.java
src/main/java/uk/gov/pay/api/model/PrefilledCardholderDetails.java
src/main/java/uk/gov/pay/api/model/ValidCreatePaymentRequest.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/validation/PaymentRequestValidator.java
src/test/java/uk/gov/pay/api/json/CreatePaymentRequestDeserializerTest.java
src/test/java/uk/gov/pay/api/resources/PaymentsResourceCreatePaymentTest.java
src/test/java/uk/gov/pay/api/validation/PaymentRequestValidatorTest.java

- As step towards refactoring to use Java Bean Validation rather than custom validation
methods this moves the validation of the CreatePaymentRequest outside of the
deserialisation and temporarily into the Resource. The important part is the removal of `validator.validate(paymentRequest);` from within `CreatePaymentRequestDeserializer`
- When refactoring is complete the validation will be invoked via the `@Valid`
annotation on the method parameter and the `PaymentRequestValidator` can be removed
entirely.
- Removed validation related tests from `CreatePaymentRequestDeserializerTest`
which are covered by validation tests within `PaymentRequestValidatorTest`
```
deserialize_shouldThrowValidationException_whenAmountIsLessThanMinimum = validateMinimumAmount_shouldFailValue …
```

PP-5100 Remove validation from CreatePaymentRequestDeserialiser

---

src/main/java/uk/gov/pay/api/model/CardPayment.java
src/main/java/uk/gov/pay/api/model/CreatePaymentResult.java
src/main/java/uk/gov/pay/api/model/ValidCreatePaymentRequest.java
swagger/swagger.json

Previously, without any annotation, when generated, metadata looked like
"metadata": {
"metadata": {
"property1": {},
"property2": {}
}
}
This commit forces the `metadata` on the swagger doc to be a
`Map<String,String>` by setting the `dataType` of the `ApiModelProperty`
annotation, which makes metadata look like
"metadata": {
"property1": "string",
"property2": "string"
}

PP-5101: Swagger doc for a payment's metadata

---

src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/exception/mapper/ViolationExceptionMapper.java
src/main/java/uk/gov/pay/api/model/CreatePaymentRequest.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/validation/PaymentRefundRequestValidator.java
src/main/java/uk/gov/pay/api/validation/PaymentRequestValidator.java
src/main/java/uk/gov/pay/api/validation/PaymentSearchValidator.java
src/test/java/uk/gov/pay/api/it/validation/PaymentsResourceAmountValidationITest.java
src/test/java/uk/gov/pay/api/resources/PaymentsResourceCreatePaymentTest.java
src/test/java/uk/gov/pay/api/validation/PaymentRequestValidatorTest.java

To avoid large PR which would be harder to assure ourselves that behaviour hasn't changed this is another step towards replacing our validation approach with using `@Valid` java bean validation.
First commit
```
PP-5100 Introduce bean validation to CreateChargeRequest
- Step towards removing validation from ValidateCreatePaymentRequest and to
annotation based approach on CreatePaymentRequest. This now uses bean validation
for `agreementId`.
- Create ViolationExceptionMapper to create a PaymentError from the ConstraintViolation
which will look for the api attribute name if it has a JsonProperty annotation.
- As per existing PublicApi behaviour the ViolationExceptionMapper will return only
the first exception, this can be changed later if we wish.
- Add `@Valid` to the PaymentResource to …
```

PP 5100 Step towards using `@Valid` for validation of CreatePaymentRequest

---

src/test/java/uk/gov/pay/api/it/validation/PaymentsResourceAgreementIdValidationITest.java

Was broken because http URLs are not allowed in the config.
Was somehow passing most of the time on CI, probably due to Dropwizard
ConfigOverrides, and the order of running tests meaning that allow http
was turned on by a previous test.

PP-5100 Fix broken validation test

---

src/test/java/uk/gov/pay/api/service/CreatePaymentServiceTest.java
src/test/resources/pacts/publicapi-connector-create-payment-with-zero-amount-not-allowed.json

Test the contract with connector that connector will give the expected error response when a request is made with a 0 amount and the flag on the gateway account is not enabled to allow this.

PP-5133 Add pact test for zero amount not allowed error

---

src/main/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapper.java
src/main/java/uk/gov/pay/api/model/CreatePaymentRefundRequest.java
src/main/java/uk/gov/pay/api/model/CreatePaymentRequest.java
src/main/java/uk/gov/pay/api/validation/PaymentRefundRequestValidator.java
src/test/java/uk/gov/pay/api/it/CreatePaymentITest.java
src/test/java/uk/gov/pay/api/it/validation/PaymentsResourceAmountValidationITest.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java

Change validation so that payments can be created with an amount of 0.
Handle error response from Connector when an amount of 0 is not allowed by the gateway account.

PP-5133 Allow 0 amount payments

---

src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/test/java/uk/gov/pay/api/it/CreatePaymentITest.java

We never want to allow 0 amounts for direct debit accounts, however we allow them for connector accounts and handle an error from connector if they are disallowed for the account in question

Pp 5133 dont allow zero amount for dd accounts

---

src/main/java/uk/gov/pay/api/model/CreatePaymentRequest.java
src/test/java/uk/gov/pay/api/it/validation/PaymentsResourceAmountValidationITest.java

When a create payment request is made with a negative amount, the error message will now always state that it has to be greater than or equal to 1. This will be incorrect when zero amounts are allowed for the account but this is a hidden feature, so it's better that the error is consistent for most services, which will not have this enabled.

PP-5133 Change negative amount error

---

src/test/java/uk/gov/pay/api/it/rule/RedisContainer.java

Instead of jumping into the container to run `redis-cli`, flush the database
from Java. This should be more efficient and make it easier to notice any
errors which might get thrown.

PP-5199 Use the Jedis client to flush redis

---

src/main/java/uk/gov/pay/api/exception/mapper/CancelChargeExceptionMapper.java
src/main/java/uk/gov/pay/api/exception/mapper/CaptureChargeExceptionMapper.java
src/main/java/uk/gov/pay/api/exception/mapper/CreateRefundExceptionMapper.java
src/main/java/uk/gov/pay/api/exception/mapper/GetAgreementExceptionMapper.java
src/main/java/uk/gov/pay/api/exception/mapper/GetChargeExceptionMapper.java
src/main/java/uk/gov/pay/api/exception/mapper/GetEventsExceptionMapper.java
src/main/java/uk/gov/pay/api/exception/mapper/GetRefundExceptionMapper.java
src/main/java/uk/gov/pay/api/exception/mapper/GetRefundsExceptionMapper.java
src/main/java/uk/gov/pay/api/exception/mapper/SearchChargesExceptionMapper.java

Not found errors are user errors in the use of the API. They should not be
logged at ERROR level (and don't really need to be logged at all)
please merge on approval

BAU: Don't log at error level for not found errors

---

src/main/java/uk/gov/pay/api/exception/mapper/ViolationExceptionMapper.java
src/main/java/uk/gov/pay/api/json/RequestJsonParser.java
src/main/java/uk/gov/pay/api/model/CreateCardPaymentRequest.java
src/main/java/uk/gov/pay/api/model/CreateDirectDebitPaymentRequest.java
src/main/java/uk/gov/pay/api/model/CreatePaymentRequest.java
src/main/java/uk/gov/pay/api/model/CreatePaymentRequestBuilder.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/service/ConnectorUriGenerator.java
src/main/java/uk/gov/pay/api/service/CreatePaymentService.java
src/main/java/uk/gov/pay/api/validation/PaymentSearchValidator.java
src/test/java/uk/gov/pay/api/it/CreatePaymentIT.java
src/test/java/uk/gov/pay/api/it/validation/PaymentsResourceAgreementIdValidationIT.java
src/test/java/uk/gov/pay/api/json/CreatePaymentRequestDeserializerTest.java
src/test/java/uk/gov/pay/api/json/RequestJsonParserTest.java
src/test/java/uk/gov/pay/api/resources/PaymentsResourceCreatePaymentTest.java
src/test/java/uk/gov/pay/api/service/ConnectorUriGeneratorTest.java
src/test/java/uk/gov/pay/api/service/CreatePaymentServiceTest.java

CreatePaymentRequest is currently used to represent both Card and DirectDebit payment
requests. This is becoming confusing and impractical as validation requirements
diverge between the two. This commit create dedicated sub-type for each.
1. Create CreatCardPaymentRequest and CreateDirectDebitRequest classes. Each
implementing the attributes and validation require beyond the base class of the
existing CreatePaymentRequest.
2. Simplify ViolationExceptionMapper to convert to the api field name using a
camel case to snake case conversion. This seems safe as it follows our convention
and avoids the complexity of reflection which would need extending to accomadate
the newly introduced hierarchy (if the field is not found on the sub-class then
it would have to search the super class).
3. Remove …

PP-5224 Split up CreatePaymentRequest

---

src/main/java/uk/gov/pay/api/json/RequestJsonParser.java
src/main/java/uk/gov/pay/api/model/CreateCardPaymentRequest.java
src/main/java/uk/gov/pay/api/model/CreateDirectDebitPaymentRequest.java
src/main/java/uk/gov/pay/api/model/CreatePaymentRequest.java
src/main/java/uk/gov/pay/api/model/PaymentError.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/service/ConnectorUriGenerator.java
src/main/java/uk/gov/pay/api/service/CreatePaymentService.java
src/test/java/uk/gov/pay/api/it/CreatePaymentIT.java
src/test/java/uk/gov/pay/api/it/validation/CreatePaymentReturnUrlValidationIT.java
src/test/java/uk/gov/pay/api/json/CreatePaymentRequestDeserializerTest.java
src/test/java/uk/gov/pay/api/json/RequestJsonParserTest.java
src/test/java/uk/gov/pay/api/service/ConnectorUriGeneratorTest.java

We determine whether a create payment request is a card or direct debit request when we deserialise the JSON (using RequestJsonParser.js). At this point we do not know whether the account is a card or direct debit account, so we look at whether the request contains a return_url or an agreement_id.
Previously, if there was no agreement_id or return_url, the error would always state that the return_url was missing. However, this is only true for card payments, so the error now states that one or the other of return_url or agreement_id is required.
Additionally, there was no validation done to check that the correct form of the request was made for the correct account type (card/dd). Now, if there is a mismatch an error will be returned stating either that the return_url or agreement_id is …

PP-5242 Return errors if agreement_id or return_url missing

---

src/test/resources/pacts/publicapi-connector-search-payment-by-cardholder-name.json
src/test/resources/pacts/publicapi-connector-search-payment-by-first-digits-card-number.json
src/test/resources/pacts/publicapi-connector-search-payment-by-last-digits-card-number.json

This is linked to a PR for PP-5292-Creating token for changes in search in pay-connector. Connector no longer emits next_url and next_url_post for search results and so this requires the pact file in publicapi to be modified.
- This removes next_url and next_url_post from publicapi-connector-search-payment-by-last-digits-card-number.json
- This removes next_url and next_url_post from publicapi-connector-search-payment-by-first-digits-card-number.json
- This removes next_url and next_url_post from publicapi-connector-search-payment-by-cardholder-name.json
- This PR also removes the links section containing the above. This is so the pact tests can be properly modified.
- Then PP5292 Connector PR can be merged
- Then there will be a PR containing the following code:
`"links": [{"rel": …

PP-5292-Creating token for charges in search

---

src/main/java/uk/gov/pay/api/exception/mapper/CreateAgreementExceptionMapper.java
src/test/java/uk/gov/pay/api/it/directdebit/AgreementsResourceIT.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorDDMockClient.java

- Will now respond with an error when a user attempts to create an agreement without an unlinked GoCardless account

PP-5278 Reject creation of agreement when GoCardless account is unlinked

---

src/test/resources/pacts/publicapi-connector-search-payment-by-cardholder-name.json
src/test/resources/pacts/publicapi-connector-search-payment-by-first-digits-card-number.json
src/test/resources/pacts/publicapi-connector-search-payment-by-last-digits-card-number.json

This adds the links field to publicapi-connector-search-payment-by-first-digits-card-number.json pact file.
This is because we removed the next_url and next_url post from the JSON which Connector emits to publicapi. This requires a modification of the pact file in publicapi - we have to remove the links field first to ensure that publicapi isn't expecting next_url and next_url_post then we have to add the links field without next_url and next_url_post to ensure that the pact file is properly modified.

PP-5292-Add-links-without-next_url to pact file

---

src/test/java/uk/gov/pay/api/it/GetDirectDebitEventsIT.java
src/test/java/uk/gov/pay/api/it/directdebit/pact/DirectDebitPaymentIT.java

Temporarily disable Direct Debit Pact tests in preparation for the Direct Debit connector API switching from “transaction” to “payment”.

PP-5248 Temporarily disable Direct Debit Pact tests

---

docs/api_specification.md
src/main/java/uk/gov/pay/api/model/links/directdebit/DirectDebitEvent.java
src/main/java/uk/gov/pay/api/model/links/directdebit/DirectDebitEventsResponse.java
src/main/java/uk/gov/pay/api/model/search/directdebit/DirectDebitPaymentForSearch.java
src/main/java/uk/gov/pay/api/model/search/directdebit/DirectDebitPaymentFromResponse.java
src/main/java/uk/gov/pay/api/model/search/directdebit/DirectDebitSearchResponse.java
src/main/java/uk/gov/pay/api/model/search/directdebit/SearchDirectDebitPayments.java
src/main/java/uk/gov/pay/api/model/search/links/DDPaymentLinksForSearch.java
src/main/java/uk/gov/pay/api/service/ConnectorUriGenerator.java
src/main/java/uk/gov/pay/api/service/DirectDebitEventService.java
src/test/java/uk/gov/pay/api/service/ConnectorUriGeneratorTest.java
src/test/java/uk/gov/pay/api/service/DirectDebitPaymentSearchServiceTest.java
src/test/resources/pacts/publicapi-direct-debit-connector-get-events.json
src/test/resources/pacts/publicapi-direct-debit-connector-search-by-mandate-three-results.json

In preparation for the Direct Debit connector API changing from “transaction” to “payment”, rename things in public API.
This change is separated into logical several commits, so it might be easiest to review commit by commit.

PP-5248 Rename Direct Debit “transaction” to “payment”

---

src/main/java/uk/gov/pay/api/exception/mapper/ViolationExceptionMapper.java
src/test/java/uk/gov/pay/api/resources/directdebit/DirectDebitPaymentsResourceTest.java

When Jersey validation fails for a model on the @NotNull, @NotEmpty or
@NotBlank validations, return a P0101 error which indicates that a value
is missing for a mandatory field.

PP-5298 Return P0101 Error for missing fields

---

src/main/java/uk/gov/pay/api/model/directdebit/DirectDebitConnectorCreatePaymentRequest.java
src/main/java/uk/gov/pay/api/model/directdebit/DirectDebitConnectorCreatePaymentResponse.java
src/test/resources/pacts/publicapi-direct-debit-connector-collect-payment.json

Rename "agreement_id" in request to "mandate_id".
Rename "charge_id" in response to "payment_id".
This can be done because direct debit connector currently has
compatibility for both variations.

PP-5298 Rename dd connector request/response fields

---

src/main/java/uk/gov/pay/api/exception/mapper/JsonProcessingExceptionMapper.java
src/test/java/uk/gov/pay/api/resources/directdebit/DirectDebitPaymentsResourceIT.java

Handle exception thrown when a JSON field cannot be deserialized due to
a mismatch in type.
Add tests for the direct debit payment request that these exceptions are
mapped into the appropriate errors.
Co-authored-by: Rory Malcolm <rory.malcolm@digital.cabinet-office.gov.uk>

PP-5298 Validate numeric types for jackson deserialization

---

src/main/java/uk/gov/pay/api/model/CreateDirectDebitPaymentRequest.java
src/main/java/uk/gov/pay/api/validation/PaymentSearchValidator.java

This is our standard practice.
While here, also rename a constant name to contain mandate rather than
agreement

PP-5298 Ignore unknown properties on create payment request

---

src/main/java/uk/gov/pay/api/exception/mapper/CreateAgreementExceptionMapper.java
src/test/java/uk/gov/pay/api/it/directdebit/CreateMandateIT.java

Remove dead code relating to an error returned by direct debit connector
when trying to create an agreement of the wrong type. Agreement types
are no longer a thing.

PP-5298 Remove dead code

---

src/main/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapper.java
src/test/java/uk/gov/pay/api/it/CreatePaymentIT.java

Remove reference to ErrorIdentifier.INVALID_MANDATE_TYPE

---

src/test/resources/pacts/publicapi-direct-debit-connector-collect-payment.json

- Pact tests are checking for a links object that is no longer included
in the response from DD connector. Removing this allows them to pass.

PP-5300 Stop checking for the links object in GET Payment pact tests

---

src/test/java/uk/gov/pay/api/service/MandatesServiceTest.java
src/test/resources/pacts/publicapi-direct-debit-connector-get-mandate.json

next_url and next_url_post shouldn't be returned when GETting a confirmed mandate, as the
state for the pact test is "a gateway account with external id and a confirmed
mandate exists".
The only time when these links should be returned is when the mandate is in
"created" state.
In this PR however I've removed the entire "links" json from the publicapi-direct-debit-connector-get-mandate pact. In an ideal scenario, removing the next_url and next_url_post links would work,
even though direct-debit-connector still the returns the links currently.
However it does not as Postel's Law only seems to be followed for json keys and not
for json values - an array of links in this case.
As a reminder of what
Postel's Law is, from https://docs.pact.io/getting_started/matching/gotchas:
```
Be liberal in …
```

PP-5299: Remove next_url and next_url_post links

---

src/test/java/uk/gov/pay/api/service/MandatesServiceTest.java
src/test/resources/pacts/publicapi-direct-debit-connector-get-mandate.json

The only link that should be present when GETting a confirmed mandate is the
"self" link.

PP-5299: Update GET mandate pact

---

src/main/java/uk/gov/pay/api/model/search/directdebit/DirectDebitSearchPaymentsParams.java
src/main/java/uk/gov/pay/api/resources/directdebit/DirectDebitPaymentsResource.java
src/main/java/uk/gov/pay/api/service/directdebit/DirectDebitPaymentSearchService.java
src/main/java/uk/gov/pay/api/validation/DateValidator.java
src/main/java/uk/gov/pay/api/validation/DirectDebitEventSearchValidator.java
src/main/java/uk/gov/pay/api/validation/SearchValidator.java
src/main/java/uk/gov/pay/api/validation/ValidDate.java
src/test/java/uk/gov/pay/api/resources/directdebit/DirectDebitPaymentsResourceSearchIT.java
src/test/java/uk/gov/pay/api/service/DirectDebitPaymentSearchServiceTest.java

Use annotations to provide validation for the query parameters for a
search direct debit payments request.
Add tests for validation.

PP-5301 Validate dd search params using Jackson

---

src/main/java/uk/gov/pay/api/exception/ConnectorResponseErrorException.java
src/main/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapper.java
src/main/java/uk/gov/pay/api/model/PaymentError.java
src/main/java/uk/gov/pay/api/resources/directdebit/DirectDebitPaymentsResource.java
src/test/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapperTest.java

- When a user tries to create a payment on a mandate which has an invalid
state, they should receive a 409 error with a related error code.

PP-5377 Return 409 On Create Payment With Invalid Mandate State

---

src/main/java/uk/gov/pay/api/model/search/directdebit/DirectDebitSearchMandateResponse.java
src/main/java/uk/gov/pay/api/model/search/directdebit/DirectDebitSearchMandatesParams.java
src/main/java/uk/gov/pay/api/model/search/directdebit/SearchMandateConnectorResponse.java
src/main/java/uk/gov/pay/api/service/MandatesService.java
src/main/java/uk/gov/pay/api/service/directdebit/DirectDebitConnectorUriGenerator.java
src/main/java/uk/gov/pay/api/service/directdebit/DirectDebitMandateSearchService.java
src/test/java/uk/gov/pay/api/model/search/directdebit/DirectDebitSearchMandatesParamsTest.java
src/test/java/uk/gov/pay/api/service/MandatesServiceTest.java
src/test/java/uk/gov/pay/api/service/directdebit/DirectDebitMandateSearchServiceTest.java
src/test/resources/pacts/publicapi-direct-debit-connector-search-mandates.json

This is a stepping stone to adding mandate search functionality to PublicAPi. I'm breaking it down to help review process but the final implementation will likely see `DirectDebitMandateSearchService.getMandatesFromDDConnector` become private under a public method that will return a client side api response. It looks big but it includes a new pact file (I've validated it locally against current master DDConnector) and a few POJOs to support the creation of query params and the mandate search response from DDConnector.
Any necessary API validation to `DirectDebitSearchMandatesParams` will be added when the end-point is added to the Resource.
with @RoryMalcolm

Pp 5302 direct debit search mandates add service

---

src/main/java/uk/gov/pay/api/exception/SearchMandatesException.java
src/main/java/uk/gov/pay/api/model/directdebit/mandates/MandateConnectorResponse.java
src/main/java/uk/gov/pay/api/model/directdebit/mandates/MandateResponse.java
src/main/java/uk/gov/pay/api/model/search/directdebit/DirectDebitSearchMandatesParams.java
src/main/java/uk/gov/pay/api/model/search/directdebit/SearchMandateConnectorResponse.java
src/main/java/uk/gov/pay/api/model/search/directdebit/SearchMandateResponse.java
src/main/java/uk/gov/pay/api/resources/MandatesResource.java
src/main/java/uk/gov/pay/api/service/MandatesService.java
src/main/java/uk/gov/pay/api/service/PublicApiUriGenerator.java
src/main/java/uk/gov/pay/api/service/directdebit/DirectDebitMandateSearchService.java
src/test/java/uk/gov/pay/api/it/directdebit/MandateResourceGetMandateIT.java
src/test/java/uk/gov/pay/api/it/directdebit/MandateResourceSearchMandateIT.java
src/test/java/uk/gov/pay/api/service/directdebit/DirectDebitMandateSearchServiceTest.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorDDMockClient.java
swagger/swagger.json

Continue to build out mandate search functionality in PublicApi. This introduces most of the feature but will require more tests around failure paths.

PP 5429 add endpoint for mandate search

---

src/test/java/uk/gov/pay/api/service/MandatesServiceTest.java
src/test/resources/pacts/publicapi-direct-debit-connector-get-mandate.json

Temporarily remove the `state.details` property from the Direct Debit connector pacts while we make the changes to populate the property with real data.

PP-5442 Remove more state.details from Direct Debit connector pacts

---

src/test/resources/pacts/publicapi-direct-debit-connector-get-mandate.json

Trailing comma slipped into a JSON Pact file.

PP-5442 Remove extraneous comma

---

src/test/resources/pacts/publicapi-connector-get-payment-with-awaiting-capture-request-state.json

We want to rename this status. Public API should permit both the old and the new value for this status.

PP-5447 relax pact test for awating capture

---

src/main/java/uk/gov/pay/api/resources/directdebit/DirectDebitPaymentsResource.java
swagger/swagger.json

This is for better naming and differentiation between direct debit payments and
card payments in the public API docs. The search operationId for card and
direct debit payments was 'searchPayments' previously, causing one to overwrite
the other.

PP-5346: Specify operationIds for directdebit mandates/payments

---

src/main/java/uk/gov/pay/api/model/CreateDirectDebitPaymentRequest.java
src/main/java/uk/gov/pay/api/resources/directdebit/DirectDebitPaymentsResource.java
src/test/java/uk/gov/pay/api/resources/directdebit/DirectDebitPaymentsResourceCreatePaymentIT.java
swagger/swagger.json

The minimum amount that gocardless accept for a payment is 100 pence so increasing
the current min to 100 from 1. Also adding swagger annotation to include the payload
for creating a direct debit payment.

PP-5433 Correct min amount for a Direct Debit Payment

---

src/test/resources/pacts/publicapi-direct-debit-connector-collect-payment.json

To be able to collect a payment from a Direct Debit mandate, the mandate needs to have been submitted to a provider and have a provider ID.
The collect payment Pact tests didn’t set up the mandate with a provider ID. This has worked up until now because sandbox was lax about whether or not the mandate had been submitted but it’s getting stricter now, so the Pact test needs to set up the mandate in the correct state.

PP-5493 Set up mandate correctly for DD collect payment tests

---

src/test/resources/pacts/publicapi-direct-debit-connector-collect-payment.json
src/test/resources/pacts/publicapi-direct-debit-connector-create-mandate.json
src/test/resources/pacts/publicapi-direct-debit-connector-get-directdebit-payment.json
src/test/resources/pacts/publicapi-direct-debit-connector-get-mandate.json
src/test/resources/pacts/publicapi-direct-debit-connector-search-by-mandate-three-results.json
src/test/resources/pacts/publicapi-direct-debit-connector-search-mandates.json

- Removes the 'finished' boolean field from the Pact tests, enabling
them to pass when the state is removed from the return object

PP-5474 Remove Finished From Pact State

---

swagger/swagger.json

The "finished" property has been removed from the "state" object for direct debit payment and mandate responses. This is the build swagger file for this change.

PP-5475 Build swagger with removed finished property

---

src/main/java/uk/gov/pay/api/model/directdebit/DirectDebitPaymentLinks.java
src/main/java/uk/gov/pay/api/model/directdebit/mandates/DirectDebitPayment.java
src/main/java/uk/gov/pay/api/model/directdebit/mandates/MandateResponse.java
src/main/java/uk/gov/pay/api/model/links/directdebit/MandateLinks.java
src/test/java/uk/gov/pay/api/it/directdebit/CreateMandateIT.java
src/test/java/uk/gov/pay/api/it/directdebit/MandateResourceGetMandateIT.java
src/test/java/uk/gov/pay/api/it/directdebit/MandateResourceSearchMandateIT.java
src/test/java/uk/gov/pay/api/resources/directdebit/DirectDebitPaymentsResourceCreatePaymentIT.java
src/test/java/uk/gov/pay/api/resources/directdebit/DirectDebitPaymentsResourceGetIT.java
swagger/swagger.json

- Currently an unused events link is returned inside PublicAPI
responses, as this is currently unused it should be removed from the
builder classes so this confusing information is not returned to users.

PP-5495 Remove Events Link From PublicAPI

---

src/test/resources/pacts/publicapi-ledger-get-payment-with-corporate-surcharge.json
src/test/resources/pacts/publicapi-ledger-get-payment-with-delayed-capture-true.json
src/test/resources/pacts/publicapi-ledger-get-payment-with-fee-and-net-amount.json
src/test/resources/pacts/publicapi-ledger-get-payment-with-gateway-transaction-id.json
src/test/resources/pacts/publicapi-ledger-get-payment-with-metadata.json
src/test/resources/pacts/publicapi-ledger-search-transaction.json

* they're not used in public api
* it will allow deprecating them in ledger

PP-5419: remove transaction links from expected ledger response

---

src/main/java/uk/gov/pay/api/model/search/directdebit/DirectDebitSearchMandatesParams.java
src/test/java/uk/gov/pay/api/it/directdebit/MandateResourceSearchMandateIT.java
swagger/swagger.json

Fix allowed states and improve error message if an invalid state is provided for the search mandates endpoint.

PP-5516 Fix state validation for search mandate

---

src/main/java/uk/gov/pay/api/model/PaymentError.java

When collecting a payment the mandate must be in an external state of
`pending` or `active`. This commit corrects the error message when
attempting to collect a payment on a mandate with an invalid state.

PP-5459 Fix error message for invalid mandate state

---

src/main/java/uk/gov/pay/api/model/search/directdebit/DirectDebitSearchPaymentsParams.java
src/test/java/uk/gov/pay/api/resources/directdebit/DirectDebitPaymentsResourceGetIT.java

We don't want to allow uppercase states for the search direct debit payments endpoint. Currently we return a "Downstream system error" when trying to search by an upper case state because directdebit-connector only expects lowercase states

PP-5516 Fix allowing uppercase states for DD payment search

---

pom.xml

This isn't needed, as far as i can tell.

bau: Remove wiremock-jre8-standalone dependency

---

docs/api_specification.md
src/main/java/uk/gov/pay/api/model/RefundError.java
src/main/java/uk/gov/pay/api/model/search/directdebit/DirectDebitSearchPaymentsParams.java
src/main/java/uk/gov/pay/api/resources/DirectDebitEventsResource.java
src/main/java/uk/gov/pay/api/resources/MandatesResource.java
src/main/java/uk/gov/pay/api/resources/PaymentRefundsResource.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/resources/SearchRefundsResource.java
src/main/java/uk/gov/pay/api/resources/directdebit/DirectDebitPaymentsResource.java
swagger/swagger.json

Group resources in public API documentation into 3 groups:
"Card Payments"
"Direct Debit"
"Refunds"
> NOTE: I think the resources currently in "Refunds" should go into "Card Payments" as they don't apply to Direct Debit. I'd like any opinions on this.
Add human readable names for the resources, which appear in the left hand navigation bar of the API documentation browser.
Find attached a built version of the API browser
[build.zip](https://github.com/alphagov/pay-publicapi/files/3452883/build.zip)

BAU Make published swagger documentation more human readable

---

Jenkinsfile

We now have a single entrypoint for running end to end tests. Let's try using it.

Use common entry point for all end to end tests

---

src/main/java/uk/gov/pay/api/model/CardDetails.java

Document that the format of the `"expiry_date"` inside `"card_details"` is MM/yy.
Change the example date from 12/20 to 04/24 to make it clear that months have leading zeros.

API docs: specify that "expiry_date" format is MM/yy

---

src/main/java/uk/gov/pay/api/model/telephone/PaymentOutcome.java
src/main/java/uk/gov/pay/api/validation/PaymentOutcomeValidator.java
src/test/java/uk/gov/pay/api/resources/telephone/PaymentOutcomeValidationResourceTest.java

This PR adds a null check in PaymentOutcomeValidator to ensure that the exception is handled when no status is provided in the PaymentOutcome section of the JSON. I have added 2 tests in the PaymentOutcomeValidationResourceTest to check this.
`"payment_outcome": { 
}`

PP-4769- Adds null check for PaymentOutcomeValidator to handle missing status

---

swagger/swagger.json

Document that the format of the `"expiry_date"` inside `"card_details"` is MM/yy.
Change the example date from 12/20 to 04/24 to make it clear that months have leading zeros.

Swagger: specify that "expiry_date" format is MM/yy

---

src/main/java/uk/gov/pay/api/exception/ConnectorResponseErrorException.java
src/main/java/uk/gov/pay/api/exception/GetRefundException.java
src/main/java/uk/gov/pay/api/exception/GetTransactionException.java
src/main/java/uk/gov/pay/api/ledger/service/LedgerUriGenerator.java
src/main/java/uk/gov/pay/api/model/RefundResponse.java
src/main/java/uk/gov/pay/api/resources/GetPaymentRefundStrategy.java
src/main/java/uk/gov/pay/api/resources/PaymentRefundsResource.java
src/main/java/uk/gov/pay/api/service/ConnectorService.java
src/main/java/uk/gov/pay/api/service/ConnectorUriGenerator.java
src/main/java/uk/gov/pay/api/service/GetPaymentRefundService.java
src/main/java/uk/gov/pay/api/service/LedgerService.java
src/test/java/uk/gov/pay/api/resources/GetPaymentRefundStrategyTest.java
src/test/java/uk/gov/pay/api/service/GetPaymentRefundServiceTest.java
src/test/resources/pacts/publicapi-connector-get-payment-refund.json

* created GetPaymentRefundStrategy + test
* created GetPaymentRefundService
* moved retrieving refund from Connector to ConnectorService
* added pact test for connector
Todo (outside of this PR):
* rename `TransactionResponse` to `TransactionFromLedger` (or similar)
* Refunds should use it as well, that would allow a little bit of clean-up later on
* use transaction_type for getting payment as well (ideally merge two methods from LedgerService)
* pact test for ledger

PP-5498: add strategy for get refund

---

src/main/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapper.java

- There is a general check for a 404 error from DD connector at the
beginning of the error if statement, this should have an exception to
the rule for cases where the erroridentifier is Mandate_ID_Invalid as
this has a more specific error but is still a 404, this change adds that
to ensure the more specific error can reach the user.

PP-5519 Fix Error Logic

---

src/main/java/uk/gov/pay/api/model/PaymentError.java

- We are currently returning a P code which is already used by another
error, causing a conflict between the two messages, this commit resolves
this.

PP-5519 Switch To Unused P Code

---

src/main/java/uk/gov/pay/api/model/ledger/RefundTransactionFromLedger.java
src/main/java/uk/gov/pay/api/model/ledger/SearchRefundsResponseFromLedger.java
src/main/java/uk/gov/pay/api/model/search/PaginationDecorator.java
src/main/java/uk/gov/pay/api/model/search/card/RefundForSearchRefundsResult.java
src/main/java/uk/gov/pay/api/resources/SearchRefundsResource.java
src/main/java/uk/gov/pay/api/resources/SearchRefundsStrategy.java
src/main/java/uk/gov/pay/api/service/LedgerService.java
src/main/java/uk/gov/pay/api/service/RefundsParams.java
src/main/java/uk/gov/pay/api/service/SearchRefundsService.java
src/test/java/uk/gov/pay/api/resources/SearchRefundsStrategyTest.java
src/test/java/uk/gov/pay/api/service/SearchRefundsServiceTest.java

- Adds `SearchRefundsStrategy` to use ledger based on X-Ledger header
- LedgerService now supports search refunds
- `PaginationDecorator` - Excludes specific parameters (acount_id, transaction_type...) from ledger as they are not required in transformed publicapi URI

PP-5499 Ledger for refunds search

---

src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/filter/RateLimiterFilter.java
src/main/java/uk/gov/pay/api/filter/ratelimit/LocalRateLimiter.java
src/main/java/uk/gov/pay/api/filter/ratelimit/RateLimit.java
src/main/java/uk/gov/pay/api/filter/ratelimit/RateLimiter.java
src/main/java/uk/gov/pay/api/filter/ratelimit/RedisRateLimiter.java
src/test/java/uk/gov/pay/api/filter/RateLimiterFilterTest.java
src/test/java/uk/gov/pay/api/filter/ratelimit/LocalRateLimiterTest.java
src/test/java/uk/gov/pay/api/filter/ratelimit/RateLimiterTest.java
src/test/java/uk/gov/pay/api/filter/ratelimit/RedisRateLimiterTest.java

- Updated RateLimiterFilter type to ContainerRequestFilter (from Filter) so security context is available for the filter (that holds `Account` principal object)
- Assigned priority `@Priority(Priorities.USER)` so that the filter comes after `OAuthCredentialAuthFilter`(dropwizard) which authorises token and creates security context
- RedisRateLimiter & LocalRateLimiter now logs account ID and HTTP method if requests are rate limited
- Updated relevant tests

PP-5607 RateLimiterFilter - Improve logging

---

src/main/java/uk/gov/pay/api/model/CreatePaymentResult.java
swagger/swagger.json

- swagger model is out of date, missing (optional) fields, like email and card_details
- see https://govuk.zendesk.com/agent/tickets/3783443

BAU fix CreatePaymentResult swagger model

---

src/main/java/uk/gov/pay/api/model/Address.java
src/test/java/uk/gov/pay/api/it/validation/CreatePaymentWithPrefilledCardholderDetailsValidationIT.java

Prefilled country should not be validated - if it
is invalid connector will discard it, and the user will
then be presented with default country code, which is fine.

PP-5610 Remove country code validation

---

pom.xml
src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/filter/ClearMdcValuesFilter.java
src/main/java/uk/gov/pay/api/filter/GatewayAccountIdFilter.java
src/main/resources/config/config.yaml
src/test/resources/config/test-config.yaml

PP-5612 Add gateway account id to logs
To aid debugging this adds the gateway account id to the MDC using a
`ContainerRequestFilter` so it can be logged in subsequent lines. The value is
cleared by  a new `ClearMdcValuesFilter` class which is a
`ServletFilter` at the head of the filter chain, this allows it to clean the
mdc values within a `finally` block after calling `chain.doFilter()`.
An alternative to using the `ClearMdcValuesFilter` to clean up at the
end of the request would be follow the pattern of the `LoggingFilter`
which we use to add the request-id. This will replace the request-id if
it already exists, else set it a new. Although this seems simpler it
has the risk of any log lines printed prior to `LoggingFilter`
containing a stale request-id; instead it seems safer to clean …

PP-5612 Add gateway account id to logs

---

src/main/java/uk/gov/pay/api/validation/URLValidator.java
src/test/java/uk/gov/pay/api/validation/URLValidatorTest.java

- Adds a URLValidator exemption for the .local TLD & tests to ensure
that they are valid.

BAU Add Local TLD Exemption

---

src/main/java/uk/gov/pay/api/json/RequestJsonParser.java
src/test/java/uk/gov/pay/api/it/CreatePaymentIT.java

If the `metadata` key is supplied in a create payment request and the
value is `null` then return a 422 status code and a helpful message.
Previously this was causing a `NullPointerException` when passing `null`
to the `ExternalMetadata` constructor.

PP-5623 Check for null metadata value

---

src/main/java/uk/gov/pay/api/app/config/PublicApiConfig.java
src/main/java/uk/gov/pay/api/resources/GetOnePaymentStrategy.java
src/main/java/uk/gov/pay/api/resources/GetPaymentEventsStrategy.java
src/main/java/uk/gov/pay/api/resources/GetPaymentRefundStrategy.java
src/main/java/uk/gov/pay/api/resources/GetPaymentRefundsStrategy.java
src/main/java/uk/gov/pay/api/resources/LedgerOrConnectorStrategyTemplate.java
src/main/java/uk/gov/pay/api/resources/PaymentRefundsResource.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/resources/SearchPaymentsStrategy.java
src/main/java/uk/gov/pay/api/resources/SearchRefundsResource.java
src/main/java/uk/gov/pay/api/resources/SearchRefundsStrategy.java
src/main/resources/config/config.yaml
src/test/java/uk/gov/pay/api/resources/GetOnePaymentStrategyTest.java
src/test/java/uk/gov/pay/api/resources/GetPaymentEventsStrategyTest.java
src/test/java/uk/gov/pay/api/resources/GetPaymentRefundStrategyTest.java
src/test/java/uk/gov/pay/api/resources/GetPaymentRefundsStrategyTest.java
src/test/java/uk/gov/pay/api/resources/PaymentsResourceCreatePaymentTest.java
src/test/java/uk/gov/pay/api/resources/SearchPaymentsStrategyTest.java
src/test/java/uk/gov/pay/api/resources/SearchRefundsStrategyTest.java
src/test/resources/config/test-config.yaml

**Why**
There is a `X-Ledger` header that controls data source of  the charge endpoints. If it's not specified it uses connector. If it's `future-strategy` it simulates the behaviour when we switch ledger on in production (depending on the endpoint it can be always using ledger or connector falling back to ledger). `ledger-only` is for testing purposes - to be able to compare connector and ledger responses.
In order to switch to using ledger as a primary source of information (with a possibility to roll it back only with a configuration change) I introduced a feature flag (`FEATURE_ALWAYS_USE_FUTURE_LEDGER_CONNECTOR_STRATEGY`) that allows to switch to `future strategy`. By default the feature value is false so it would be using connector for all the requests (unless `X-Ledger` header says …

PP-5604 use future strategy only

---

src/main/java/uk/gov/pay/api/ledger/service/LedgerUriGenerator.java
src/test/resources/pacts/publicapi-ledger-get-payment-events.json
src/test/resources/pacts/publicapi-ledger-get-payment-refund.json
src/test/resources/pacts/publicapi-ledger-get-payment-with-corporate-surcharge.json
src/test/resources/pacts/publicapi-ledger-get-payment-with-delayed-capture-true.json
src/test/resources/pacts/publicapi-ledger-get-payment-with-fee-and-net-amount.json
src/test/resources/pacts/publicapi-ledger-get-payment-with-gateway-transaction-id.json
src/test/resources/pacts/publicapi-ledger-get-payment-with-metadata.json

In order to for ledger to be compatible with connector
the returned status needs to be the old version ("status_version", "1")
Updated pact test to match value (to prevent regression)
ledger changes to support status_version
https://github.com/alphagov/pay-ledger/pull/295

PP-5628: update ledger requests to use old status version

---

Jenkinsfile
README.md
docker-startup.sh
env.sh

This was only used for testing environments, but they no longer run with TLS
enabled. Remove support for adding additional CA certificates to the Java
truststore.
Also, sneak in a change to how we call smoketests from the `Jenkinsfile`

Remove support for custom CA certificates

---

src/main/java/uk/gov/pay/api/model/telephone/CreateTelephonePaymentRequest.java

This PR fixes an error in the toConnectorPayload() method of CreateTelephonePaymentRequest. The problem occurs as 'this.getAuthCode' returns an Optional which isn't unwrapped. Similarly with 'getErrorCode' and 'getErrorMessage' both return Optionals which aren't unwrapped. This causes an error in Connector as it is unable to deserialize into a String as an Optional<String> is sent across instead of a String.
This PR unwraps the Optionals and returns them as Strings.

PP-5443-Fix to Connector Payload method

---

README.md
src/main/java/uk/gov/pay/api/app/config/RateLimiterConfig.java
src/main/java/uk/gov/pay/api/app/config/StringToListConverter.java
src/main/resources/config/config.yaml
src/test/java/uk/gov/pay/api/app/config/StringToListConverterTest.java
src/test/java/uk/gov/pay/api/it/validation/PublicApiConfigIT.java
src/test/resources/config/test-config.yaml

In order to support extended limits for chosen accounts we need to extend configuration.
* add additional parameter values for rate-limitting
* introduce converter to transform string into list of strings
* cover changes with tests
* update README

PP-5632: add configuration for rate-limiting

---

src/main/java/uk/gov/pay/api/app/config/PublicApiModule.java
src/main/java/uk/gov/pay/api/filter/RateLimiterFilter.java
src/main/java/uk/gov/pay/api/filter/RateLimiterKey.java
src/main/java/uk/gov/pay/api/filter/ratelimit/RateLimitManager.java
src/main/java/uk/gov/pay/api/filter/ratelimit/RateLimiter.java
src/main/java/uk/gov/pay/api/filter/ratelimit/RedisRateLimiter.java
src/main/java/uk/gov/pay/api/utils/PathHelper.java
src/test/java/uk/gov/pay/api/filter/RateLimiterFilterTest.java
src/test/java/uk/gov/pay/api/filter/RateLimiterKeyTest.java
src/test/java/uk/gov/pay/api/filter/ratelimit/RateLimitManagerTest.java
src/test/java/uk/gov/pay/api/filter/ratelimit/RateLimiterTest.java
src/test/java/uk/gov/pay/api/filter/ratelimit/RedisRateLimiterTest.java
src/test/java/uk/gov/pay/api/utils/PathHelperTest.java

Context:
At the moment rate limiting works on per method basis [GET/POST].
It is required to introduce separate buckets (each bucket will have separate limit counter):
* [POST] create payment
* [POST] capture payment
* remaining [POST] requests
* all [GET] requests
In order to do that the RateLimiterKey has been introduces. It determines the bucket
based on the method and path (taken from ContainerRequestContext).
On top of splitting endpoints into separate buckets the logic to have two types of limits
has been introduced. Certain accounts (defined in configuration #697) will have different limits
than by default. In the implementation RateLimitManager is used to determine the limit based on
account id and RateLimiterKey (although at the moment only method from the object is used for the …

PP-5632: Implementation for rate-limiting

---

src/main/java/uk/gov/pay/api/ledger/service/LedgerUriGenerator.java
src/main/java/uk/gov/pay/api/model/search/PaginationDecorator.java
src/test/resources/pacts/publicapi-ledger-search-payments.json
src/test/resources/pacts/publicapi-ledger-search-refunds.json
src/test/resources/pacts/publicapi-ledger-search-transaction.json

- PublicAPI uses different statuses to selfservice. With status_version=1, ledger returns the status on par with connector

PP-5637 Search ledger by status version `1`

---

src/main/java/uk/gov/pay/api/app/config/RateLimiterConfig.java

It seems the dropwizard uses converter only when there is a value;
When there is none it returns null;
The fix is to wrap the value in optional nullable and return empty list if
value doesn't exist.

PP-5632: fix to config causing null pointer exception

---

src/main/java/uk/gov/pay/api/app/config/RateLimiterConfig.java
src/main/java/uk/gov/pay/api/app/config/StringToListConverter.java
src/main/java/uk/gov/pay/api/filter/RateLimiterFilter.java
src/main/java/uk/gov/pay/api/filter/RateLimiterKey.java
src/main/java/uk/gov/pay/api/filter/ratelimit/LocalRateLimiter.java
src/main/java/uk/gov/pay/api/filter/ratelimit/RateLimitManager.java
src/main/java/uk/gov/pay/api/filter/ratelimit/RateLimiter.java
src/main/java/uk/gov/pay/api/filter/ratelimit/RedisRateLimiter.java
src/main/java/uk/gov/pay/api/utils/PathHelper.java
src/test/java/uk/gov/pay/api/app/config/StringToListConverterTest.java
src/test/java/uk/gov/pay/api/filter/ratelimit/LocalRateLimiterTest.java
src/test/java/uk/gov/pay/api/filter/ratelimit/RateLimiterTest.java
src/test/java/uk/gov/pay/api/filter/ratelimit/RedisRateLimiterTest.java
src/test/java/uk/gov/pay/api/it/validation/PublicApiConfigIT/EmptyElevatedAccountsPublicApiConfigIT.java
src/test/java/uk/gov/pay/api/it/validation/PublicApiConfigIT/PublicApiConfigIT.java
src/test/resources/config/empty-elevated-accounts-test-config.yaml

Addressing review comments (https://github.com/alphagov/pay-publicapi/pull/701 and https://github.com/alphagov/pay-publicapi/pull/697):
* filtering empty values in StringToListConverter
* using method from rateLimiterKey in RateLimiterFilter
* removing unused imports from RateLimiterKey
* using HttpMethod.POST instead of string in RateLimitManager
* using removeEnd to remove trailing slash in PathHelper
* refactor LocalRateLimiter to use RateLimiterKey

PP-5632: rate-limiting follow-up changes

---

src/main/java/uk/gov/pay/api/service/LedgerService.java
src/test/resources/pacts/publicapi-ledger-search-payments.json

Context:
Connector endpoint used by public api does the exact match search.
In order to do the same through ledger the exact_reference_match query param
needs to be added to the search call (https://github.com/alphagov/pay-ledger/pull/305)
Changes:
* add exact_reference_match query param to payments search endpoint (LedgerService)
* update pact to include exact_reference_match query param for payments search

PP-5647: add exact_reference_match query param to ledger search call

---

src/main/java/uk/gov/pay/api/model/telephone/CreateTelephonePaymentRequest.java
src/test/java/uk/gov/pay/api/it/telephone/CardExpiryValidationIT.java
src/test/java/uk/gov/pay/api/it/telephone/CreateTelephonePaymentIT.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java
src/test/java/uk/gov/pay/api/validation/CardExpiryValidatorTest.java

- as pointed out by our integrating partner, card_expiry field is not present when the transaction failed. We're removing the @NotNull annotation from CreateTelephonePaymentRequest
- update relevant tests

PP-5648 make expiry date an optional field

---

pom.xml
src/main/resources/config/swagger-config.yaml

- To move from swagger v2.0 to Open API v3.0.0
- Adds swagger core library and plugin to generate swagger with openapi 3.0 specification
- Configuration for resource classes and basic info including auth
- `mvn compile` will generate a swagger file `swagger_v3_0_0.json` ("openapi" : "3.0.1") with all the definitions for resource packages specified
Although swagger file is generated, it is not accurate with the definitions and examples. PRs to follow that defines required properties for schemas, descriptions, examples..

PP-5285 Swagger library and config

---

src/main/java/uk/gov/pay/api/model/CreatePaymentRefundRequest.java
src/main/java/uk/gov/pay/api/model/PaymentError.java
src/main/java/uk/gov/pay/api/model/RefundError.java
src/main/java/uk/gov/pay/api/model/RefundResponse.java
src/main/java/uk/gov/pay/api/model/RefundsResponse.java
src/main/java/uk/gov/pay/api/model/links/Link.java
src/main/java/uk/gov/pay/api/model/links/RefundLinksForSearch.java
src/main/java/uk/gov/pay/api/model/links/SearchNavigationLinks.java
src/main/java/uk/gov/pay/api/model/search/card/RefundForSearchRefundsResult.java
src/main/java/uk/gov/pay/api/model/search/card/RefundForSearchResult.java
src/main/java/uk/gov/pay/api/model/search/card/RefundResult.java
src/main/java/uk/gov/pay/api/model/search/card/SearchRefundsResults.java
src/main/java/uk/gov/pay/api/resources/PaymentRefundsResource.java
src/main/java/uk/gov/pay/api/resources/SearchRefundsResource.java
src/main/java/uk/gov/pay/api/resources/error/ApiErrorResponse.java

Prep to convert swagger to openAPI v3.0
- Adds annotations for refund endpoints defining parameters required, examples for related schemas
- `mvn compile` should now generate swagger (with openapi v3.0.0) with correct definitions for refund endpoints including examples

PP-5285 OpenAPI specs for refund endpoints

---

src/main/java/uk/gov/pay/api/model/CreateDirectDebitPaymentRequest.java
src/main/java/uk/gov/pay/api/model/Payment.java
src/main/java/uk/gov/pay/api/model/directdebit/DirectDebitConnectorPaymentResponse.java
src/main/java/uk/gov/pay/api/model/directdebit/DirectDebitPaymentLinks.java
src/main/java/uk/gov/pay/api/model/directdebit/mandates/CreateMandateRequest.java
src/main/java/uk/gov/pay/api/model/directdebit/mandates/DirectDebitPayment.java
src/main/java/uk/gov/pay/api/model/directdebit/mandates/MandateError.java
src/main/java/uk/gov/pay/api/model/directdebit/mandates/MandateResponse.java
src/main/java/uk/gov/pay/api/model/directdebit/mandates/MandateStatus.java
src/main/java/uk/gov/pay/api/model/directdebit/mandates/Payer.java
src/main/java/uk/gov/pay/api/model/links/PostLink.java
src/main/java/uk/gov/pay/api/model/links/directdebit/MandateLinks.java
src/main/java/uk/gov/pay/api/model/search/directdebit/DirectDebitSearchMandatesParams.java
src/main/java/uk/gov/pay/api/model/search/directdebit/DirectDebitSearchPaymentsParams.java
src/main/java/uk/gov/pay/api/model/search/directdebit/DirectDebitSearchResponse.java
src/main/java/uk/gov/pay/api/resources/MandatesResource.java
src/main/java/uk/gov/pay/api/resources/directdebit/DirectDebitPaymentsResource.java

Follows on from https://github.com/alphagov/pay-publicapi/pull/722 and now includes definitions for DirectDebit endpoints (for openapi v3.0.0)
- `mvn compile` should now generate swagger (with openapi v3.0.0) with correct definitions for direct debit endpoints including examples

PP-5285 Open API specs for `DirectDebit` endpoints

---

src/main/java/uk/gov/pay/api/model/Address.java
src/main/java/uk/gov/pay/api/model/CardDetails.java
src/main/java/uk/gov/pay/api/model/CardPayment.java
src/main/java/uk/gov/pay/api/model/CreateCardPaymentRequest.java
src/main/java/uk/gov/pay/api/model/CreatePaymentResult.java
src/main/java/uk/gov/pay/api/model/PaymentEventResponse.java
src/main/java/uk/gov/pay/api/model/PaymentEventsResponse.java
src/main/java/uk/gov/pay/api/model/PaymentState.java
src/main/java/uk/gov/pay/api/model/PrefilledCardholderDetails.java
src/main/java/uk/gov/pay/api/model/RefundSummary.java
src/main/java/uk/gov/pay/api/model/SettlementSummary.java
src/main/java/uk/gov/pay/api/model/links/PaymentEventLink.java
src/main/java/uk/gov/pay/api/model/links/PaymentLinksForEvents.java
src/main/java/uk/gov/pay/api/model/search/card/PaymentSearchResults.java
src/main/java/uk/gov/pay/api/model/search/directdebit/DirectDebitSearchMandatesParams.java
src/main/java/uk/gov/pay/api/resources/MandatesResource.java
src/main/java/uk/gov/pay/api/resources/PaymentRefundsResource.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java

- Swagger definitions for Card payment endpoints (for openapi v3.0.0)
- `mvn compile` should now generate swagger (with openapi v3.0.0) with correct definitions for card payment endpoints including examples

PP-5285 Open API specs for `Card payment` endpoints

---

pom.xml
swagger/swagger.json

- Convert swagger to Openapi v3
- Removed swagger-maven-plugin (groupId: com.github.kongchen)
- Npm packages `swagger2openapi` (to convert current swagger to openapi) & `json-diff` can be used to find differences with previous version and v3 (current version). 
[Click here to see differences or run commmands below ](https://github.com/alphagov/pay-publicapi/files/3695846/swaggerv2_v3_diff.pdf)
```
npm install swagger2openapi
./node_modules/swagger2openapi/swagger2openapi.js -o swagger_old.json https://raw.githubusercontent.com/alphagov/pay-publicapi/ab938d0f79470566fb63bd6638de44c6e6b0ffd6/swagger/swagger.json
wget --output-document=swagger_new.json https://raw.githubusercontent.com/alphagov/pay-publicapi/599452aac435e9e0b8215aaa3ba089495d281d96 …
```

PP-5285 Convert swagger to Openapi v3

---

src/main/java/uk/gov/pay/api/exception/mapper/CancelChargeExceptionMapper.java
src/main/java/uk/gov/pay/api/exception/mapper/CaptureChargeExceptionMapper.java

We should not log an error if e.g. connector responds with a
400 - this can happen for all sorts of normal reasons. Seems
useful to keep log in case of connector 500, but don't log anything
otherwise.

PP-5757 Only log error if connector 500s

---

src/main/java/uk/gov/pay/api/resources/PaymentRefundsResource.java
src/test/java/uk/gov/pay/api/it/PaymentRefundsResourceIT.java

Previously if charge not found when trying to retrieve charge,
we got a NPE. Instead use Connector Service to get charge which
handles errors and deserialisation etc, meaning a 404 will be thrown
if refund attempted for non-existent charge.
It is possible for the refund summary on a charge not to be
present when fetching a charge in process of refund. In that
case assume the amount available to refund is 0. This does mean
an extra call will be made to connector before the refund fails, but
has the advantage of keeping the logic contained in connector.

PP-5758 Return 404 if charge not found when refunding

---

src/main/java/uk/gov/pay/api/exception/mapper/ViolationExceptionMapper.java

The ViolationExceptionMapper maps all validation exceptions. In
general a validation exception is a client error, and of no concern
from an operational perspective. This commit downgrades the log level to
info - the log may still be useful for debugging purposes

PP-5758 Downgrade violation exception log level

---

src/main/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapper.java
src/main/java/uk/gov/pay/api/exception/mapper/CreateRefundExceptionMapper.java

We should only log an error at this point if connector has done something weird. Validation errors etc should just be passed on to user - no log necessary.

PP-5759 Only log error on error from connector

---

src/main/java/uk/gov/pay/api/resources/GetPaymentEventsStrategy.java
src/main/java/uk/gov/pay/api/service/GetPaymentEventsService.java
src/test/java/uk/gov/pay/api/resources/GetPaymentEventsStrategyTest.java

Update get payment events strategy to check Connector before fetching
events from Ledger. This is our "get one" strategy and will make sure
asking for events has no delay when processing a payment in real time.

PP-5742 Payment events use Connector if payment exists

---

src/main/java/uk/gov/pay/api/exception/mapper/CreateAgreementExceptionMapper.java
src/main/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapper.java
src/main/java/uk/gov/pay/api/exception/mapper/CreateRefundExceptionMapper.java
src/main/java/uk/gov/pay/api/exception/mapper/SearchRefundsExceptionMapper.java

From Sentry, these things are logged at error when they should be at info:
GO_CARDLESS_ACCOUNT_NOT_LINKED
CREATE_MANDATE_ACCOUNT_ERROR - There is an error with this account. Please contact support
CREATE_PAYMENT_REFUND_CONNECTOR_ERROR - Stripe refund response (error code: charge_already_refunded
CREATE_PAYMENT_VALIDATION_ERROR - Invalid attribute value: amount. Must be greater than or equal to 1

PP-5809: Log things at info

---

src/test/java/uk/gov/pay/api/it/SearchRefundsResourceIT.java
src/test/java/uk/gov/pay/api/utils/mocks/LedgerMockClient.java
src/test/java/uk/gov/pay/api/utils/mocks/RefundTransactionFromLedgerFixture.java

Why?
To make sure the code path executed in production is properly tested.
What?
Introduce integreation test for refunds search that makes sure the mapping between
dto from Ledger maps properly to public api response for searching refunds.

PP-5869: add integration test for refunds search

---

src/test/java/uk/gov/pay/api/it/ResourcesFilterITestBase.java
src/test/java/uk/gov/pay/api/it/ResourcesFilterRateLimiterIT.java

Why?
The search after the code cleanup will solely go through the ledger, so all the
references to the connector in this context should be removed.
Changes:
* replace connector mock with ledger one for rate limiting integration test of the
search endpoint

[PP-5869] replace connector mock with ledger when search in rate limit test

---

src/test/java/uk/gov/pay/api/it/PaymentResourceITestBase.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchIT.java

Why?
Changes:
* add ledger equivalent tests for all the payment search scenarios (that make sense)
* add missing mock reset for ledger

[PP-5869] update search integration tests to cover ledger paths

---

src/test/java/uk/gov/pay/api/it/GetPaymentIT.java
src/test/java/uk/gov/pay/api/it/PaymentResourceITestBase.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchIT.java
src/test/java/uk/gov/pay/api/utils/mocks/LedgerMockClient.java

Why?
Changes:
* add and refactor methods to mock ledger client
* add ledger equivalent of tests for get payment and payment events (part one)

[PP-5869] first part of ledger integration tests for payment resource

---

src/test/java/uk/gov/pay/api/it/GetPaymentIT.java
src/test/java/uk/gov/pay/api/utils/mocks/LedgerMockClient.java
src/test/java/uk/gov/pay/api/utils/mocks/TransactionEventFixture.java
src/test/java/uk/gov/pay/api/utils/mocks/TransactionFromLedgerFixture.java

Why?
Changes:
* add ledger equivalent of tests for get payment and payment events (part two)

[PP-5869] second part of ledger integration tests for payment resource

---

src/main/java/uk/gov/pay/api/clients/ExternalServiceClient.java
src/main/java/uk/gov/pay/api/service/CancelPaymentService.java
src/main/java/uk/gov/pay/api/service/CapturePaymentService.java
src/main/java/uk/gov/pay/api/service/ConnectorService.java
src/main/java/uk/gov/pay/api/service/CreatePaymentService.java
src/test/java/uk/gov/pay/api/clients/ExternalServiceClientTest.java
src/test/java/uk/gov/pay/api/service/CancelPaymentServiceTest.java
src/test/java/uk/gov/pay/api/service/CapturePaymentServiceTest.java
src/test/java/uk/gov/pay/api/service/CardPaymentSearchServiceTest.java
src/test/java/uk/gov/pay/api/service/CreatePaymentServiceTest.java
src/test/java/uk/gov/pay/api/service/GetPaymentEventsServiceTest.java
src/test/java/uk/gov/pay/api/service/GetPaymentRefundServiceTest.java
src/test/java/uk/gov/pay/api/service/GetPaymentRefundsServiceTest.java
src/test/java/uk/gov/pay/api/service/GetPaymentServiceLedgerTest.java
src/test/java/uk/gov/pay/api/service/GetPaymentServiceTest.java
src/test/java/uk/gov/pay/api/service/SearchRefundsServiceTest.java

This is so we can trace requests from publicapi to calls to downstream services
such as connector in splunk.
Note PP-5761 only covers connector so i haven't done anything for calls to direct-debit-connector.

PP-5761: Add X-Request-Id header to requests

---

pom.xml
src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/filter/RestClientLoggingFilter.java
src/test/java/uk/gov/pay/api/filter/RestClientLoggingFilterTest.java

The MDC value is actually "x_request_id" which is set in
https://github.com/alphagov/pay-java-commons/blob/master/utils/src/main/java/uk/gov/pay/commons/utils/logging/LoggingFilter.java.

PP-5761: Send X-Request-Id properly to downstream calls

---

src/test/java/uk/gov/pay/api/service/SearchRefundsServiceTest.java
src/test/resources/pacts/publicapi-ledger-search-refunds-with-page-and-display-when-no-refunds-exist.json

- Adds a pact test to ensure that searchs with 'null' (but still valid)
responses still have pagination when they are returned from ledger.

PP-5868 Pact ensures null searches have pagination

---

src/main/java/uk/gov/pay/api/app/config/PublicApiConfig.java
src/main/java/uk/gov/pay/api/model/search/card/RefundForSearchRefundsResult.java
src/main/java/uk/gov/pay/api/resources/GetOnePaymentStrategy.java
src/main/java/uk/gov/pay/api/resources/GetPaymentEventsStrategy.java
src/main/java/uk/gov/pay/api/resources/GetPaymentRefundStrategy.java
src/main/java/uk/gov/pay/api/resources/GetPaymentRefundsStrategy.java
src/main/java/uk/gov/pay/api/resources/LedgerOrConnectorStrategyTemplate.java
src/main/java/uk/gov/pay/api/resources/PaymentRefundsResource.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/resources/config/config.yaml
src/test/java/uk/gov/pay/api/it/ResourcesFilterITestBase.java
src/test/java/uk/gov/pay/api/resources/GetOnePaymentStrategyTest.java
src/test/java/uk/gov/pay/api/resources/GetPaymentEventsStrategyTest.java
src/test/java/uk/gov/pay/api/resources/GetPaymentRefundStrategyTest.java
src/test/java/uk/gov/pay/api/resources/GetPaymentRefundsStrategyTest.java
src/test/resources/config/empty-elevated-accounts-test-config.yaml
src/test/resources/config/test-config.yaml

Why? The flag has been used to switch public api to use ledger. Given the
changes have been there for a while, now it's time to remove the feature
flag. It's been decided to leave the `X-Ledger` header to allow ad-hoc
change to public api behaviour (local curl-ing for testing)
Changes:
* remove feature flag
* remove usage of the feature flag from the LedgerOrConnectorStrategyTemplate
* clean up the tests (for feature flag behaviour)
* clean up dependencies in remaining strategies
* parametrize strategy unit tests

[PP-5771] remove alwaysUseFutureStrategy feature flag

---

src/main/java/uk/gov/pay/api/resources/GetOnePaymentStrategy.java
src/main/java/uk/gov/pay/api/resources/GetPaymentEventsStrategy.java
src/main/java/uk/gov/pay/api/resources/GetPaymentRefundStrategy.java
src/main/java/uk/gov/pay/api/resources/GetPaymentRefundsStrategy.java
src/main/java/uk/gov/pay/api/resources/LedgerOrConnectorStrategyTemplate.java
src/test/java/uk/gov/pay/api/it/GetPaymentIT.java
src/test/java/uk/gov/pay/api/it/PaymentRefundsResourceIT.java
src/test/java/uk/gov/pay/api/it/PaymentResourceITestBase.java
src/test/java/uk/gov/pay/api/resources/GetOnePaymentStrategyTest.java
src/test/java/uk/gov/pay/api/resources/GetPaymentEventsStrategyTest.java
src/test/java/uk/gov/pay/api/resources/GetPaymentRefundStrategyTest.java
src/test/java/uk/gov/pay/api/resources/GetPaymentRefundsStrategyTest.java

Why?
Apart from removing feature flag, it's important to update the actual strategies
to use future strategy by default now.
These changes introduce "connector-only" strategy and swaps the behaviour between
default and future strategy (default becomes connector only and future becomes default strategy).

[PP-5771] update strategies to make future strategy the default one

---

src/main/java/uk/gov/pay/api/service/LedgerService.java

- Add MediaType `json` to search for refunds from ledger, as ledger now supports both json and csv on same endpoint (https://github.com/alphagov/pay-ledger/pull/470)

PP-5970 Accept header for search ledger refunds

---

src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/exception/mapper/CreateRefundExceptionMapper.java
src/main/java/uk/gov/pay/api/exception/mapper/GetEventsExceptionMapper.java
src/main/java/uk/gov/pay/api/exception/mapper/GetRefundExceptionMapper.java
src/main/java/uk/gov/pay/api/exception/mapper/GetRefundsExceptionMapper.java
src/main/java/uk/gov/pay/api/filter/RateLimiterKey.java
src/main/java/uk/gov/pay/api/validation/CardExpiryValidator.java
src/main/java/uk/gov/pay/api/validation/MaxLengthValidator.java
src/main/java/uk/gov/pay/api/validation/SearchValidator.java
src/test/java/uk/gov/pay/api/filter/RateLimiterFilterTest.java
src/test/java/uk/gov/pay/api/filter/ratelimit/RedisRateLimiterTest.java
src/test/java/uk/gov/pay/api/json/CreateCardPaymentRequestDeserializerTest.java
src/test/java/uk/gov/pay/api/json/RequestJsonParserTest.java
src/test/java/uk/gov/pay/api/model/search/directdebit/DirectDebitSearchMandatesParamsTest.java
src/test/java/uk/gov/pay/api/service/ConnectorUriGeneratorTest.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java
src/test/java/uk/gov/pay/api/utils/mocks/TransactionFromLedgerFixture.java

Changes:
* remove redundant casting
* remove redundant `toString` call
* remove unnecessary boxing (valueOf -> parseInt)
* remove redundant escape sequence from regexp
* chain append instead of using string concatenation
* remove redundant `throws` clause
* remove redundant logger placeholders
* remove unused [test] methods and variables

[BAU] code clean-up (cont)

---

pom.xml
src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/app/config/PublicApiConfig.java
src/main/java/uk/gov/pay/api/validation/CardFirstSixDigitsValidator.java
src/main/java/uk/gov/pay/api/validation/CardLastFourDigitsValidator.java
src/main/java/uk/gov/pay/api/validation/CardTypeValidator.java

- Upgrades dropwizard to v2.0.0
- Added `dropwizard-dependencies` as parent as v2.0.0 upgrade doesn't specify transitive dependency versions anymore https://www.dropwizard.io/en/release-2.0.x/manual/upgrade-notes/upgrade-notes-2_0_x.html
We can also include BOM for transitive dependency versions but versions can't be overridden and we may end up with multiple revisions of same library. For example, `jackson-version` current used is `2.10.2` but dropwizard uses `2.10.1`
- Upgraded dropwizard-sentry library to latest version as container might fail to start with error `java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableList org.dhatim.dropwizard.sentry.logging.SentryAppenderFactory.getFilterFactories()
- Upgraded pay-java-commons library which is on dropwizard v2.0.0 and …

PP-6001 Upgrade dropwizard

---

src/main/java/uk/gov/pay/api/json/RequestJsonParser.java
src/main/java/uk/gov/pay/api/model/CreateCardPaymentRequest.java
src/main/java/uk/gov/pay/api/model/CreateCardPaymentRequestBuilder.java
src/main/java/uk/gov/pay/api/model/Internal.java
src/test/java/uk/gov/pay/api/it/CreatePaymentIT.java
src/test/java/uk/gov/pay/api/json/CreateCardPaymentRequestDeserializerTest.java
src/test/java/uk/gov/pay/api/json/RequestJsonParserTest.java
src/test/java/uk/gov/pay/api/utils/mocks/BaseConnectorMockClient.java
src/test/java/uk/gov/pay/api/utils/mocks/CreateChargeRequestParams.java

- Allowed new JSON object `internal` with field source on `create` payment payload
- Validation for source field
- Updated relevant tests

PP-6019 Source field for create payment endpoint

---

Jenkinsfile

The docker registry v1 API, which is used by the spotify docker-client
maven plugin that we use has been switched off.
https://www.docker.com/blog/registry-v1-api-deprecation/
We need to use the v2 API, which test containers use.
In the meantime, pull the docker image prior to running tests on CI so
the build will pass

BAU Pull redis docker image prior to CI build

---

src/test/java/uk/gov/pay/api/it/PaymentResourceSearchIT.java

Description:
- Moves SearchPaymentsIT.shouldNotFindAnyChargeByANonExistingReference from pay-end-to-end 'publicapi' to PaymentResourceSearchIT

PP-6010 Add test for not finding charge for nonexisting reference

---

src/test/java/uk/gov/pay/api/service/CardPaymentSearchServiceTest.java
src/test/resources/pacts/publicapi-ledger-search-payments-page-not-found.json

Add a pact test to verify that ledger returns a 404 when a search request is made with a page number that does not exist.
This will allow us to remove an end-to-end test checking this as we already have an integration test to verify that we handle a 404 response from ledger correctly.

PP-6010 Add Pact test for searching ledger with a non existent page no

---

src/test/java/uk/gov/pay/api/it/SearchRefundsResourceIT.java
src/test/java/uk/gov/pay/api/utils/mocks/LedgerMockClient.java

Add an integration test to check we return the correct response when ledger returns a 404 when searching refunds, which indicates that the requested page was not found.

PP-6010 Add search refunds page not found integration test

---

src/test/java/uk/gov/pay/api/service/SearchRefundsServiceTest.java
src/test/resources/pacts/publicapi-ledger-search-refunds-page-not-found.json

Add a pact test to verify that calling ledger to search for refunds with a page number that doesn't exist returns a 404 response.

PP-6010 Add pact test for search Refunds for page not found

---

manifest.yml

So that they are consistent with our naming conventions in other
projects

PP-6031 Correct var names in manifest

---

src/main/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapper.java
src/main/java/uk/gov/pay/api/model/PaymentError.java
src/test/java/uk/gov/pay/api/it/CreatePaymentIT.java
src/test/java/uk/gov/pay/api/utils/mocks/BaseConnectorMockClient.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java
src/test/java/uk/gov/pay/api/utils/mocks/CreateChargeRequestParams.java

Assign error code for moto payment not enabled
If someone tries to send a MOTO payment but their account has not had MOTO
payments enabled, then they will get an error message.

PP-6077: Create moto payment when not enabled

---

src/test/java/uk/gov/pay/api/service/CreatePaymentServiceTest.java
src/test/resources/pacts/publicapi-connector-create-payment-with-minimum-fields.json
src/test/resources/pacts/publicapi-connector-create-payment.json

Description:
- Set moto to false in publicapi-connector-create-payment-with-minimum-fields
- Set moto to true in publicapi-connector-create-payment as that test includes all optional fields
- Run Pact tests locally

PP-6077 Modify Pact Tests for creating MOTO Payments

---

src/test/java/uk/gov/pay/api/service/GetPaymentServiceTest.java
src/test/resources/pacts/publicapi-connector-get-payment-with-awaiting-capture-request-state.json
src/test/resources/pacts/publicapi-connector-get-payment-with-corporate-surcharge.json
src/test/resources/pacts/publicapi-connector-get-payment-with-delayed-capture-true.json
src/test/resources/pacts/publicapi-connector-get-payment-with-fee-and-net-amount.json
src/test/resources/pacts/publicapi-connector-get-payment-with-gateway-transaction-id.json
src/test/resources/pacts/publicapi-connector-get-payment-with-metadata.json

Description:
- Adds moto field to get payment pact tests. No real need to add a get payment with moto as a previous pact test checks whether a moto payment can be created

PP-6077 - Modify Pact for get payment moto field

---

manifest.yml
src/main/resources/env-map.yml

Add the (modified) env-map buildpack to allow binding VCAP_SERVICES data to app environment variables. The env-map.yml file is added to `./src/main/resources` to ensure this is copied into the built .jar and subsequently made available to the env-map buildpack. In this case the `app-catalog` user provided service is bound to the app to supply URLs of connected services.
Deploy manually:
`cf push --vars-file path/to/pay-omnibus/paas/env_variables/staging.yml --var space=staging`
View configured env vars:
`cf ssh publicapi -c "/tmp/lifecycle/shell /home/vcap/app 'env | sort'" | grep URL`

PP-6085: Add env-map buildpack to support user-provided services

---

src/test/resources/pacts/publicapi-ledger-search-payments-page-not-found.json

Reuse the "a payment transaction exists" state.

bau: Consolidate search payment transaction pact

---

src/main/resources/env-map.yml

Publicapi relies on a fully qualified url/route to be specified in the PUBLIC_AUTH_URL env var, instead of just the hostname. This route has been added to the app-catalog user-provided service (see alphagov/pay-omnibus#85). This PR maps the new url to the public auth url env var.
The app-catalog service has been updated. After rebuilding and restaging publicapi it should pick up the new environment variable.

PP-6085: Map fully qualified url to PUBLIC_AUTH_URL env var

---

src/main/resources/env-map.yml

Add missing hmac secret mapping to env-map.yml. This change ensures the secret is mapped to an environment variable from the user-provided "secret" CF service.

PP-6127: Add missing hmac secret mapping to env-map.yml

---

manifest.yml

Removes manifest vars which are defined in PaaS using terraform and don't need to be interpolated into the manifest.yml file by Concourse.
Redis will be added as a bound service in a later story.

PP-6146: Remove manifest vars configured by terraform

---

manifest.yml

The app won't start if the Redis url is an empty variable, although it will run if the url is invalid.

PP-6146: Update redis placeholder manifest var

---

src/test/java/uk/gov/pay/api/filter/RateLimiterFilterTest.java
src/test/java/uk/gov/pay/api/filter/ratelimit/LocalRateLimiterTest.java
src/test/java/uk/gov/pay/api/filter/ratelimit/RedisRateLimiterTest.java
src/test/java/uk/gov/pay/api/json/CreateCardPaymentRequestDeserializerTest.java
src/test/java/uk/gov/pay/api/json/CreatePaymentRefundRequestDeserializerTest.java
src/test/java/uk/gov/pay/api/ledger/service/TransactionSearchServiceTest.java
src/test/java/uk/gov/pay/api/service/CardPaymentSearchServiceTest.java
src/test/java/uk/gov/pay/api/service/SearchRefundsServiceTest.java
src/test/java/uk/gov/pay/api/validation/RefundSearchValidatorTest.java

Part of upgrading to Junit5
- Removes deprecated ExpectedException rule and replaces with `assertThrows`

PP-6708 Remove deprecated ExpectedException rule

---

pom.xml
src/test/java/uk/gov/pay/api/app/config/StringToListConverterTest.java
src/test/java/uk/gov/pay/api/filter/RateLimiterKeyTest.java
src/test/java/uk/gov/pay/api/filter/ratelimit/RateLimitManagerTest.java
src/test/java/uk/gov/pay/api/json/CreateCardPaymentRequestDeserializerTest.java
src/test/java/uk/gov/pay/api/resources/GetOnePaymentStrategyTest.java
src/test/java/uk/gov/pay/api/resources/GetPaymentEventsStrategyTest.java
src/test/java/uk/gov/pay/api/resources/GetPaymentRefundStrategyTest.java
src/test/java/uk/gov/pay/api/resources/GetPaymentRefundsStrategyTest.java
src/test/java/uk/gov/pay/api/utils/PathHelperTest.java

- Uses Junit5 `junit-jupiter-params` library for parameterised unit tests as `JUnitParams` library does support Junit5.
- Although this feature is experimental it is more likely to be become stable. see https://github.com/junit-team/junit5/issues/1093#issuecomment-503590220

PP-6708 Use Junit5 ParamaterisedTest

---

Jenkinsfile

Description:
- Before we can turn off the direct debit smoke test we need to ensure that no pipeline calls it. This ensures that the publicapi Jenkins pipeline doesn't call the direct debit smoke Jenkins function.
- This also ensures that the direct debit portion of the end to end test suit won't be run

PP-6763 - Remove direct debit smoke and end test from publicapi Jenkins pipeline

---

.secrets.baseline
pom.xml
src/test/java/uk/gov/pay/api/it/validation/PaymentResourceMetadataValidationFailuresIT.java

Upgrade Pay Java commons dependency to 1.0.20200911141024, which includes changes to increase the maximum payment metadata value length from 50 characters to 100 characters.
Connector already supports this longer length.
Update `PaymentResourceMetadataValidationFailuresIT` to rely on constants in `ExternalMetadata` rather than repeating limits for the maximum metadata value length etc.

PP-7067 Increase maximum metadata value length from 50 to 100

---

manifest.yml
src/main/resources/env-map.yml

We are no deploying DDConnector into PaaS but for now Publicapi
still requires the url. This is a dummy value so that Publicapi will
start. This can be removed as part of removing DD from Publicapi.
We no longer deploy dd connector and do not provide it's url via the app-catalogue. I've tried this by manually pushing to staging and it works.

PP-7154 Add dummy url for dd connector for PaaS

---

src/main/java/uk/gov/pay/api/model/RefundResponse.java
src/main/java/uk/gov/pay/api/model/ledger/RefundTransactionFromLedger.java
src/main/java/uk/gov/pay/api/model/search/card/RefundForSearchRefundsResult.java
src/test/java/uk/gov/pay/api/it/PaymentRefundsResourceIT.java
src/test/java/uk/gov/pay/api/utils/mocks/RefundTransactionFromLedgerFixture.java

- add settlement_summary to refund responses
- settlement_summary is the same as payments' one but will never have capture details. refunds from connector are always an empty object {}
- add/extend tests

PP-6670 add settlement summary to refunds

---

pom.xml

Remove `jackson-datatype-joda` dependency from the POM because it’s not used.

PP-7229 Remove unused jackson-datatype-joda dependency

---

src/main/java/uk/gov/pay/api/model/CardDetails.java
src/main/java/uk/gov/pay/api/model/search/card/PaymentSearchResponse.java

- Adding this property to relevant classes ensures that no breakage or downtime when introducing new fields to payload on other backend systems.

PP-7208 add json ignore unknown properties

---

pom.xml
src/main/java/uk/gov/pay/api/validation/CardExpiryValidator.java

Replace the current regex for validating card expiry dates with the one from `CardExpiryDate` from Pay Java commons.
The two regexes are not identical. The old one is:
```
(0[1-9]|1[0-2])/\d{2}
```
… while the new one is:
```
(0[1-9]|1[0-2])/([0-9]{2})
```
However, these are equivalent.
Both regexes are identical up to and including the slash. After this, the new regex has parentheses (used for a capturing group) but these don’t actually make any difference to what’s matched.
In Java, the character class `\d` matches only the digits in the range 0 to 9 inclusive, so `\d{2}` and `[0-9]{2}` are equivalent (this is not the case in all languages!).

PP-7242 Use regex from CardExpiryDate to validate card expiry dates

---

.secrets.baseline
src/main/java/uk/gov/pay/api/auth/AccountAuthenticator.java
src/main/java/uk/gov/pay/api/filter/AuthorizationValidationFilter.java
src/main/java/uk/gov/pay/api/model/TokenPaymentType.java
src/main/java/uk/gov/pay/api/model/publicauth/AuthResponse.java
src/test/java/uk/gov/pay/api/auth/AccountAuthenticatorTest.java
src/test/java/uk/gov/pay/api/filter/AuthorizationValidationFilterTest.java
src/test/java/uk/gov/pay/api/it/AuthorisationIT.java
src/test/java/uk/gov/pay/api/utils/PublicAuthMockClient.java

Log at INFO level when a valid API key is used. Log the token_link for the API key, which is returned by public auth.
Log at WARN level when an API key with an invalid checksum is used. Log the IP address the request originates from to help us detect brute force attempts.
Log at WARN level when an invalid API key with a valid checksum is used.
Log at WARN level when a revoked API key is used. Log the token_link for the API key, which is returned by public auth.
Remove logic that maps a non-existent/unknown value for `token_type` returned from public auth to TokenPaymentType.CARD. Public auth will always return a `token_type`, and if it doesn't this will result in a `com.fasterxml.jackson.databind.exc.InvalidFormatException` which will be wrapped in a 500 response. This will show up in …

PP-7104 Log when API keys are used

---

pom.xml
src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/filter/AuthorizationValidationFilter.java

Move the initialisation of filters for the application so that the request id is added to the MDC for logging before the AuthorizationValidationFilter runs.
Fix logging the "remote_address" for the line logged when the API key fails checksum validation so that it logs the client address obtained from the "X-Forwarded-For" header, which is added by the proxies the request passes through.

PP-7104 Fix logging when API key fails checksum

---

src/main/java/uk/gov/pay/api/filter/LoggingMDCRequestFilter.java
src/main/java/uk/gov/pay/api/filter/RateLimiterFilter.java
src/test/java/uk/gov/pay/api/it/ResourcesFilterRateLimiterIT.java

- Added `token_link` and `remote_address` to MDC so these are logged for all log lines.
Changed the priority of RateLimiterFilter so this is invoked after LoggingMDCRequestFilter (which adds keys to MDC)
- Although keys are added to MDC, a few logs below won't have the same as logging happens before/during API authentication and before keys are added to MDC
"POST to /v1/payments began","logger_name":"uk.gov.pay.logging.LoggingFilter" ...
"[] - GET to http://publicauth/v1/api/auth began",  ....
"[] - GET to http://publicauth/v1/api/auth ended - total time 147ms", ...

PP-7429 Add token_link and remote_address to MDC

---

src/main/java/uk/gov/pay/api/filter/RateLimiterFilter.java
src/test/java/uk/gov/pay/api/filter/RateLimiterFilterTest.java

Do not rate limit calls to the healthcheck endpoint. This is used by the
loadbalancer to test if an instance is healthy and a 429 response is considered
unhealthy. This could lead to the loadbalancer incorrectly setting the instance
as unhealthy.
Although we're not sure whether it caused or contributed to an incident where the Publicapi Loadbalancer began returning 503 responses it isn't ideal that we are rate limiting its requests to the `/healthcheck` endpoint.

PP-7526 Do not rate limit calls to healthcheck

---

src/main/java/uk/gov/pay/api/filter/ClearMdcValuesFilter.java

We are observing in our logs that sometimes the remote_address from a previous request seems to be logged even though the MDC should have been cleared at the end of that request.
Additionally clear the MDC at the beginning of the request (it should have no values at this point so we shouldn’t lose anything we want) to see if this makes things better.
with @katstevens

PP-7560 Clear MDC at both the beginning and end of a request

---

src/test/resources/pacts/publicapi-connector-create-telephone-payment-notification.json

We will start checking that this flag is enabled for the account in connector, adding this pact state will mean pact tests will pass when the change in connector to do this is made.

PP-7589 Use pact state for telephone notifications

---

src/main/java/uk/gov/pay/api/resources/telephone/TelephonePaymentNotificationResource.java
src/main/java/uk/gov/pay/api/service/telephone/CreateTelephonePaymentService.java
src/test/java/uk/gov/pay/api/it/telephone/pact/CreateTelephonePaymentServiceTest.java

I found the names of methods and interaction with the service slightly confusing. The reason it's like this is because public api will respond with a 200 or 201 depending on the status code from connector.
Refactored so that the service is responsible for constructing the public api response from the connector response, and returns a Pair of the response and the status code to reply with.

PP-7589 Refactor TelephonePaymentNotificationResource

---

pom.xml
src/main/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapper.java
src/main/java/uk/gov/pay/api/model/PaymentError.java
src/test/java/uk/gov/pay/api/it/telephone/CreateTelephonePaymentIT.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java

Handle connector error when telephone payment notifications are not enabled for the account by responding with a 403 forbidden and a new P error code P0930.

PP-7589 Handle connector error for telephone payments

---

pom.xml
src/main/java/uk/gov/pay/api/json/RequestJsonParser.java
src/test/java/uk/gov/pay/api/json/RequestJsonParserTest.java

When processing a request to create a new card payment via the API, accept `CARD_AGENT_INITIATED_MOTO` as a valid source.

PP-7696 Accept CARD_AGENT_INITIATED_MOTO as created payment source

---

src/main/java/uk/gov/pay/api/ledger/model/TransactionSearchResults.java
src/main/java/uk/gov/pay/api/model/ChargeFromResponse.java
src/main/java/uk/gov/pay/api/model/RefundResponse.java
src/main/java/uk/gov/pay/api/model/TransactionEvents.java
src/main/java/uk/gov/pay/api/model/ledger/RefundTransactionFromLedger.java
src/main/java/uk/gov/pay/api/model/ledger/RefundsFromLedger.java
src/main/java/uk/gov/pay/api/model/ledger/TransactionState.java
src/main/java/uk/gov/pay/api/model/publicauth/AuthResponse.java
src/main/java/uk/gov/pay/api/model/search/card/SearchRefundsResults.java
src/main/java/uk/gov/pay/api/model/telephone/CreateTelephonePaymentRequest.java
src/main/java/uk/gov/pay/api/model/telephone/Supplemental.java
src/main/java/uk/gov/pay/api/model/telephone/TelephonePaymentResponse.java
src/main/java/uk/gov/pay/api/resources/MandatesResource.java
src/main/java/uk/gov/pay/api/resources/PaymentRefundsResource.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/resources/SearchRefundsResource.java
src/main/java/uk/gov/pay/api/resources/directdebit/DirectDebitPaymentsResource.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentRefundSearchJsonFixture.java
src/test/java/uk/gov/pay/api/utils/mocks/RefundTransactionFromLedgerFixture.java
src/test/java/uk/gov/pay/api/utils/mocks/TransactionEventFixture.java
src/test/java/uk/gov/pay/api/utils/mocks/TransactionFromLedgerFixture.java

- Update deprecated `PropertyNamingStrategy` class to `PropertyNamingStrategies`
- Remove fully qualified annotation `@io.swagger.v3.oas.annotations.responses.ApiResponse` as we no longer have swagger v2 annotations

PP-7896 Update deprecated class 

---

pom.xml
src/main/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapper.java
src/main/java/uk/gov/pay/api/model/PaymentError.java
src/test/java/uk/gov/pay/api/it/CreatePaymentIT.java
src/test/java/uk/gov/pay/api/model/PaymentErrorTest.java
src/test/java/uk/gov/pay/api/resources/PaymentsResourceCreatePaymentTest.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java

Description:
- Return 403 and error code of P0940 with the description message when we receive 400 from Connector with the error identifier as 'ACCOUNT_NOT_LINKED_WITH_PSP' and the message as 'Payment provider details are not configured on this account'
- Removed 'public' from PaymentErrorTest as methods don't need to be in JUnit 5
- Removed unused emocks in PaymentsResourceCreatePaymentTest

PP-8210 - Return 403 when PSP not linked with gateway account

---

src/test/resources/pacts/publicapi-connector-create-payment-with-credentials-in-created-not-allowed.json

Description:
- I re-used the state as I only needed a gateway_account_credential in a CREATED state
- Checks if Connector returns 400 when the gateway_account_credential is in a CREATED state

PP-8210 - Pact test for gateway account credentials in created

---

README.md
src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/resources/SecuritytxtResource.java

Make `/.well-known/security.txt` and `/security.txt` redirect to https://vdp.cabinetoffice.gov.uk/.well-known/security.txt.
Update `README.md` to reference the Cabinet Office CDIO Cyber Security vulnerability disclosure policy and security.txt file rather than the GOV.UK Pay security vulnerability email address.

PP-8095 Add security.txt file

---

src/main/java/uk/gov/pay/api/resources/SecuritytxtResource.java

Send a `Cache-Control: no-cache` header and an `Expires` header with the current time when redirecting from `/.well-known/security.txt` and `/security.txt`.
Without these headers, clients will use heuristics to decide how long to cache the response for, which could be a problem if we want to update our `security.txt`.

PP-8095 Make security.txt require cache revalidation every request

---

src/main/java/uk/gov/pay/api/model/CardPayment.java
src/main/java/uk/gov/pay/api/model/CreateCardPaymentRequest.java

The payment reference can come from user input for a payment link payment. We've seen users mistakenly entering their card number in the reference field.
It is a lot of effort to remove log lines from all places when this happens, so stop logging the reference in all cases. We can still find out the reference or search for payments by the reference in toolbox.

PP-8415 Stop logging payment reference

---

src/main/java/uk/gov/pay/api/filter/AuthorizationValidationFilter.java

- String.equals() doesn't implement a constant-time algorithm for comparing inputs. As a result, an attacker may be able to run a timing attack that can forge a valid signature for an arbitrary body.

PP-8394 refactor signature comparison to mitigate timing attack

---

src/main/java/uk/gov/pay/api/filter/ratelimit/RateLimitManager.java
src/main/java/uk/gov/pay/api/filter/ratelimit/RedisRateLimiter.java
src/test/java/uk/gov/pay/api/filter/ratelimit/RateLimitManagerTest.java
src/test/java/uk/gov/pay/api/filter/ratelimit/RedisRateLimiterTest.java

- Rate limits requests for low traffic accounts as per the configuration (RATE_LIMITER_LOW_TRAFFIC_ACCOUNTS and related env variables).
- Number of post requests are defaulted to 1 request per minute and per bucket (capture, create and the rest)
- Number of get requests allowed will be the same as the rate limit for standard accounts (4500 requests per minute which is equivalent to 75 req per second) but rate limit interval is per minute.

PP-8550 Rate limit requests for low traffic accounts

---

Jenkinsfile

CI Jenkins no longer needs to deploy Publicapi.
Interestingly publicapi didn't seem to be checking pact compatibility before deployment.

PP-8695 Remove Jenkins deploy step

---

src/main/java/uk/gov/pay/api/filter/ratelimit/RedisRateLimiter.java

Description:
- As described in the kick off the lettuce library used to talk to Redis already has multithreading support so no concurrency issues will arise
- We are removing the synchronization keyword to prevent publicapi processing requests one at a time in the event the Redis cluster goes offline

PP-8844 - Remove synchronization for Redis calls

---

.secrets.baseline
src/main/java/uk/gov/pay/api/app/config/PublicApiModule.java
src/main/java/uk/gov/pay/api/app/config/RedisConfiguration.java
src/main/resources/config/config.yaml
src/test/resources/config/empty-elevated-accounts-test-config.yaml
src/test/resources/config/empty-low-traffic-accounts-test-config.yaml
src/test/resources/config/test-config.yaml

Description:
- Added support to specify a socket timeout. Command timeout is when a TCP connection is established to Redis and we are waiting for Redis to process the command. Socket timeout is when a TCP connection isn't established and we are waiting for Redis to respond.
- To test that the environment variables do what they are defined I set `REDIS_COMMAND_TIMEOUT=20s` and `REDIS_CONNECT_TIMEOUT=20s`.
- I spun up our local environment and pointed publicapi to a local Redis docker container
- I ran:
```
seq 1 5000 | xargs -I {} -P 500 curl -s -o /dev/null -w "{} = connect %{time_connect} total %{time_total} status_code %{http_code}\n" -H "Authorization: Bearer <api token from above>" http://localhost:9100/v1/payments/<payment id from above>
```
-  which began making requests to …

PP-8844 - Add connect and socket timeout values for Redis

---

src/test/java/uk/gov/pay/api/service/GetPaymentServiceTest.java
src/test/resources/pacts/publicapi-connector-get-capturable-payment.json
src/test/resources/pacts/publicapi-connector-get-created-payment.json
src/test/resources/pacts/publicapi-connector-get-payment-with-fee-and-net-amount.json

The pact for getting a charge from connector simulates a scenario
where the payment is in "AWAITING CAPTURE REQUEST" status so that it
can check that a link to capture the payment exists.
It also checks for a fee and net amount, but we would not expect a
fee or net amount to exist on a charge in this state. As a result,
connector is returning a negative `net_amount` as we would expect for
failed payments which have a fee, whereas the pact test is expecting a
positive `net_amount` which will only be returned if the charge is in
a `CAPTURED` status.
Remove the check for `fee` and `net_amount` fields on this pact. Rename
the pact to indicate that it is for a charge in the capturable state.
Add a separate pact test that uses a connector state that has a captured
payment with fees to check the …

PP-8945 Allow connector pact tests to pass

---

src/main/java/uk/gov/pay/api/filter/ratelimit/RedisRateLimiter.java

Although dropwizard metrics says that timers measure time durations in
nanoseconds, the actual metric value emitted to graphite is determined by the
configuration of the `GraphiteReporter`. Ours is configured in the
[`initialiseMetrics`][1] method.
The setting which controls how time intervals/durations are emitted can be
controlled by the [`convertDurationsTo`][2] method of the builder. Since
we don't specify that when we set this up, it falls back to the default, which
[appears to be Milliseconds][3].
Since the time unit is not controlled at the point that the metric is emitted,
it's better not to specify it in the name of the metric, as it risks causing
confusion at best. All time metrics will use the same unit controlled by the
configuration of the GraphiteReporter.
Therefore, remove …

BAU remove time unit from redis metrics

---

src/main/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapper.java
src/main/java/uk/gov/pay/api/model/RequestError.java
src/main/java/uk/gov/pay/api/model/links/PaymentLinks.java
src/test/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapperTest.java
src/test/java/uk/gov/pay/api/it/CreatePaymentIT.java
src/test/java/uk/gov/pay/api/it/GetPaymentIT.java
src/test/java/uk/gov/pay/api/service/CreatePaymentServiceTest.java
src/test/java/uk/gov/pay/api/service/GetPaymentServiceTest.java
src/test/java/uk/gov/pay/api/utils/mocks/BaseConnectorMockClient.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java
src/test/resources/pacts/publicapi-connector-create-payment-with-authorisation-mode-moto-api-not-allowed.json
src/test/resources/pacts/publicapi-connector-get-motoapi-created-payment.json

- Updated the PaymentLinks model to handle `auth_url_post` links when using the `moto_api` authorisation mode.
- Updated CreateChargeExceptionMapper to handle new error state when gateway acounts do not have `moto_api` enabled.
- Added new error identifier for bad authorisation permissions
- Added new Pact tests between PublicAPI and Connector to model scenarios involving charge creation and retrieval using the `moto_api` authorisation mode.

PP-9390 map connector responses with authorisation mode `moto_api`

---

src/main/java/uk/gov/pay/api/model/links/PaymentLinks.java
src/main/java/uk/gov/pay/api/model/links/PaymentWithAllLinks.java
src/main/java/uk/gov/pay/api/service/CreatePaymentService.java
src/main/java/uk/gov/pay/api/service/GetPaymentService.java
src/main/java/uk/gov/pay/api/service/PublicApiUriGenerator.java
src/test/java/uk/gov/pay/api/it/CreatePaymentIT.java
src/test/java/uk/gov/pay/api/it/GetPaymentIT.java
src/test/java/uk/gov/pay/api/model/PaymentTest.java
src/test/java/uk/gov/pay/api/resources/PaymentsResourceCreatePaymentTest.java
src/test/java/uk/gov/pay/api/service/CreatePaymentServiceTest.java
src/test/java/uk/gov/pay/api/service/GetPaymentServiceTest.java

- Updated the `PaymentWithAllLinks` class to construct responses with the correct payment authorisation URI when creating or retrieving payment requests

PP-9390 Use publicapi authorisation endpoint for auth_url_post links

---

.secrets.baseline
src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/filter/AuthorizationValidationFilter.java
src/test/java/uk/gov/pay/api/filter/AuthorizationValidationFilterTest.java
src/test/java/uk/gov/pay/api/resources/AuthorisationResourceIT.java

The MOTO payments authorisation API should not require an Authorisation header with the bearer token to be present. We instead require a one_time_token in the request body to authorise the request.
Add an exclusion to the filter that checks for Authorisation header for the URL "/v1/auth". It is not possible to add this exclusion in the URL pattern we provide for the filter when registering it in the app module, so instead hardcode this exclusion into the filter.

PP-9407 Don't require Authorisation header for auth API

---

src/main/java/uk/gov/pay/api/exception/mapper/AuthorisationRequestExceptionMapper.java
src/test/java/uk/gov/pay/api/exception/mapper/AuthorisationRequestExceptionMapperTest.java

When the connector /v1/api/charges/authorise API returns an error response with error_identifier: AUTHORISATION_TIMEOUT, map this to the P0050 status code with a generic description of "There was an error authorising the payment" matching the description for other authorisation errors.

PP-9503 Add error mapper for AUTHORISATION_TIMEOUT error

---

src/main/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapper.java
src/main/java/uk/gov/pay/api/exception/mapper/CreateRefundExceptionMapper.java
src/main/java/uk/gov/pay/api/service/CreateRefundService.java
src/test/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapperTest.java
src/test/java/uk/gov/pay/api/exception/mapper/CreateRefundExceptionMapperTest.java
src/test/java/uk/gov/pay/api/service/CreateRefundServiceTest.java
src/test/resources/pacts/publicapi-connector-create-refund-for-disabled-account.json

* New CreateChargeException mapping
* New pact test
* Uses same message and error code as used for create payment request when account is disabled

PP-9587: Map account disabled error from Connector for refunds

---

src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/service/PaymentSearchService.java
src/test/java/uk/gov/pay/api/it/GetPaymentIT.java
src/test/java/uk/gov/pay/api/it/PaymentResourceSearchIT.java
src/test/java/uk/gov/pay/api/resources/PaymentsResourceCreatePaymentTest.java

As per the IT health check (ITHC) report, add no cache directives for endpoints that
return sensitive data.
The ITHC report recommends to add `Cache-control: no-store` and `Pragma: no-cache` to `/v1/payments` and `/v1/payments/{paymentId}` (see JIRA ticket).

PP-9758: Add no cache directive

---

src/main/java/uk/gov/pay/api/json/RequestJsonParser.java
src/main/java/uk/gov/pay/api/model/CreateCardPaymentRequest.java
src/main/java/uk/gov/pay/api/model/CreateCardPaymentRequestBuilder.java
src/main/java/uk/gov/pay/api/model/RequestError.java
src/main/java/uk/gov/pay/api/service/CreatePaymentService.java
src/test/java/uk/gov/pay/api/it/CreatePaymentIT.java
src/test/java/uk/gov/pay/api/json/RequestJsonParserTest.java
src/test/java/uk/gov/pay/api/utils/mocks/BaseConnectorMockClient.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java
src/test/java/uk/gov/pay/api/utils/mocks/CreateChargeRequestParams.java

Allows agreement authorisation mode.
Add all of the various additional builder/ parser/ validator params needed to pass a string through from the api to internal connector call.
Fix the test assertions so that it's validating the value would be propagated through to connector.
When creating a new payment, if `"authorisation_mode": "agreement"`, require an `"agreement_id"` (which must have a string value).
Conversely, if any other `"authorisation_mode"` is specified (or none at all), reject the request if it contains an `"agreement_id"`.
(The latter change will prevent surprising things happening if both `"set_up_agreement"` and `"agreement_id"` are specified.)
with @alexbishop1

PP-9812 Send recurring payment request to connector

---

src/main/java/uk/gov/pay/api/agreement/service/AgreementService.java
src/main/java/uk/gov/pay/api/app/PublicApi.java
src/test/java/uk/gov/pay/api/service/AgreementServiceTest.java

When cancelling an agreement, check that connector returns the expected 204 response, throwing a `CancelAgreementException` if it does not.
Ensure the connector response is always closed.
Register `CancelAgreementExceptionMapper`.

PP-9784 Check agreement cancelled successfully by connector

---

pom.xml
src/main/java/uk/gov/pay/api/exception/mapper/CreateRefundExceptionMapper.java
src/main/java/uk/gov/pay/api/model/RequestError.java
src/test/java/uk/gov/pay/api/exception/mapper/CreateRefundExceptionMapperTest.java

Handle an error response returned by connector with identifier REFUND_NOT_AVAILABLE_DUE_TO_DISPUTE when attempting to create a refund to return a specific error.

PP-9671 Return error for refund unavailable for disputed payment

---

src/main/java/uk/gov/pay/api/ledger/model/SearchResults.java
src/main/java/uk/gov/pay/api/ledger/resource/TransactionsResource.java
src/main/java/uk/gov/pay/api/ledger/service/TransactionSearchService.java
src/test/java/uk/gov/pay/api/ledger/service/TransactionSearchServiceTest.java

Transmogrify `TransactionSearchResults` into `SearchResults<E>` so we can use it for other kinds of search results.
with @sfount

PP-9545 Make TransactionSearchResults generic

---

src/main/java/uk/gov/pay/api/agreement/resource/AgreementsApiResource.java
src/main/java/uk/gov/pay/api/service/LedgerService.java
src/test/java/uk/gov/pay/api/it/CreateAgreementIT.java
src/test/java/uk/gov/pay/api/utils/mocks/LedgerMockClient.java

Require Ledger to check the event stream and make sure the
projection for that agreement is up to date. We should now be able to
rely on our GET agreement being up to date with the work done by any
other service.
Use the event store as the source of truth, get a consistent/ up to date agreement from the event store
after confirmation that the agreement has been correctly created.

PP-9545 Pass consistent headers to get agreement

---

src/main/java/uk/gov/pay/api/ledger/service/LedgerUriGenerator.java
src/main/java/uk/gov/pay/api/service/LedgerService.java
src/test/resources/pacts/publicapi-ledger-get-payment-refunds.json

- Query payment refunds by transaction_type as the ledger endpoint /v1/transaction/{externalId}/transaction without query params will return refunds as well as disputes

PP-9662 Query payment refunds by transaction_type

---

src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/exception/mapper/SearchDisputeExceptionMapper.java
src/main/java/uk/gov/pay/api/model/RequestError.java
src/main/java/uk/gov/pay/api/resources/SearchDisputesResource.java
src/main/java/uk/gov/pay/api/service/DisputesSearchParams.java
src/main/java/uk/gov/pay/api/service/LedgerService.java
src/main/java/uk/gov/pay/api/service/SearchDisputesService.java
src/main/java/uk/gov/pay/api/validation/DisputeSearchValidator.java
src/test/java/uk/gov/pay/api/it/SearchDisputesResourceIT.java
src/test/java/uk/gov/pay/api/service/SearchDisputesServiceTest.java
src/test/java/uk/gov/pay/api/utils/mocks/DisputeTransactionFromLedgerFixture.java
src/test/java/uk/gov/pay/api/utils/mocks/LedgerMockClient.java
src/test/java/uk/gov/pay/api/validation/DisputeSearchValidatorTest.java
src/test/resources/pacts/publicapi-ledger-search-disputes_by_state.json

- add a new resource endpoint `/v1/disputes`
- implement endpoint to use SearchDisputesService
- there is double re-writing of the incoming data. we need to re-write incoming query param `status` to `state` as that is what Ledger expecting. also re-write the return data from Ledger, the links  changed from `state` to `status`
- add tests

PP-9675 implement search disputes endpoint

---

src/main/java/uk/gov/pay/api/exception/mapper/CancelAgreementExceptionMapper.java
src/main/java/uk/gov/pay/api/exception/mapper/JsonProcessingExceptionMapper.java
src/main/java/uk/gov/pay/api/exception/mapper/SearchAgreementsExceptionMapper.java
src/main/java/uk/gov/pay/api/json/RequestJsonParser.java
src/main/java/uk/gov/pay/api/model/RequestError.java
src/main/java/uk/gov/pay/api/validation/AgreementSearchValidator.java
src/test/java/uk/gov/pay/api/it/AgreementsIT.java
src/test/java/uk/gov/pay/api/it/CreateAgreementIT.java
src/test/java/uk/gov/pay/api/json/CreateAgreementRequestDeserializerTest.java

Update the error codes for agreements API calls to match those we’ve agreed upon (which is essentially the same as the equivalent P0xxx error code for payments but P2xxx instead).

PP-9498 Update error codes for agreements API calls

---

src/main/java/uk/gov/pay/api/agreement/model/AgreementLedgerResponse.java
src/test/java/uk/gov/pay/api/it/AgreementsIT.java
src/test/java/uk/gov/pay/api/it/CreateAgreementIT.java
src/test/java/uk/gov/pay/api/utils/mocks/AgreementFromLedgerFixture.java
src/test/java/uk/gov/pay/api/utils/mocks/LedgerMockClient.java

It’s possible for an agreement to not have a payment instrument yet. We have unintentionally flip-flopped between including
`"payment_instrument": null` or nothing in the agreement response if this is the case.
We have now decided to not include `"payment_instrument": null` when there is no payment instrument for the agreement. The rationale for including it was it alerts services that there may sometimes be a payment instrument. However, we wish to use the agreements model for other kinds of recurring payments in the future and our crystal balls are not good enough to rule out the possibility that we may one day have a kind of agreement that never has a payment instrument. If this happens, always including `"payment_instrument": null` will be undesirable.
Update integration tests to …

PP-9545 Assert that we do not send "payment_instrument": null

---

src/main/java/uk/gov/pay/api/agreement/resource/AgreementsApiResource.java
src/main/java/uk/gov/pay/api/exception/mapper/CancelAgreementExceptionMapper.java
src/test/java/uk/gov/pay/api/exception/mapper/CancelAgreementExceptionMapperTest.java
src/test/java/uk/gov/pay/api/it/AgreementsIT.java
src/test/java/uk/gov/pay/api/utils/mocks/BaseConnectorMockClient.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java

Correctly handle connector returning 404, 400 and 500 appropriately when cancelling an agreement and add tests to prove this.

PP-9498 Make cancel agreement handle error conditions

---

src/main/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapper.java
src/test/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapperTest.java
src/test/java/uk/gov/pay/api/it/CreatePaymentIT.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java

Handle connector returning an `INCORRECT_AUTHORISATION_MODE_FOR_SAVE_PAYMENT_INSTRUMENT_TO_AGREEMENT` error when creating a payment. This happens if we send connector `"save_payment_instrument_to_agreement": true`, `"authorisation_mode": "agreement"` and an `"agreement_id"`.
Public API will send a request like this to connector if it receives a request with `"authorisation_mode": "agreement"` and `"set_up_agreement"` (with or without `"agreement_id"`).
Public API will respond with a 400 response with the error code P0104 and the message ‘Unexpected attribute: set_up_agreement‘.

PP-9498 Handle connector incorrect auth mode for set up agreement

---

openapi/publicapi_spec.json
src/main/java/uk/gov/pay/api/model/CreatePaymentRefundRequest.java

The refund_amount_available field on the create refund request was marked as readonly. As this is a field on a request, it should not be marked as readonly. This was causing issues for a user generating a request library using the file.

BAU Fix readonly field in OpenAPI spec

---

.github/workflows/run-tests.yml
pom.xml
src/test/java/uk/gov/pay/api/it/CreateAgreementIT.java
src/test/java/uk/gov/pay/api/it/PaymentResourceITestBase.java
src/test/java/uk/gov/pay/api/it/ResourcesFilterITestBase.java
src/test/java/uk/gov/pay/api/it/rule/RedisContainer.java
src/test/java/uk/gov/pay/api/it/rule/RedisDockerRule.java
src/test/java/uk/gov/pay/api/it/telephone/TelephonePaymentResourceITBase.java
src/test/java/uk/gov/pay/api/it/validation/CreatePaymentWithHttpReturnUrlIT.java
src/test/java/uk/gov/pay/api/service/AgreementServiceTest.java
src/test/java/uk/gov/pay/api/utils/Payloads.java

- updated int tests to use testcontainers over now EOL docker client
- changed redis version to match engine version in use on elasticache
- updated GHA to use correct redis image
- moved static method to utility class, this fixes a unit test failure in CI environments where no docker engine was available
- removed Docker Client dependency, this is no longer needed as TestContainers instruments all ephemeral test dependencies

PP-10004 M1 support for integration tests

---

openapi/publicapi_spec.json
src/main/java/uk/gov/pay/api/model/CreatePaymentResult.java
src/main/java/uk/gov/pay/api/model/Payment.java
src/main/java/uk/gov/pay/api/model/PaymentSettlementSummary.java
src/main/java/uk/gov/pay/api/model/search/dispute/DisputeForSearchResult.java

- there is a  discrepancy regarding the date formats defined in the open API spec. The dates in the spec are in the format 2015-08-14T12:35:00Z but when they are returned by the API they're in the format 2022-09-29T12:20:03.873Z

BAU correct swagger examples to the right format

---

openapi/publicapi_spec.json
src/main/java/uk/gov/pay/api/common/ResponseConstants.java
src/main/java/uk/gov/pay/api/model/CardPayment.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java

Context
- OpenApi spec is being updated to better reflect Pay API documentation
- One aspect of this is Response descriptions which are currently
defined in each endpoint as string literals, with lots of duplication.
- This is being refactored to facilitate changes to the descriptions.
- created ResourceConstants class with commonly-occurring response descriptions
- pointed PaymentResource response descriptions to the constants where appropriate
- where descriptions differed, these were left as string literals.
- this particular change is refactoring only, not affecting the openapi spec.
- other Resource classes will be dealt with in subsequent PRs.

PP-10265 Responses As Constants for PaymentResource

---

src/main/java/uk/gov/pay/api/resources/PaymentRefundsResource.java
src/main/java/uk/gov/pay/api/resources/SearchDisputesResource.java
src/main/java/uk/gov/pay/api/resources/SearchRefundsResource.java

- OpenApi spec is being updated to make it more consistent with the Pay API documentation
- this is a refactoring step to facilitate those changes
- where ApiResponse descriptions match the standard descriptions as declared in ResponseConstants,
pointed the ApiReponse descriptions to ResponseConstants
- where the existing descriptions related to codes not covered in ResponseConstants,
or where the descriptions differ from their equivalents in ResponseConstants, no changes have been made,
so this change has no effect on the publicapi_spec

PP-10265 Point ApiResponse descriptions to constants

---

src/main/java/uk/gov/pay/api/agreement/model/Agreement.java
src/main/java/uk/gov/pay/api/agreement/model/AgreementLedgerResponse.java
src/test/java/uk/gov/pay/api/it/AgreementsIT.java
src/test/java/uk/gov/pay/api/utils/mocks/AgreementFromLedgerFixture.java

Include the `user_identifier` attribute on the agreement endpoint (search and get one).

PP-10437 Map agreement user identifier now sent from ledger

---

pom.xml
src/main/java/uk/gov/pay/api/exception/mapper/CreateAgreementExceptionMapper.java
src/main/java/uk/gov/pay/api/model/RequestError.java
src/test/java/uk/gov/pay/api/exception/mapper/CreateAgreementExceptionMapperTest.java
src/test/java/uk/gov/pay/api/service/AgreementServiceTest.java

Context: If connector receives a create agreement request from public_api for a gateway account that does not have recurring payments enabled, it will return a 422 response with the error_identifier RECURRING_CARD_PAYMENTS_NOT_ALLOWED
- Update CreateAgreementExceptionMapper to handle the 422 response from connector, sending a 422 response with the error identifier CREATE_AGREEMENT_RECURRING_CARD_PAYMENTS_NOT_ALLOWED
- Add unit tests

PP-10439 Handle 422 Recurring Payments Not Allowed response

---

src/main/java/uk/gov/pay/api/agreement/resource/AgreementsApiResource.java
src/main/java/uk/gov/pay/api/service/SearchAgreementsService.java
src/test/java/uk/gov/pay/api/it/AgreementsIT.java
src/test/java/uk/gov/pay/api/service/SearchAgreementsServiceTest.java
src/test/resources/pacts/publicapi-ledger-search-agreements-with-page-and-display-size.json

- Add SearchAgreementsService to call ledger to search agreements and transform the response to the Public API response. When the response is converted, convert the pagination links returned by ledger into public API links.
- Add pact test for getting agreements from ledger that checks that we transform the pagination links correctly.

PP-10485 Include pagination links for search agreements

---

openapi/publicapi_spec.json
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/service/PaymentSearchParams.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceSearchIT.java
src/test/java/uk/gov/pay/api/service/CardPaymentSearchServiceTest.java
src/test/resources/pacts/publicapi-ledger-search-payment-by-agreement-id.json

Ledger already supports filtering transactions by agreement, allow the
agreement ID to be passed through.
Use the open api specs and description from the public docs.

PP-10485 Search transactions by recurring payment agreement

---

src/main/java/uk/gov/pay/api/exception/mapper/CreateAgreementExceptionMapper.java
src/main/java/uk/gov/pay/api/model/RequestError.java
src/test/java/uk/gov/pay/api/exception/mapper/CreateAgreementExceptionMapperTest.java

- Context: If RCP is not enabled for a gateway account, error code P0942 should be returned for any request to create agreement, setup agreement or take recurring payment
- Remove specific error for create agreement, replace with P0942
- Update associated unit test accordingly
- A separate PR will cover applying this error code to setting up agreements and taking recurring payments.

PP-10486 Make RCP error code more generic

---

src/main/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapper.java
src/test/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapperTest.java

Context: In the event of a setup agreement or recurring payment request from a service which does not have RCP enabled, connector will return a RECURRING_CARD_PAYMENTS_NOT_ALLOWED error response
- Map RCP error response from connector to error code P0942.

PP-10486 Map RCP error response from connector

---

openapi/publicapi_spec.json
src/main/java/uk/gov/pay/api/agreement/model/Agreement.java
src/main/java/uk/gov/pay/api/agreement/model/AgreementSearchResults.java
src/main/java/uk/gov/pay/api/agreement/resource/AgreementsApiResource.java
src/main/java/uk/gov/pay/api/service/SearchAgreementsService.java
src/test/java/uk/gov/pay/api/service/SearchAgreementsServiceTest.java

- previous updates to the openapi spec involved creating an AgreementSearchResults class purely
for the openapi spec
- update search agreements endpoint to return AgreementSearchResults instead of generic SearchResults
- correct naming and whitespace in AgreementSearchResults

PP-10441 Return AgreementSearchResults when searching agreements

---

Dockerfile
m1/arm64.Dockerfile

Upgrade image to [jdk 11.0.18](https://hub.docker.com/layers/library/eclipse-temurin/11-jre-alpine/images/sha256-4edcb9a82ae75460ff836a63d7bf2d601635233130952083f5bc79bf888ea8ad?context=explore).
See this [adr](https://github.com/alphagov/pay-architecture/blob/main/adr/024-java-base-image-pinning-strategy.md) on why we only specify the major version.
Alpine doesn't provide an ARM variant of [11.0.18_10-jre-alpine](https://hub.docker.com/layers/library/eclipse-temurin/11.0.18_10-jre-alpine/images/sha256-4edcb9a82ae75460ff836a63d7bf2d601635233130952083f5bc79bf888ea8ad?context=explore) so we've used the latest [eclipse-temurin:11-jre](https://hub.docker.com/layers/library/eclipse-temurin/11-jre/images/sha256-dd745f7e5a780d432ea24c9936721271e74853c712a58461c47aecd315ef5701?context=explore).

PP-10717: Upgrade Docker Java image to 11.0.18

---

.github/dependabot.yml

Dependabot is keen to update to `eclipse-temurin:20-jre` - we're happy with `11-jre` for the moment.

BAU: Pin to Java 11

---

.secrets.baseline
openapi/publicapi_spec.json
src/main/java/uk/gov/pay/api/exception/mapper/ViolationExceptionMapper.java
src/main/java/uk/gov/pay/api/model/RequestError.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceCreateIT.java
src/test/java/uk/gov/pay/api/resources/PaymentsResourceCreatePaymentTest.java

- implement checking the length of the Idempotency-Key header if present.
- refactor RequestError to include a `header` field
- refactor ViolationExceptionMapper to handle this violation
- add header param to PaymentsResource create payment
- add/update relevant tests
with @alexbishop1

PP-10713 implement idempotency key header violation

---

.secrets.baseline
src/main/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapper.java
src/main/java/uk/gov/pay/api/model/CreatedPaymentWithAllLinks.java
src/main/java/uk/gov/pay/api/model/RequestError.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/java/uk/gov/pay/api/service/CreatePaymentService.java
src/test/java/uk/gov/pay/api/it/AgreementsApiResourceCreateIT.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceCreateIT.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceCreateWithIdempotencyKeyIT.java
src/test/java/uk/gov/pay/api/it/ResourcesFilterLocalRateLimiterIT.java
src/test/java/uk/gov/pay/api/it/ResourcesFilterRateLimiterIT.java
src/test/java/uk/gov/pay/api/it/validation/CreatePaymentWithHttpReturnUrlIT.java
src/test/java/uk/gov/pay/api/it/validation/CreatePaymentWithPrefilledCardholderDetailsValidationIT.java
src/test/java/uk/gov/pay/api/it/validation/PaymentsResourceLanguageValidationIT.java
src/test/java/uk/gov/pay/api/resources/PaymentsResourceCreatePaymentTest.java
src/test/java/uk/gov/pay/api/service/CreatePaymentServiceTest.java
src/test/java/uk/gov/pay/api/utils/mocks/BaseConnectorMockClient.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java

- add idempotency key header to endpoint
- add idempotency key validations
- pass idempotency key to connector client
- call connector with idempotency key if applicable
- handle responses from connector
- implement tests for happy path and not so happy path
- refactor a few things as needed
with @alexbishop1

PP-10713 Implement passing idempotency key to connector

---

src/test/java/uk/gov/pay/api/service/CreatePaymentServiceTest.java
src/test/resources/pacts/publicapi-connector-create-payment-with-idempotency-key-200-response.json
src/test/resources/pacts/publicapi-connector-create-payment-with-idempotency-key-409-response.json

Add a Pact test to test the scenario where a second request is received to create a payment with an idempotency key and request body that matches that of an existing payment, which causes connector to return the original payment with a 200 response.
with @SandorArpa

PP-10713 Pact test for idempotency key create matching payment

---

src/main/java/uk/gov/pay/api/exception/mapper/ViolationExceptionMapper.java

- the if statement in ViolationExceptionMapper.getFieldNameRequestError needs an extra bracket: && has higher precedence than ||
So if we have A && B && C || D || E then it effectively becomes (A && B && C) || D || E

BAU fix if statement

---

src/main/java/uk/gov/pay/api/resources/PaymentsResource.java

The Idempotency-Key pattern matcher validataion is sometimes executed before the length check. This leads to a false error where the error `Header [Idempotency-Key] can only contain alphanumeric characters and hyphens` is returned.
- add allow empty string to regex

BAU fix flaky tests

---

openapi/publicapi_spec.json
src/main/java/uk/gov/pay/api/agreement/model/Agreement.java
src/main/java/uk/gov/pay/api/ledger/model/AgreementSearchParams.java

We don’t have any process/code that sets the payment_instrucment/agreement status to expired. Also, we don’t have any plans to set payment instruments to expired status.
- remove `EXPIRED` from agreements status
- replace `expired` with `inactive` (it was forgotten in PP-10949)

PP-10977 remove expired status from agreement

---

openapi/publicapi_spec.json
src/main/java/uk/gov/pay/api/model/PaymentState.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceCreateIT.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceGetIT.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceSearchIT.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentResultBuilder.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentSearchResultBuilder.java
src/test/java/uk/gov/pay/api/it/fixtures/PaymentSingleResultBuilder.java

- add canRetry to `PaymentState`
- implement including canRetry when getting/searching transactions (if applicable)
- add test
- BAU remove forgotten debug code (`.log().body()`)

PP-10982 add can_retry to external transaction state

---

src/test/java/uk/gov/pay/api/it/PaymentsResourceGetIT.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceSearchIT.java
src/test/java/uk/gov/pay/api/service/GetPaymentServiceLedgerTest.java
src/test/resources/pacts/publicapi-ledger-get-rejected-recurring-payment-with-can-retry-true.json

- add a new pact test that verifies a rejected recurring payment with can retry true against ledger
- correct rejected state's status to the right one in tests

PP-10982 add new pact test

---

src/main/java/uk/gov/pay/api/ledger/service/LedgerUriGenerator.java
src/test/java/uk/gov/pay/api/utils/mocks/LedgerMockClient.java
src/test/resources/pacts/publicapi-ledger-search-agreements-with-page-and-display-size.json

- Removed `status_version` from the agreements URI when querying Ledger for agreements. This field is not required for agreements

PP-10509 Remove `status_version` from agreements URI

---

src/test/java/uk/gov/pay/api/service/CancelAgreementConnectorServicePactTest.java
src/test/java/uk/gov/pay/api/service/GetOneAgreementLedgerServicePactTest.java
src/test/java/uk/gov/pay/api/service/SearchAgreementsLedgerServicePactTest.java

- remove AgreementService from the pact tests and use the actual service that interacts with the backend to run them
- refactor tests accordingly
with @james-peacock-gds

PP-11188 refactor agreement pact tests

---

pom.xml
src/main/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapper.java
src/main/java/uk/gov/pay/api/model/RequestError.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceCreateIT.java
src/test/java/uk/gov/pay/api/service/CreatePaymentServicePactTest.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java
src/test/resources/pacts/publicapi-connector-create-payment-link-payment-with-card-number-in-reference.json

- Handles `CREATE_PAYMENT_CARD_NUMBER_IN_PAYMENT_LINK_REFERENCE_ERROR` from connector and returns P0105 (new) error code

PP-11167 Handle card number in payment link reference error

---

src/main/java/uk/gov/pay/api/resources/SecuritytxtResource.java

According to https://gds-way.cloudapps.digital/standards/vulnerability-disclosure.html#security-txt, we should be redirecting with a 302 rather than a 307 when returning security.txt.

PP-11087: Use status 302 for security.txt redirect

---

pom.xml
src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/app/config/PublicApiConfig.java
src/main/resources/config/config.yaml
src/test/resources/config/test-config.yaml

Set up a prometheus metric endpoint /metrics.
Append ECS metadata info (via the PrometheusDefaultLabelSampleBuilder class in pay-java-commons) as default labels.
Analogus to alphagov/pay-connector#4625, which has been tested.

PP-11223: Set up prometheus metrics

---

pom.xml

Publicapi failed to deploy due to:
```
at uk.gov.pay.api.app.PublicApi.main(PublicApi.java:220)
Caused by: java.lang.ClassNotFoundException: org.json.JSONException
```
The transitive org.json:json dependency from pay-java-commons was not included due to the test scope overriding it in publicapi's pom.xml

PP-11223: Fix deploy

---

.secrets.baseline
README.md
pom.xml
src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/app/config/PublicApiConfig.java
src/main/resources/config/config.yaml
src/test/resources/config/empty-elevated-accounts-test-config.yaml
src/test/resources/config/empty-low-traffic-accounts-test-config.yaml
src/test/resources/config/test-config.yaml

Remove graphite metrics configuration and sending.
Also fixed the description of DISABLE_INTERNAL_HTTPS env var in the README
Check build passes ok 🥳 and explicitly wait for the e2e tests to pass
* ~Introduced any new environment variables /~ removed existing environment variable
* ~Added new API / updated existing API definition~

PP-11228: Remove graphite metrics sending and config

---

build-local.sh
src/main/java/uk/gov/pay/api/app/PublicApi.java

Now we don't need to build our default labels in the app (since they are now added by the sidecar) we should remove the default sample builder.
1. Remove default sample builder
2. Update local build script to account for m1 macs, and use the correct container tag
This change has already been rolled out to connector and is working well.

PP-11154: Update initialise prometheus metrics

---

openapi/publicapi_spec.json
src/main/java/uk/gov/pay/api/model/search/card/RefundForSearchRefundsResult.java

The `payment_id` field is included in the refund object and documented at https://docs.payments.service.gov.uk/api_reference/search_refunds_reference/#attributes-you-ll-get-in-a-search-refunds-response but it is not included in our OpenAPI spec.
Since it’s already there and documented, people will be relying on it so the only sensible thing to do is to include it in the OpenAPI spec.
Description nabbed from the documentation and is identical to that used elsewhere in the OpenAPI spec.

ZD-5631868 Add payment_id to refund OpenAPI spec

---

pom.xml
src/main/java/uk/gov/pay/api/app/PublicApi.java
src/main/java/uk/gov/pay/api/app/config/PublicApiConfig.java
src/main/java/uk/gov/pay/api/app/config/PublicApiModule.java
src/main/java/uk/gov/pay/api/app/config/RateLimiterConfig.java
src/main/java/uk/gov/pay/api/app/config/RestClientConfig.java
src/main/java/uk/gov/pay/api/filter/ratelimit/RedisRateLimiter.java
src/main/java/uk/gov/pay/api/resources/HealthCheckResource.java
src/main/java/uk/gov/pay/api/resources/PaymentsResource.java
src/main/resources/config/config.yaml
src/test/java/uk/gov/pay/api/filter/ratelimit/RedisRateLimiterTest.java
src/test/java/uk/gov/pay/api/resources/HealthCheckResourceTest.java

- Upgrade Dropwizard to v3 latest.
- Use dropwizard-dependencies BOM, which removes the need to pull in some dependencies ourselves

PP-12175 upgrade Dropwizard to version 3

---

src/test/java/uk/gov/pay/api/auth/AccountAuthenticatorTest.java
src/test/resources/config/test-config.yaml

This will save some effort looking into terraform to see what the value for the PUBLIC_AUTH_URL env var is.

bau: Make publicauth endpoint clear

---

pom.xml
src/test/java/uk/gov/pay/api/it/telephone/PredefinedValidationIT.java

Some imports were transitive, taken from Spotify's docker-client.
- update pay-java-commons to 1.0.20240528083746
- refactor given imports to use org.apache.commons.lang3

PP-12177 refactor imports

---

src/main/java/uk/gov/pay/api/filter/ratelimit/RedisRateLimiter.java

- Update logging for exceptions caught on rate limiter allowance update
- Adds logging of exception classname
- This is to help diagnose the cause of timeout errors being caught here, and may be removed once resolved

PP-12517 Update logging for rate limiter exceptions

---

src/main/resources/config/config.yaml

https://github.com/redis/lettuce/wiki/Frequently-Asked-Questions#im-seeing-rediscommandtimeoutexception recommends setting DEBUG level for the logger io.lettuce.core.protocol to help diagnose RedisCommandTimeoutExceptions. We've
[agreed](https://gds.slack.com/archives/C03B49R80NA/p1718201774505239?thread_ts=1718195250.871609&cid=C03B49R80NA) that we can turn DEBUG logging temporarily.

PP-12517: Set DEBUG level for the logger io.lettuce.core.protocol

---

src/main/resources/config/config.yaml

Same as https://github.com/alphagov/pay-publicapi/pull/2012. Setting DEBUG level again as the RedisCommandTimeoutExceptions are still occurring, albeit at a much reduced frequency (reason as yet unknown).

PP-12517: Set DEBUG level for the logger io.lettuce.core.protocol again

---

src/test/resources/pacts/publicapi-ledger-search-disputes-no-result.json

`publicapi-ledger-search-disputes-no-result` pact test fails provider verification on Ledger. It is due to the stricter rules introduced by pact v4 through pay-java-commons.
- fix pact descriptor file

PP-12789 fix pact test

---

src/main/java/uk/gov/pay/api/model/Charge.java
src/main/java/uk/gov/pay/api/model/search/card/PaymentForSearchResult.java
src/main/java/uk/gov/pay/api/utils/AuthorisationSummaryHelper.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceGetIT.java
src/test/java/uk/gov/pay/api/it/ledger/TransactionsResourceIT.java
src/test/java/uk/gov/pay/api/utils/AuthorisationSummaryHelperTest.java

Only include authorisation summary in public API responses if 3D Secure was required.
- add a helper class that determines whether we need to include AuthorisationSummary to the return API call objects

PP-13201 implement AuthorisationSummary.ThreeDSecure not required

---

src/main/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapper.java
src/main/java/uk/gov/pay/api/model/RequestError.java
src/test/java/uk/gov/pay/api/it/rule/RedisDockerRule.java
src/test/java/uk/gov/pay/api/it/validation/CreatePaymentWithHttpReturnUrlIT.java
src/test/java/uk/gov/pay/api/utils/mocks/BaseConnectorMockClient.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java
src/test/java/uk/gov/pay/api/utils/mocks/Junit5ConnectorMockClient.java
src/test/java/uk/gov/pay/api/utils/mocks/MockHelperFunctions.java

Deal with possible NON_HTTPS_RETURN_URL_NOT_ALLOWED_FOR_A_LIVE_ACCOUNT when creating a charge.
This commit also upgrades CreatePaymentWithHttpReturnUrlIT to a junit5 test. As part of this MockHelperFunctions is created so WireMockExtension (junit5) and WireMockClassRule (junit4) can be DRY.

PP-13315: Deal with NON_HTTPS_RETURN_URL_NOT_ALLOWED_FOR_A_LIVE_ACCOUNT

---

src/main/java/uk/gov/pay/api/app/config/PublicApiModule.java

- Redis: enables keepalive to reduce the need to handle failed connections during command runtime.
- This is as recommended by AWS docs https://docs.aws.amazon.com/AmazonElastiCache/latest/dg/BestPractices.Clients-lettuce.html

PP-13367 Enable keepalive

---

.secrets.baseline
Dockerfile
src/main/java/uk/gov/pay/api/app/config/PublicApiModule.java
src/main/java/uk/gov/pay/api/app/config/RedisConfiguration.java
src/main/java/uk/gov/pay/api/managed/RedisClientManager.java
src/main/resources/config/config.yaml
src/test/resources/config/empty-elevated-accounts-test-config.yaml
src/test/resources/config/empty-low-traffic-accounts-test-config.yaml
src/test/resources/config/test-config.yaml

As per AWS recommendations https://docs.aws.amazon.com/AmazonElastiCache/latest/dg/BestPractices.Clients-lettuce.html
- Updated DNS_TTL to 10s
- Updated Exponential reconnect strategy.
- With the default lettuce config, the exponential retry strategy uses an exponential base of 2 and an upper bound of 30 seconds. So we will likely fall back to the local rate limiter for 30+ seconds (as it uses DNS cache within the first 15 seconds of retries).
- With the new config, reconnect attempts will be at 100ms, 1000ms, 10000ms and every 10000ms.
- so if there are any one-off issues, the Redis client can reconnect at 100ms and 1000ms. For longer timeouts (during failovers or upgrades) attempts can be every 10 seconds. This also coincides with DNS_TTL. For re-connect attempts at 10000ms, PublicAPI …

PP-13367 Update DNS_TTL and lettuce reconnect delay

---

src/main/java/uk/gov/pay/api/app/config/PublicApiModule.java
src/main/java/uk/gov/pay/api/app/config/RedisConfiguration.java
src/main/resources/config/config.yaml
src/test/resources/config/empty-elevated-accounts-test-config.yaml
src/test/resources/config/empty-low-traffic-accounts-test-config.yaml
src/test/resources/config/test-config.yaml

- Updated `reconnectDelay` config to match AWS docs
- Renamed Redis `reconnectDelay` variables as Full Jitter is not truly exponential. FullJitter delay uses the power of 2 during the calculation and the `base` configured is used to limit the upper bound for a specific attempt. See FullJitter reconnect delay calculation in https://github.com/redis/lettuce/blob/main/src/main/java/io/lettuce/core/resource/FullJitterDelay.java#L59-L63 (FullJitter is explained in AWS docs https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/)
Reconnect delays calculated locally (with DEBUG enabled and Redis stopped) for the FullJitter approach are as follows:
```
Reconnect attempt 1, delay 100ms
Reconnect attempt 2, delay 182ms
Reconnect attempt 3, delay 386ms
Reconnect attempt 4, delay …
```

PP-13367 Rename redis reconnect delay config vars

---

pom.xml

- point to updated pay-java-commons so we can use the new `BELOW_MINIMUM_AMOUNT` error identifier necessary for restricting Stripe transactions to less than 30p.

PP-13359 update java commons version

---

src/main/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapper.java
src/test/java/uk/gov/pay/api/exception/mapper/CreateChargeExceptionMapperTest.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceCreateIT.java
src/test/java/uk/gov/pay/api/utils/mocks/ConnectorMockClient.java

- Respond appropriately to an AMOUNT_BELOW_MINIMUM response from connector in relation to a create payment request for a Stripe account (we are limiting Stripe payments to 30p or more to avoid the issues associated with fees exceeding the transaction amount).
- Include link to the 'amount' section of the tech docs in error responses for this scenario and for the zero amount not allowed scenario.
- The change to the connector logic to cover this scenario will be made subsequently.

PP-13359 Handle AMOUNT_BELOW_MINIMUM

---

src/test/java/uk/gov/pay/api/service/CardPaymentSearchServicePactTest.java
src/test/resources/pacts/publicapi-ledger-search-payment-with-charge-in-success-state-that-has-exemption-honoured.json

Add a pact test that searches Ledger for a transaction which has an honoured corporate exemption. This test is needed because Ledger builds transactions in different ways for a get one and a search call.

PP-13334 add a ledger as provider pact test

---

src/main/java/uk/gov/pay/api/filter/RateLimiterKey.java
src/main/java/uk/gov/pay/api/filter/ratelimit/RedisRateLimiter.java
src/test/java/uk/gov/pay/api/filter/ratelimit/LocalRateLimiterTest.java
src/test/java/uk/gov/pay/api/filter/ratelimit/RateLimitManagerTest.java
src/test/java/uk/gov/pay/api/filter/ratelimit/RateLimiterTest.java

The rate limiting implementation can be quite to understand; hopefully adding the comments will help. Rate limiting is currently applied using discrete time blocks, but an idea for the future is to use a sliding window and do a count for requests in the last second/minute/hour window which could potentially make the logic simpler.
This commit also makes the RateLimiterKey constructor private; this is more correct as it's currently public for the sake of convenient unit testing.

PP-13429: Clarify rate limiting functionality

---

README.md
src/main/resources/config/config.yaml

We want to enable TLS encryption for connections to redis, it's already in the code, we just need to take the configuration via env var and default to false (the current value)
Check the syntax is correct for loading via env var. See the e2e tests work
N/A
* ~Added new API / updated existing API definition~

PP-13949: Allow setting the redis ssl setting via env var REDIS_SSL

---

src/main/java/uk/gov/pay/api/json/RequestJsonParser.java
src/test/java/uk/gov/pay/api/it/AgreementsApiResourceCreateIT.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceCreateIT.java
src/test/java/uk/gov/pay/api/it/PaymentsResourceGetIT.java
src/test/java/uk/gov/pay/api/json/RequestJsonParserTest.java

With this change, we are improving the input validation for the reference and
description fields so that it matches the same validation currently in place
in SelfService.
* ~~Introduced any new environment variables / removed existing environment variable~~
* ~~Added new API / updated existing API definition~~

PP-14054 Improve validation for some fields

---

src/test/java/uk/gov/pay/api/service/CardPaymentSearchServicePactTest.java
src/test/resources/pacts/publicapi-ledger-search-payment-by-agreement-id.json

Update an existing Pact test between connector and ledger to verify the agreement_payment_type property.

PP-14434 add rcp reason to a pact test
